### ISSUE TITLE
Reinstate websockets

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#102]
Websockets should provide less latency than HTTP requests for calls to `@update` etc. See `web/stencila/connection.js` for JS implementation of the WAMP protocol. On the C++ side, Websockets with WAMP are all ready implemented but will need application to Sheets.

**Comment by michael** [comment]
You have experience with WAMP? We are also evaluating what the best options are for implementing the protocol for our realtime document editing hub. I found http://autobahn.ws/ but did not have time to evaluate yet.

**Comment by nokome** [comment]
@michael : I have implemented a basic version of WAMP RPC for the client in JS [web/stencila/connection.js](https://github.com/stencila/stencila/blob/master/web/stencila/connection.js) and for the server in C++ [cpp/stencila/component-serve.cpp](https://github.com/stencila/stencila/blob/master/cpp/stencila/component-serve.cpp#L89). I didn't want to overcomplicate things so kept it very simple and didn't try to follow the protocol slavishly. Switching to an exisiting implemenations http://wamp-proto.org/implementations/, at least on the client side, could be useful.

**Comment by nokome** [comment]
Refactoring done in foundational C++ to reduce code duplication between the `request()` method which handles HTTP requests and the `message()` method which handles Websocket messages. Applied to sheets. Still need to apply to stencils.

**Comment by nokome** [comment]
@michael : there is an issue with the current Websockets implementation  which breaks using sheets on the hub (previously each ws socket connection was bound to an individual sheet or stencil but now the hub expects one ws connection per session - so the routing to components is broken). I'll let you know when it is fixed.

**Comment by nokome** [comment]
@michael : I've fixed the Websocket issue - cell updates feel a lot faster to me, would be interested to hear what you think. Function widgets pop up nicely, although equation parsing not perfect (e.g. two functions in the same cell).

But don't use the save and commit buttons - they are causing issues (e.g. #150) and may make your session unresponsive. If that happens you can manually shutdown the session at https://stenci.la/sessions. Then refresh the page and another one will get created.

**Comment by nokome** [comment]
The store/restore stuff seems to be working OK now so it should be safe to hit the save button - next session will restore from last snapshot
