### ISSUE TITLE
import of xlsx failed in  https://hub.stenci.la

### ISSUE THREAD

**Issue by ouboub** [stencila/stencila#1030]
Hi
Maybe I misunderstood something, but I created an account in  https://hub.stenci.la
and tried to import a xlsx files, that contained a bit more complicated formula (with some ifs and mins)
and wanted to see how stencila could deal with it.

The file was never really imported. All I can see are symbols 
(se https://hub.stenci.la/uwe-richard-otto/tribunal/files/baremo-antonio-raul.xlsx!details)
which make me belive that a zip file is displayed (which is true xlsx is some compressed xml)

so what went wrong, When pressing convert nothing happenes.

thanks

Uwe Brauer

**Comment by ouboub** [comment]
I managed to use the convert button, but it did not help, the result 
is 
`{
  "new": {
    "size": 12273,
    "encoding": null,
    "mimetype": null,
    "modified": 1625735948.7954535,
    "fingerprint": "8bf395d74b013fe67ad8354da3cdd069bf47533450d637571305df464c573780"
  }
}`

**Comment by alex-ketch** [comment]
Thanks for reporting this @ouboub. The project is private and I can't see the file in question unfortunately.
To help debug this, would it be possible for you to invite me (alexander@stenci.la) to the project using the `Sharing` tab from the project sidebar please? If it's sensitive, would it be possible to create a sample file with a similar formula to the one you're having problems with?

Thanks again!

**Comment by ouboub** [comment]
>>> "AK" == Alex Ketch ***@***.***> writes:

> Thanks for reporting this @ouboub. The project is private and I
> can't see the file in question unfortunately. To help debug this,
> would it be possible for you to invite me ***@***.***) to
> the project using the `Sharing` tab from the project sidebar
> please? If it's sensitive, would it be possible to create a sample
> file with a similar formula to the one you're having problems with?

Thanks for you quick reply. The file is a bit sensitive but I will
remove the sensitive parts and retry again. However I want to do that
with the original MS excel not with libreoffice or wps I am using on my
Linux machine. 

To be on the save side I will also send it to you via regular email if
you don't mind.

**Comment by ouboub** [comment]
Hi Alex

I uploaded a file (in xlsx and ods format), that does not contain
sensitive information.
I, hopefully,  invited you to share these documents, but just case I
attach them.


Regards

Uwe

**Comment by ouboub** [comment]
PS o great, when I try to attach the documents, the system responds:
that it does not support xlsx, but the file is an xlsx file, ods however works, is this a BUG?
or does he want .XLSX, no it does not make a difference. so there is a bug: 
the system does accept XLSX or xlsx, great

[Exper-sten.ods](https://github.com/stencila/stencila/files/6789899/Exper-sten.ods)
