### ISSUE TITLE
Windows distributions fail to install

### ISSUE THREAD

**Issue by alex-ketch** [stencila/stencila#1039]
I haven't been able to track down a successful build, but at least from v0.89.1 and above the installers fail with the following error:

![Screenshot 2021-07-15 at 16 12 33](https://user-images.githubusercontent.com/1646307/125861904-ee0c8708-9c25-4f09-804a-97ce117ed301.png)

(Apologies for the screenshot, I couldn't select and copy the text for some reason)

**Comment by nokome** [comment]
I was unable to reproduce this issue. I was able to install and use https://github.com/stencila/stencila/releases/download/v0.97.1/Stencila-0.97.1.Setup.exe on a Windows 10 VirtualBox VM.
