### ISSUE TITLE
Fail to install on WINDOW 10

### ISSUE THREAD

**Issue by happydentist** [stencila/stencila#1059]
I haven't been able to track down a successful build, but at least from Stencila-0.103.0.Setup.exe on WINDOW 10 and above the installers fail with the following error:
![s](https://user-images.githubusercontent.com/35398116/127592445-e78b7aa5-55c9-4a84-9fec-0c8a078fcf62.png)

**Comment by happydentist** [comment]
Stencila-0.104.0.Setup.exe also the same error
![s1](https://user-images.githubusercontent.com/35398116/127606155-999bce30-2e3b-4d58-857b-99c5f3ebd203.png)

**Comment by alex-ketch** [comment]
Thanks for reporting this @happydentist, I will take a look and try to get to the Windows builds.
Could I ask you to try a [build from v100](https://github.com/stencila/stencila/releases/tag/v0.100.0) please, and see if you see the error shown in [this issues](https://github.com/stencila/stencila/issues/1039)?

**Comment by happydentist** [comment]
After run Stencila-0.100.0.Setup.exe, It is OK
![S100](https://user-images.githubusercontent.com/35398116/127672461-38a5e51a-6d0c-4d5b-bad0-fb4ae0f891f2.png)
Then 3 or 4 second later, it will update to v104, 
![S100_104](https://user-images.githubusercontent.com/35398116/127672713-9520afb3-675a-4108-8d55-62846d1c8f54.png)
And restart Stencila, show error again
![s100_104_start](https://user-images.githubusercontent.com/35398116/127673042-97d2b4ad-24e1-41c9-9cd4-0ee2a8667d84.png)

**Comment by alex-ketch** [comment]
Thanks for confirming @happydentist. I will let you know as soon as a fix is released

**Comment by happydentist** [comment]
Thanks

**Comment by nokome** [comment]
In case it helps, I'm getting this error in development, on `master` when running `npm start` in the `desktop` folder.

**Comment by happydentist** [comment]
install Stencila-0.106.0.Setup.exe failed
![s106](https://user-images.githubusercontent.com/35398116/128018999-b7392e97-290a-4a46-95b4-2b003ac9b5ca.png)

**Comment by alex-ketch** [comment]
Thanks for your patience @happydentist, this should now be fixed in the latest release.
Let me know if you encounter any other issues
