### ISSUE TITLE
A way to restore examples once we broke them

### ISSUE THREAD

**Issue by michael** [stencila/stencila#106]
We managed to break the demos/sheets/iris example. Is there a way for us to just reset it?

**Comment by nokome** [comment]
Doesn't look broken to me at https://stenci.la/demo/sheets/iris/ - perhaps you just broke the clone in your session - that is temporary to the session (at the moment). So, try deactivating whatever sheet you are in and then reactivating - it should reclone

**Comment by oliver----** [comment]
Yeah, we tried to deactivate, but didn't seem to work.. We will try again...

**Comment by nokome** [comment]
I will close that session (number 26) now...

**Comment by nokome** [comment]
There is now an API method exposed to stop a session - if you need to : https://stenci.la/api/#!/Sessions/put_sessions_id_stop i.e. `curl -X PUT --header "Accept: application/json" "https://stenci.la/sessions/26@stop"`
