### ISSUE TITLE
Still activate problems

### ISSUE THREAD

**Issue by michael** [stencila/stencila#108]
Maybe you are working on it currently because it was working an hour ago. I get:

![image](https://cloud.githubusercontent.com/assets/2931/12434356/82c392a2-bf06-11e5-896c-044ee6033daa.png)

We call it a day now.. can you check out the substance-dev branch and run with my credentials:

```js
STENCILA_HUB_TOKEN=0169r7177msDcBkT/OOmrnGD0wOO9rHgIn8UCSMYQM75wbI00yLL9ag2KanA1+tMmNFfa2DLADbIL9b63Ybg== node server.js https://stenci.la
```

and then just open that empty sheet:

http://localhost:5000/michael/SCndozXOTbOk/

If that's working I think we have a working setup for tomorrow. Thanks! See you tomorrow!

**Comment by nokome** [comment]
Sorry, I didn't see this until just now. Yes, there were some serious issues with Docker using up all the disk space on the worker. So, any attempts to start a new session were failing. It is a known issue and I am working on some maintenance scripts.

I have deleted that token you posted above. Anyone could use it to access your account :-1: . You will need to generate a new one at https://stenci.la/api#!/Tokens/post_tokens - no need to specify any data, just press the button. One thing to do is to limit the scope of what can be done using token access - but at the moment it is open.

I've worked on the API as discussed and it's looking nice. I will test on your branch now

**Comment by nokome** [comment]
@michael : I have tested `http://localhost:5000/michael/SCndozXOTbOk/` with my creds and it calls `@activate` straight away - but there are some JS errors. Maybe you try out in the morning and ping me if there are any issues.

**Comment by michael** [comment]
Ah yeah, that wasn't too smart. I'll check.

**Comment by michael** [comment]
Works. JS errors are regressions of our refactor. We will merge back into develop when it's ready to test.
