### ISSUE TITLE
Disambiguate HTML exchange format

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#109]
Looking at the Sheet HTML, there is atm. no way to distinguish

`1.0` and `=1.0`

I.e. in both cases the HTML representation looks like

```
<td data-expr='1.0' data-type='real'>1</td>
```

I would suggest this specification:

- primitives (string, int, real):

```
  <td>foo</td>
  <td>1</td>
  <td>1.0</td>
```

- expressions: e.g. `=bar(1,2,3)`

```
<td data-expr='bar(1,2,3)' data-type='real'>1</td>
```

- and named expressions: e.g., `foo=bar(1,2,3)`

```
<td data-name='foo' data-expr='bar(1,2,3)' data-type='real'>1</td>
```

**Comment by oliver----** [comment]
The workaround using `data-kind` works fine with a running session.
But not with a fresh session, there `data-kind` is not defined in any cell.

**Comment by nokome** [comment]
The difference between running and fresh session may be due to different versions of the code that produced the HTML. The 'fresh' session is actually just a static `index.html` that was created the last time the sheet was pushed to - which may have a different version of the code base. Something to keep in mind - I'm not sure of best way to avoid this while there is active development.

**Comment by nokome** [comment]
This is implemented in dccabd6. The `kind` codes are:

 *     '0' - empty or blank (only whitespace) source
 *     '1' - expression       (eg. `= 22/7`)
 *     '2' - named expression (eg. `pi = 3.14`)
 *     'n' - number literal   (eg. `42`)
 *     's' - string literal   (eg. `"foo"`)
 *     'd' - date literal     (eg. `23/12/1978`) [not currently implemented]
 *     'z' - implicit string  (eg. `foo bar`)

The convention is a bit obscure but allows for efficiency in code and exchange. Anything with an alpha code (kind > '9') is a literal expression, usually a primitive, but also including literals for date, datetime, currency etc.

@oliver----  : I have implemented you suggested output above except that all `td`s have `data-kind`.

**Comment by nokome** [comment]
Oh, also, `kind` is coming back in the response from `PUT @update`

**Comment by michael** [comment]
Good for now.
