### ISSUE TITLE
Cell update goes often wrong.

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#113]
As shown in the screenshot I was sending an update for cell 'C1', but the server tried to update 'B1' which doesn't exist.

![screen shot 2016-01-22 at 00 48 45](https://cloud.githubusercontent.com/assets/284099/12498318/f7d72a08-c0a1-11e5-81c8-404fd9d96e19.png)

**Comment by nokome** [comment]
Yes, sorry about this. This is the bug described here https://github.com/stencila/stencila/issues/89#issuecomment-173472920. So closing this - but thanks for the report! #89
