### ISSUE TITLE
Issues on First Run With Mac

### ISSUE THREAD

**Issue by psychemedia** [stencila/stencila#1134]
Stencila v. 0.114.1

Trying to install this release on Mac (10.15.7), the recommendation to load the document converter extension on first run meets with an error:

![image](https://user-images.githubusercontent.com/82988/132469184-88988891-d96c-4af8-a065-05c5aa749ab2.png)

Possibly related to https://github.com/stencila/stencila/issues/1074 ?

**Comment by psychemedia** [comment]
Loading a new project and creating a new file, the editor is sparse to say the least:

![image](https://user-images.githubusercontent.com/82988/132469730-a00153a8-d2ee-4753-9432-6e6f2ba590a7.png)

Clicking the _Settings_ cog wheel opens a blank `project.json` tab in the editor along with an error:

![image](https://user-images.githubusercontent.com/82988/132469837-783e7052-7bbf-466d-b18a-367b8a94c8c1.png)

**Comment by alex-ketch** [comment]
Thanks for taking the time to try out the desktop client and report these issues @psychemedia, much appreciated.
I've been able to reproduce both issues and will let you know once they are fixed.

As for the editor seeming sparse, we do have plans to add example content and documentation once things are a bit more defined. But do you mind if I ask what you had in mind?

**Comment by psychemedia** [comment]
Re: sparseness of editor: typically in a rich editor I'd expect a base palette of tools (header level, emphasis, bold, insert link, quotation etc.) as well as a button to raise an extended toolbar.

Also, assuming that different sorts of cells will be available (md, non-executable code(?), executable code) some way to select those. And the code language. Something like this maybe?!

![image](https://user-images.githubusercontent.com/82988/132561525-699eca39-8aaf-469b-b5e4-816bad52ffe7.png)
