### ISSUE TITLE
Desktop: record `DEBUG` level log entries in production

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1147]
Currently, in release binaries, only `INFO` level and above log entries are sent to the desktop:

https://github.com/stencila/stencila/blob/80e13023befcfdc6bb579f2dd4388a807fa28ca4/node/src/logging.ts#L29-L34

I propose to send all logs to the desktop and have the ability to filter log entries, by level, in the desktop log window. This would make debugging releases easier.

**Comment by alex-ketch** [comment]
Closed by https://github.com/stencila/stencila/pull/1202
