### ISSUE TITLE
Streamlining the terminology

### ISSUE THREAD

**Issue by michael** [stencila/stencila#116]
Data format to rendering was a bit chaotic since the structure was not clear. I made an attempt to improve this.
- Cell
  - ConstantCell (for all constants -> when there is no = sign)
  - ExpressionCell (generic implementation for any expression just displaying the value)
    - PrimitiveCell (valueType is real, integer or string)
    - ErrorCell (if an expression is erroneous)
    - ImageCell (valueType = ImageFile)

All components now follow that pattern without introducing an extra hierarchy as before. That makes is much easier to extend the system and manage the styles. If you want special handling for a new valueType you can just register a new component for it. 

``` js
// from SheetWriter
    components: {
      // Registry for different cell types
      'string': require('./PrimitiveCell'),
      'int': require('./PrimitiveCell'),
      'real': require('./PrimitiveCell'),
      'ImageFile': require('./ImageCell'),
      'error': require('./ErrorCell'),
    }
```

Let's try to use this terminology when we talk about things.

**Comment by nokome** [comment]
This seems fine with me. 

Just to note here that there is the `data-kind` attribute which the backend provides if there is a need for  further differentiation of `ConstantCell` (which in the C++ comments I have called "literal" value cells).  Also `kind` distinguishes between named and unnamed `ExpressionCell` https://github.com/stencila/stencila/issues/109#issuecomment-173448661

**Comment by michael** [comment]
Feel free to rename things in the code to make them consistent. But we can also decide to use different terms in the UI and in the evaluation context. Constant seemed a suitable cell content type for all things that don't need evaluation. So Constant vs. Expression we thought is better than Literal vs Expression. But more a matter of taste...

**Comment by nokome** [comment]
Yes, completely agree. If needed, we could do a refactoring to get naming consistency some time in the future when core concepts have solidified - but not urgent now.
