### ISSUE TITLE
Solution for editing rich text (strong, italic, links)

### ISSUE THREAD

**Issue by michael** [stencila/stencila#117]
We can implement an HTMLCellEditor that allows annotations. We will then just store the resulting HTML markup in the cell.

Implementation plan:
- Nokome implements handling of HTML on the server (import/export to TSV as markdown?)
- Michael develops HTML only editor
- Oliver and Michael develop smart editor that switches between expression mode (Ace) and constant mode (HTMLEditor).

Possible problems:

It may become harder to parse numbers. E.g. what do with `<strong>45</strong>.<em>10</em>`. Would resolve to real 45.10 right?

**Comment by nokome** [comment]
I have implemented this by defining Cila cells (indicated by a leading underscore, see #136 ). These cells are parsed and converted into HTML by the backend. This allows lots of rich text opportunities including MathJax, lists etc and having dynamic, stencil-like, text inside a sheet (when spreads are merged into contexts). An example cell having source:
```
_Some _bold_ and _italics_ and an equation |e=mc^2| 
and a list {ol {li banana} {li kiwi} {li pear}} 
Want a [link](http://stenci.la) ?
```
looks like this:
![image](https://cloud.githubusercontent.com/assets/1152336/13551643/e2e199f4-e3a5-11e5-91b9-b4a5d5649d44.png)
In the future we could define a "HTML cell" which allows one to open a HTML editor (but I think that Cila, as a Markdown-like lang, will probably meet most needs for adding rich text to sheets)
