### ISSUE TITLE
Cell mapping

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#118]
Map cell ranges to native objects. For example `B8:D20` might be mapped to a `data.frame` and given a name `data`. So then, a cell id `B8`   would get translated to `data[1,1]` and `C10` to `data[2,3]`. This would allow (a) fewer variables in context, (b) more efficient exporting as code.

Allow for "condensing" cell ranges to a native object (select a cell range, give it a name, and a data.frame gets created) and "projecting" native objects to a cell range (enter an expression like `|= data` and the data.frame gets projected onto the adjacent cell range; obviously some clash detection would be needed).

**Comment by nokome** [comment]
Some more thoughts on this:

- we might distinguish between mapping cell ie. those that define the a mapping (e.g. `data : read.table("my-data.tsv")`, kind `map`) and location cells i.e. those that represent the mapped data (kind `loc`?)
- `map` cells can be edited as per normal, but 
- `loc` cells would having some shading or other CSS to indicate they were different
- `loc` cells should act like literal, constant cells - only store values like `42` or `3.14`, not formula.
- the backend would keep track of all the `loc` cells, and if a `loc` was updated e.g. `G4 = 3` it would do the mapping and generate the code to modify the mapped object e.g. `data[4,5] = 3`.

**Comment by ern0** [comment]
Excel calls it "named ranges", so instead of "A1:A8" you can use "MyRange". When you change "MyRange", all references to it will use the changed range.

<img src="http://www.contextures.com/images/tables/partstablenames02.png" />
_Image source / see also: http://www.contextures.com/xlNames01.html#UseName_
