### ISSUE TITLE
Schema: move into this repository

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1186]
I propose to move https://github.com/stencila/schema into this repository under the the `schema` folder. It would still be published as the `@stencila/schema` NPM package, `stencila-schema` Rust crate, `stencilaschema` R package etc. but the code, and issues related to would live here. 

Much of the code in this repository is closely tied to the schema and moving it into this repository would avoid the hoops that we sometimes have to jump through when testing / deploying changes both in the schema and code that relies upon it. It is not a repository that a lot of other people have contributed or rely upon so there seems little need to have it independent of this one.

**Comment by alex-ketch** [comment]
Something to consider as we bring in projects: https://github.blog/2021-11-10-make-your-monorepo-feel-small-with-gits-sparse-index/

**Comment by nokome** [comment]
After / when moving should consider alternative approach to generating Rust enums along the lines of this comment:

```rust
// To avoid bloat it is likely that a lot of these enums
// will be generalized e.g. `OrganizationOrPerson`. `CreativeWorkTypesOrString`

patchable_variants!(
    CreativeWorkAuthors,
    CreativeWorkAuthors::Organization,
    CreativeWorkAuthors::Person
);

patchable_variants!(
    CreativeWorkFunders,
    CreativeWorkFunders::Organization,
    CreativeWorkFunders::Person
);

```

**Comment by nokome** [comment]
This move has now been done and schema lives in [`schema`](https://github.com/stencila/stencila/tree/master/schema) folder. Still some work to be done with adding package publishing to CI but will close now.
