### ISSUE TITLE
Use of el.withTagName

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#120]
I found I had to comment this out to fix exporting. @michael or @oliver---- : what is the right thing to do here : dcdded5 (I meant to comment out line 27 not 26!)

**Comment by nokome** [comment]
More generally, it would be great if someone can have a quick look at all the changes I have made to the Stencil JS - to check I haven't made any silly mistakes : https://github.com/stencila/stencila/compare/develop...2118daca94b5

**Comment by michael** [comment]
This code should actually work. Maybe we forgot to bump the substance version in package.json so el.withTagName wasn't available for you. Can you try enable the old code with the latest code from the `develop` branch?
