### ISSUE TITLE
Error when cell updates are coming in.

### ISSUE THREAD

**Issue by michael** [stencila/stencila#124]
https://github.com/stencila/stencila/blob/develop/web/sheet/ui/SheetWriter.js#L136

Sheet.normalizeValueType is no longer implemented but still called.

**Comment by michael** [comment]
Ok another problem here is that a rerender of the cell (after a cell update) is not enough anymore since we introduced individual components for different cell types.

Need to think how we do this:

- empty cells are covered by CellComponent
- now some content gets added and the cell should update
- the existing CellComponent should be disposed and instead a PrimitiveCell should be instantiated.

The same situation we have when a cell changes from an ImageCell to an Expression cell etc.

**Comment by oliver----** [comment]
There is one optimization in Component.js
https://github.com/substance/substance/blob/6bd946ac81016055d7e05a400a6fc1bf6e552ddd/ui/Component.js#L979
which causes trouble if there is no explicit props change.
E.g. in this case the CellComponent has the same props when rendered the second time.
The change is actually happening on a deeper level.
We need to find a way to make this work naturally, while still having a good performance.

**Comment by michael** [comment]
Fixed.
