### ISSUE TITLE
Desktop: Serve document preview from web client

### ISSUE THREAD

**Issue by alex-ketch** [stencila/stencila#1254]
Currently the Desktop client communicates directly with the rust based client, and requests the open document converted to HTML.
The HTML is then injected directly into the preview panel. The preview panel creates a subscription to document updates, and as edits are made, new versions of the document replace the preview contents.
Any change to the source document causes the entire preview document to be replaced.

This is not only inefficient, but more importantly causes loss of state and duplication of document subscription/update logic across clients.

We now have a [Web client](https://github.com/stencila/stencila/tree/master/web) to solve the above problems, and which is designed to manage incremental updates to the document using patches.

---

Several technical challenges:
- [x] Pass Web client server authentication key to the Desktop client
- [x] Pass document path
  - ~Currently the mock server used to validate approach can only serve items from the `/fixtures` directory~ NVM, as per @nokome's comment below, the constraint is based on the path where `stencila` server is started. 
- [x] Ensure multiple projects and documents can be open in the Desktop client at the same
- [x] Ensure Desktop client remains secure
  - To serve the preview contents via iframe, we need to alter our Content Security Policy to include something along the lines of `frame-src="http://127.0.0.1::9000"`. If left as is, then this opens up loading of anything from that endpoint.
  - To harden the iframe, I've added a `sandbox="allow-scripts"` attribute. `allow-scripts` is necessary for custom WebComponents (CodeChunks, etc.) to load.

**Comment by nokome** [comment]
> Currently the mock server used to validate approach can only serve items from the /fixtires directory

I don't think this correct. The server can serve any file from the file system but has a [path traversal](https://owasp.org/www-community/attacks/Path_Traversal) check to make sure that the requested path is inside the current working directory:

```sh
    if path.strip_prefix(&cwd).is_err() {
        return error_response(
            StatusCode::FORBIDDEN,
            "Requested path is outside of current working directory",
        );
    }
```
Causing...

![image](https://user-images.githubusercontent.com/1152336/140185226-bd721dfe-7e85-485f-8f29-d4940344ad08.png)

Currently you can by pass this by starting `stencila` in the directory from where you want to serve files. I suggest that for development convenience, we add a `--traverse` option with a warning (similar to how the `--insecure` and `--root` options allow bypassing other security checks).

More importantly we should probably allow for several server instances to run concurrently (on different ports), one for each project. Each server would have a `root_path` - the project root - which it would not be allow traversal out of.

In the longer term this would also have the benefit that the same user could access several projects, with differing rights as passed by the JSON Web Token, from the same `stencila` binary instance. Thinking here about a hosted deployment.
