### ISSUE TITLE
Session lifecycle + save workflow + optimizations

### ISSUE THREAD

**Issue by michael** [stencila/stencila#132]
We need to improve the situation here. It's kind of intransparent to a user in which session they are in and when it dies  and what gets persisted when.. I mean as we discussed the user should not care about technical concepts like sessions but we need to clearly communicate the available actions.

![image](https://cloud.githubusercontent.com/assets/2931/12748544/4a7be84a-c9ab-11e5-979c-326071fd5baa.png)

A few requirements:
- [x]  When I open a document for editing I get a user based session (@boot API)
- [ ] Save changes using a commit message (then changes are persisted as HTML and the old version is replaced or a new version is created on the server)
- [ ] Possibility for a user to switch back to the latest saved version. I would call this action 'discard changes' for the user... however internally we just destroy/disconnect the session and create a new one (connect) based on the latest saved version
- [ ] A user should be able to come back at any time and continue work (currently if you don't hit save your changes will be lost after some time) @nokome maybe you find a way to implement that
- [x] Optimization: Can we get cell updates faster? E.g. using websockets instead of http?
- [ ] Optimization: What options do we have to speed up the boot process (creating R sessions faster)?

**Comment by nokome** [comment]
Re "What options do we have to speed up the boot process". One option is to have pre-emptively launched sessions that just get assigned to a user when the boot up.

Re "Can we get cell updates faster? E.g. using websockets instead of http?" Yes definitely, Websockets would be easy to (re)implement and make things a lot faster.

Re everything else - will be working on it next.

**Comment by nokome** [comment]
I have implemented separate `save` and `commit` tools and commands. I made the commit tool more compact:

![image](https://cloud.githubusercontent.com/assets/1152336/13589587/cfa6ea8a-e53d-11e5-848c-a6a648add066.png)

when button is clicked:

![image](https://cloud.githubusercontent.com/assets/1152336/13589599/e2282110-e53d-11e5-8776-aacdf223388a.png)

However, when you start typing a commit message it gets inputted into the currently selected cell - despite trying to explicitly focussing on the `<input>`. Must be something to do with the global handling of input for the cell grid.

**Comment by nokome** [comment]
Save command will now `write()` to sheet to disk if a local session and `store()` to the `snapshot` endpoint if a remote session. On the hub, when you `boot()` a sheet it will attempt to `restore()` it, thereby downloading, unzipping and reading the latest snapshot tar file. So this does the 4th bullet point except there is no autosave. Would be easy to just put the save on a `setInterval` but need to take care of deactivating save button until more changes are made.

**Comment by nokome** [comment]
@michael and I discussed workflow yesterday. It all needs a lot more thought and iteration and so in the short term, to reduce confusion, I am removing the save and commit buttons. Here's why:

Save: when you hit save, in a local session it will write the component to disk, in a remote session it will create and POST a snapshot tarball; the next time you visit that component on the hub you get that same snapshot restores. That's all fine except that the same URL produces different looking sheets depending upon who's looking at it and what changes they have made - confusing. It is planned to remedy this with unique URLs for each clone. But in the meantime it seems less confusing just to remove the save button (although, save's are still done on page unload).

Commit: commits are working but there are things to sort out like #19. Also the pull/push/merge/sync strategy has not been worked out and there is no UI for listing commits, rollback etc. So, until its more obvious what's going on, probably best to remove it.
