### ISSUE TITLE
Cell with an error causes sheet app to fail to load

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#133]
OK, so now this bug seems to be resolved. But I'm still filing (and immeadiately closing) this issue for the sake or recod keeping and in case this crops up again.

A new example sheet demonstrates this error:

- http://localhost:5000/examples/sheet-with-error/

That sheet has an intentional error in it which propagates into the initial HTML that is loaded:

```html
<td data-kind="1" data-expr="an_intentional_error" data-type="error">object 'an_intentional_error' not found</td>
```
But nothing shows up in the browser and no JS exception is thrown (in Chrome anyway). Remove the error and everything works fine.

**Comment by michael** [comment]
:+1: for example sheets :)
