### ISSUE TITLE
Adding Role to Person

### ISSUE THREAD

**Issue by moranegg** [stencila/stencila#1363]
Hello Stencila community,

I just discovered the Stencila schema by watching the webinar on YouTube and I'm very interested in the software section of the schema.

A first proposition that I can suggest is the addition of the `property`  [Role](https://schema.org/Role)  for persons which exists in schema.org and is still WIP in CodeMeta (see https://github.com/codemeta/codemeta/issues/240).

In the scholarly ecosystem it is important to identify the role of the author/contributor and by using the property we can use the CRediT taxonomy or the software specific taxonomy identified in :
 > Pierre Alliez, Roberto Di Cosmo, Benjamin Guedj, Alain Girault, Mohand-Said Hacid, Arnaud Legrand and Nicolas Rougier Attributing and Referencing (Research) Software: Best Practices and Outlook from Inria: Best practices and outlook from Inria, CiSE 2020 (10.1109/MCSE.2019.2949413) (hal-02135891)
https://hal.archives-ouvertes.fr/hal-02135891

**Comment by nokome** [comment]
Closing this as I think the original intent of this suggestion is mostly provided by the new [`AuthorRole`](https://github.com/stencila/stencila/blob/main/docs/reference/schema/works/author-role.md) type which encompasses not only the role but also aspects such as the format and last time that role was taken.
