### ISSUE TITLE
Auto-purge logs and caches

### ISSUE THREAD

**Issue by alex-ketch** [stencila/stencila#1416]
I noticed that my computer was a bit sluggish due to nearing max HD storage capacity.
After investigating I noticed that a large chunk was taken up by some log messages from Desktop/CLI and the Rust compiler debug targets.

I propose we periodically purge the log files. Don't have enough insight on best practices for the Rust side.
![Screenshot 2022-03-21 at 13 50 48](https://user-images.githubusercontent.com/1646307/159337674-4b1cc379-78f5-4396-a38d-a16f351ba568.png)
![Screenshot 2022-03-21 at 13 48 20](https://user-images.githubusercontent.com/1646307/159337681-91014708-cb19-412d-a4da-b33d81b22676.png)

**Comment by nokome** [comment]
I've experience the same issue with the Rust build artifacts and periodically do `rm -rf target` (or `cargo clean` I think that is just a lighter touch). That just means that the next time you do a build the dependencies need to be downloaded and recompiled again - but it doesn't takes too long. It's like doing `rm -rf node_modules && npm install`.
