### ISSUE TITLE
document for data model

### ISSUE THREAD

**Issue by grayflow** [stencila/stencila#164]
stencila seems promising, man!

and one other really important thing (at least for me) to make it shining is an elegant and consistent document of the sheets' data model, so that i can integrate it to my own workflow(in what ever language i like).

**Comment by nokome** [comment]
Hey @grayflow, thanks for the support! 

Yes, documentation is lacking. I will try to do a full write up of the data model but in the meantime if your main interest is in having sheets for a different language:

- a sheet has an execution context for the host language attached to it, currently that execution context is called a `Spread` and implemented as an abstract base class in [spread.hpp](cpp/stencila/spread.hpp)

- to implement a spread for a particular language you need to create a derived spread class which talks to the host language session. For example, the C++ class [`RSpread`](/r/stencila/spread.hpp) talks to its [R-side counterpart](/r/stencila/spread.R). It's actually not too difficult. The trickiest part is working out how to link the two - for example in R we use the Rcpp's `Environment` object.

Note that I'll be merging sheet's `Spread` with stencil's `Context` soon #148. Note also that we are planning to implement a browser-based Javascript context soon which of course does not need the C++ stuff.

I'm very keen to implement contexts for more languages (e.g. Julia, Haskell) and would be interested to here which languages you would like to see support for.
