### ISSUE TITLE
Full R error messages

### ISSUE THREAD

**Issue by yasirs** [stencila/stencila#165]
For some cells, when there is an error in the R code, I just see "error" in red. It would be useful to see the full error message (may be by clicking on the cell).

**Comment by nokome** [comment]
Hi @yasirs, thanks for pointing this out. Cells have three display modes: `clipped`, `expanded`, and `overlay`. You can change the display mode by clicking on the cell and pressing the space bar (which rotates through those display modes), or by using the dropdown that appears in the top-right of the menu bar. 

It sounds like you had an error in a cell whose display mode has been set to `clipped`. Currently, the default display mode for error cells is expanded but if you explicitly set it to something else then that default is overridden (the `if (display_.length()){` below).

```
std::string Sheet::Cell::display(void) const {
    if (display_.length()){
        return display_;
    } else {
        if (type=="image_file" or type=="html") {
            return "ove";
        } else if(type=="error") {
            return "exp";
        } else {
            return "cli";
        }
    }
}
```

We can change this behaviour (e.g by *always* making errors expanded or clipped) but I think we just need to make the display modes more obvious, like in this old mock up: https://github.com/stencila/stencila/issues/100#issuecomment-172608782.

There is already a related issue for this: #143 so if it's OK with you perhaps you could close this issue and move any further discussion on this over to there.

**Comment by nokome** [comment]
Closing this as covered by #143
