### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [stencila/stencila#166]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in [the destructor for the class "Component"](https://github.com/stencila/stencila/blob/4cb22e17b1776eeed7145c49ffd9cc001495b3fb/cpp/stencila/component.hpp#L38 "Update candidate: Component destructor").

**Comment by nokome** [comment]
Thanks @elfring for pointing (:smile: ) that out. Fixed in 377ffca.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/stencila/stencila/commit/377ffca453874307da6dd28c65f41488fb1557ca "Deletion of an unnecessary checks").
