### ISSUE TITLE
Formula syntax tree, parsers and generators

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#169]
For full import/export from/to other spreadsheet formats (e.g. Excel `.xlsx`, Google Sheets) it is necessary to parse/generate formulas in cells. For example, if importing an Excel spreadsheet into a Stencila R Sheet it would be necessary to translate `AVERAGE(A1:A10)` to `mean(A1:A10)`, and do the reverse if exporting. Some proposals for how to do this in a way that is extendible to multiple source/target languages:
- Implement an [Abstract Syntax Tree (AST)](https://en.wikipedia.org/wiki/Abstract_syntax_tree) in simple C++ classes. Only expression nodes need to be implemented e.g. expression, call, operators. The AST would be internal representation used for translation e.g. `Excel -> ExcelParser -> AST -> RGenerator -> R`.  AST nodes would only contain data and all the translation logic would be in Parser and Generator classes.
- Implement language parsers using [Flex](https://en.wikipedia.org/wiki/Flex_%28lexical_analyser_generator%29) + [Lemon](https://en.wikipedia.org/wiki/Lemon_Parser_Generator) to generate an AST from a language expression.
- Implement language generators that take the AST and generate syntax. These may need to transform the AST to change arguments etc

An initial implementation of this is in the `sheet-syntax` branch cec86ef. It explores some of the approaches to implementation. It's bare bones and needs tidying up but can transform Excel expressions like `AVERAGE(LN(A1:A10),2)` into an R Sheet expression `mean(c(log(A1:A2),2))` (note combining of multiple args into one for R's `mean`). See the [RGenerator](https://github.com/stencila/stencila/blob/sheet-syntax/cpp/stencila/syntax/r.hpp).

There is also a [README.md](https://github.com/stencila/stencila/blob/sheet-syntax/cpp/stencila/syntax/README.md) with some notes on previous approaches to this.

**Comment by jennybc** [comment]
I'm going to also tag @richfitz here because he is actively thinking about this as well.

**Comment by nokome** [comment]
This work has been merged into the `develop` branch: see the `cpp/stencila/syntax-*` files. 

A different approach has been taken to translating function calls - don't! Previously translation was done in C++ generator (see above). The `ExcelToRGenerator` still does that but the `ExcelToRSheetGenerator` does not modify function calls and instead relies on compatibility functions with the same names e.g. `AVERAGE` implemented in R (see #172). This has the advantages that:
- users can write the functions that they are familiar with writing within a spreadsheet environment
- R developers can write and test translations (ie. compatibility functions) in R instead of in C++

The `ExcelToRGenerator` will still be useful (when fully implemented) for users who want to convert to pure R code (i.e. not dependent upon the compatibility functions implemented in the `stencila` package).

Next, implementation for Python sheets.

**Comment by richfitz** [comment]
Given

> A different approach has been taken to translating function calls - don't!

are you still planning on writing a formula parser?  Our interests are in pulling things from existing Excel spreadsheets and so we're looking for a way to pull apart formulae (with perhaps movements to doing some translation to R).  I'd rather not duplicate effort here if you're going to implement something we can use, but if you are no longer planning on developing that way, I can start trying to wrap up an existing Excel formula parser.

**Comment by nokome** [comment]
Yep, the parser is still implemented in the C++ class ExcelParser and generates an AST. I was chatting to @jennybc today on Gitter about exposing the AST in R. Will create an issue for that.

**Comment by richfitz** [comment]
Great, thanks.  I'm happy to test it out, and can organise running whatever you come up with over the [Enron excel corpus](http://www.felienne.com/archives/3634) which we're using to test our Excel reader (there are about ~900k formulae there)

**Comment by nokome** [comment]
Thanks @richfitz, I was looking at that corpus today! Exposing the AST in R won't be too big a deal but the Excel parser still needs some work - only basics there at present.

**Comment by nokome** [comment]
In the process of cleaning up old issues. Conversion of Excel files, including parsing of formulas, will now be handled in the stencila/convert repo.
