### ISSUE TITLE
Implement spreadsheet compatibility functions for R

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#172]
The file [spreadsheet.R](https://github.com/stencila/stencila/blob/develop/r/stencila/spreadsheet.R) implements spreadsheet compatibility functions like `ABS`, `ACCRINT`,...`ZTEST`. Currently, there are 470+ functions in that file, most of which are stubs which throw an error when called (and refer to this issue). See #169 for the rationale for implementing these.

It is probably best for the same person to implement related functions. Families of functions are marked using the roxygen2 tag `@family`e.g. "Spreadsheet date and time", "Spreadsheet statistical".

Implementers should provide documentation in the form of `@param` tags etc. See the Microsoft Excel [documentation for functions](https://support.office.com/en-us/article/Excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188) which is useful in this regard.

Priorities: [Jansen (2015)](ceur-ws.org/Vol-1355/paper15.pdf) provides a list of the top 15 functions used in the Enron and EUSES spreadsheet corpora, these combined with a quick web search suggests:

**Statistical**
- [ ] COUNT
- [ ] COUNTIF
- [ ] COUNTA
- [ ] SUM
- [ ] SUMIF
- [ ] AVERAGE
- [ ] AVERAGEIF
- [ ] MIN
- [ ] MAX
- [ ] CHOOSE

**Logical**
- [ ] IF
- [ ] AND
- [ ] OR

**Information**
- [ ] ISNUMBER
- [ ] ISBLANK

**Math and trigonometry**
- [ ] ROUND
- [ ] SUBTOTAL

**Text**
- [ ] CONCATENATE
- [ ] LEN
- [ ] TRIM
- [ ] RIGHT
- [ ] LEFT
- [ ] MID

**Date**
- [ ] DATE
- [ ] DAYS
- [ ] NOW
- [ ] MONTH

**Lookup and reference**
- [ ] OFFSET
- [ ] INDIRECT
- [ ] INDEX
- [ ] MATCH
- [ ] LOOKUP
- [ ] VLOOKUP

**Comment by nokome** [comment]
Commit 0f70895 adds a test [XLSX spreadsheet](https://github.com/stencila/stencila/blob/develop/r/tests/spreadsheet.xlsx) and a [test runner](https://github.com/stencila/stencila/blob/develop/r/tests/testthat-spreadsheet.R) which reads it in (as a Stencila sheet of course!) and then runs any defined tests using the R compatibility functions and checks their value against the value calculated by the spreadsheet software and stored in that xlsx.

So any implementations should have at least one, ideally more, tests defined in that xslx.

**Comment by nokome** [comment]
In case there is some doubt about how to go about implementing these functions here's a step by step summary of how I implemented `AVERAGEIF` in commit ed91e4f:

- go to the Microsoft's [Excel function list](https://support.office.com/en-us/article/Excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188) and click on the link to the function you are implementing
- in `r/stencila/spreadsheet.R` find the function stub and write R code to implement what's described in the docs
- add additional documentation as appropriate to the function, `@param`, `@examples` etc
- do some adhoc tests in your favourite R console/IDE e.g `AVERAGEIF(1:10, "<5")`, `AVERAGEIF(1:10, "<5", 10:1)`
- add some tests for the function to the columns B-E on the row corresponding to the function in `r/tests/spreadsheet.xlsx`

**Comment by nokome** [comment]
Came across @tamc's [tamc/excel_to_code](https://github.com/tamc/excel_to_code) a Ruby library for parsing Excel formulas and converting them into C and Ruby. This includes implementations of Excel functions in Ruby (https://github.com/tamc/excel_to_code/tree/master/src/excel/excel_functions)

**Comment by tamc** [comment]
There is also a set of implementations in C as well. 

Thanks for drawing my attention to your project. It is addressing some challenges that interest me. I'm going to explore your work properly.

**Comment by nokome** [comment]
Closing in favour of new issue https://github.com/stencila/stencila/issues/310
