### ISSUE TITLE
Grid is missing

### ISSUE THREAD

**Issue by michael** [stencila/stencila#174]
Looks like the grid lines got lost somewhere. Probably just a css issue:

![image](https://cloud.githubusercontent.com/assets/2931/14743719/490d0e26-08a3-11e6-896f-f3bda50e168a.png)

**Comment by nokome** [comment]
Thanks for the bug report @michael . I can't replicate it on Chrome or Firefox on Ubuntu 14.04. Could you do a browser cache refresh and confirm that it's still happening for you?

**Comment by michael** [comment]
It's working now.
