### ISSUE TITLE
Meta: Functionality of Ankhor, DADiSP, Quantrix, etc

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#177]
It is possible to add / borrow some of the functionality found in other spreadsheet software like:
- http://www.ankhor.com/
- https://www.dadisp.com/
- http://matrex.sourceforge.net/
- https://github.com/hoplon/javelin (it would be great to have a progammable spreadsheets like in this project)
- http://orgmode.org/
- https://github.com/Spreads/Spreads (it would be great to have a progammability like in this project)
- http://www.curl.com/, https://en.wikipedia.org/wiki/Curl_(programming_language), https://en.wikibooks.org/wiki/Curl
- http://www.wolfram.com/cdf/
- http://unisonweb.org/
- http://eve-lang.com/, http://witheve.com/
- ZigZag or  zzstructure - http://xanadu.com/zigzag/, http://xanadu.com/zigzag/tutorial/ZZwelcome.html, http://gzigzag.sourceforge.net/, http://www.nongnu.org/gzz/, http://fenfire.org/

**Comment by nokome** [comment]
Yes, absolutely, we should seek inspiration and ideas from projects like these. If you have some specific features in mind please feel free to add them as a separate standalone feature request.

Having said that, my personal view is that we need to be careful not to shoehorn too much into the spreadsheet interface. It may be better to keep sheets as sheets (with the familiar two dimensional grid) and design separate components for approaches like data flow programming (with a more flexible layout canvas and connectors).

**Comment by sirinath** [comment]
I would partly agree and disagree. DF can be separate but best if you can dataflows as a means to populate sheets / workbooks. Also it would be best is WBs are multi dimensional (row, column, sheet).

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
