### ISSUE TITLE
Dataflow Computing Coupled with Spreadsheets

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#179]
DF can be separate but best if you can dataflows as a means to populate sheets / workbooks. You should be able to easily specify which sheets, rows, columns and cells get populated from streaming data. Also it would be best is WBs are multi dimensional (row, column, sheet). The Spreadsheets interface is the easiest mode of programming available.

See: http://www.ankhor.com/

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
