### ISSUE TITLE
[DRAFT] feat(css): How do we apply css?

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#1794]
Stencila will need to apply CSS to a variety of contexts:

- Document chrome
- Web Component chrome (when viewing the document in non-preview mode)
- Print
- Render differently depending on the theme chosen
- Light & Dark mode?
- Responsiveness?

There's quite a lot to organise here!

### HTML elements will live not in isolation

The HTML elements will live not in isolation, but alongside and in many instances inside of each other. The CSS will need to allow for this level of composability.

e.g.

```html
<article>
  <p>Content... etc.</p>
</article>
<footer>
  I am the article's footer
</footer>
```

vs. 

```html
<article>
  <p>Content... etc.</p>
  <footer>
    I am the article's footer
  </footer>
</article>
```

e.g. `article + footer` & `article > footer` 🤷 

### Purely semantic CSS (where possible)

We'd like the components to be rendered in classless, semantic markup.

In principle, this means that the majority of our CSS is written to apply to html tag selectors (in combination with html attributes). The combination of semantic markup + aria tags (specifically `role`) will give use enough variation without having to apply any `class` attributes to the elements.

> [!IMPORTANT]
> There may be caveats here to cater for CSS specific layouts that can't be captured with purely semantic markup - e.g. `grid` layouts or possibly colour theme variations (i.e. `primary` vs `secondary` vs `outline` etc.

The inspiration for this is [picocss.com](https://picocss.com)

### Tailwind?

Tailwind is great (obviously!) and we should be open to using it. However, it runs counter to the above 👆 stated goal of "Purely semantic CSS". If that is the case, we can use Tailwind in a couple of contexts:

- Layout only (e.g. grids or colour emphasis variations)
- `@apply`ing the tailwind classes into our CSS

#### What are we giving up?

There are plenty of things that come for free (outside of the utility nature of adding classes arbitrarily to elements). These will need to be replaced with our own version:

- Variants (:hover, :active etc)
- Responsive variants (:sm, :md, :lg ...)
- Theme propagation - e.g. the application of colours overrides to any related classes (border, color, bg etc)

### Think global, act global

By using an approach similar to `pico.css`, we will need to place the CSS at a global level. The CSS used to render the _"preview"_ mode of a component will be handled by the global styles.

There are reasons for a Web Component to add its own styles:

- The chrome displayed around a component (e.g. a code editor) can be managed within the component
- There may be some other caveats

In general there will be limited CSS added to the majority of Web Components.

## Technology choices

This is TBD. There are a number of choices:

- use pico.css directly
- build our own sass library
- hand roll css
- build our own postcss library

This requires a spike to understand the options - particularly the use of pico directly. 

## Themes

> [!NOTE]
> THIS IS A WORK IN PROGRESS
> Documents can be rendered with different themes. In the future there is the possibility that themes could be developed by users themselves. In order to allow for this, we will need to provide some level of customisation, while still maintaining the underlying CSS. 
> We will need to define what can and should be modified...

**Comment by simonwinter** [comment]
@nokome - I've added some updates so that the main app now has a chrome featuring:

- header 👍 
- main 😎 
- footer ⛅ 

I've also added the favicon as well.

There are a few things that I've run into that need some attention:

1. Getting the view to render in the app
2. Importing the `main.css` inside the `main.ts` file was not working at all, so I've had to hack on the rust & add the file there. Less than ideal.
3. The favicon also gets added to the rust - not sure if that's cool?
4. Twind has some challenges that I can't solve.
5. I had to disable the print view as it was causing the app to render as a blank screen.

Number 4 ☝️ is pretty annoying. I was hoping that I could simply adjust the `tailwind.config.js` to override styles, but that doesn't appear to have any effect. I was attempting to set `font-sans` to use `Lato`, however there is no effect on Twind. It generates the tailwind css (I think) on the fly, with minimal override options.

I've ended up using an inline custom style `font-['Lato']` which works fine, it's just not that awesome or scalable.

---

My plan next week is to:

- Understand how to render the view inside the chrome (I think maybe we need to have different chrome for when we print)
- Tidy up the css
- Get a theme switcher in there
- Most importantly work with @kusalekanayake on understanding what the UI & UX needs actually are & between us get as much as possible up & running in this sprint
-

**Comment by nokome** [comment]
> I was hoping that I could simply adjust the `tailwind.config.js` to override styles, but that doesn't appear to have any effect. I was attempting to set font-sans to use Lato, however there is no effect on Twind.

I'm pretty sure that Twind offers the same config options as Tailwind but you have to do that in `src/twind.ts`. I had to add the  `tailwind.config.js` file for the themes which use `tailwindcss` proper via Parcel. Understandably very confusing. I've added some comments to the files to clarify this and fixed this up so that `font-sans` is Lato:

https://github.com/stencila/stencila/commit/3ac0a15f3a46ffa6505b0a875878e26aacb80f6b

**Comment by nokome** [comment]
For the other bullet points that need attention I think the best approach is to merge your branch into main and work on top of some other things I have in progress. I'm going to close this issue because it's feeling a bit more like a PR discussion and I'll try to put remaining points into new issues.

**Comment by simonwinter** [comment]
Thanks @nokome! Will setup issues for the others above ☝️
