### ISSUE TITLE
Compilability of documents

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#180]
Is there possibility to add compilability of documents into stand alone applications / components in which throughput and latency is paramount. Compiled sheets need not be editable. Also this will be more useful if you have: https://github.com/stencila/stencila/issues/179 which can be used as a means to pupulate and extract data from the documents. There should be ability to specify or change data sources (https://github.com/stencila/stencila/issues/181).

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
