### ISSUE TITLE
Use of Stencila as a Homoiconic Programming framework like Curl

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#182]
This might need some change of direction but if Stencila can be used as a Homoiconic programing language like [Curl](https://en.wikipedia.org/wiki/Curl_%28programming_language%29). If the document definition language can manipulate it self then this makes it easy to extend this language with more functionality.

**Comment by talwrii** [comment]
I think it's important that understanding "what gets recalculated when" be easy. I fear the macros / code-generation could be problematic here.

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
