### ISSUE TITLE
Doc: Advantages of Stencila over Orgmode, Curl, etc.

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#183]
Orgmode share many similarities and also can have multi language support. So what is the advantage of Stencila over Orgmode? Also how does it stack against frameworks like Curl which also has nice UI capabilities?

If someone is to switch from MS Office, Ankhor CE, Quantrix what would you gain?

Also how does it compare with UI based programming frameworks like: http://unisonweb.org/, http://eve-lang.com/?

Best is to have comparison of these in the documents.

**Comment by talwrii** [comment]
# Comparison to org mode

One imagines the main advantage over org-mode is partial re-evaluation of only those things that have changed.

Also I think low barrier to entry is an aim.

# Analytica

Analytica is another piece of software that exists in the same space.
