### ISSUE TITLE
Catch system_fingerprint from OpenAI requests

### ISSUE THREAD

**Issue by hlm628** [stencila/stencila#1832]
As described in [these notes on reproducibility](https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter) from OpenAI, seeds do not guarantee reproducibility.

`system_fingerprint` - which identifies the actual config on the OpenAI side used to generate a given response - may provide clues when this fails. We should catch this and store with our responses.

Looking at the docs from the [`async-openai` Rust crate](https://docs.rs/async-openai/latest/async_openai/types/struct.CreateCompletionResponse.html#structfield.system_fingerprint), this is a field in `CreateCompletionResponse`. We should adapt our `agent-openai` crate to grab this.

**Comment by nokome** [comment]
Hah, I was anticipating this request :)!

We'll need to change the signature of the `Agent::text_to_text` method from:

```rust
async fn text_to_text(&self, instruction: &str, options: &GenerateOptions) -> Result<String>
```

to something like

```rust
async fn text_to_text(&self, instruction: &str, options: &GenerateOptions) -> Result<(String, GenerateDetails)>
```

so that we can bubble up those details through the call stack and store them in the db.
