### ISSUE TITLE
Spreadsheets as an Editor and Rendering of Data Structures

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#184]
I feel Spreadsheets baked in is not the way to go but support Pandas like dataframe or indexed arrays as a form of spreadsheet. This way you can change the row and column indices as well. 

Also you can have the notion of editors and rederes (somethin like: http://mbeddr.com/2014/11/14/graphical.html, http://orgmode.org/manual/Built_002din-table-editor.html#Built_002din-table-editor, http://orgmode.org/worg/org-tutorials/tables.html) for tables and sheets datastuctures. This way a sheet can be embedded within a normal document also.

Also there should be check to see if references are valid when new data structures are created and sliced.

Also see: https://en.wikipedia.org/wiki/Structure_editor, http://martinfowler.com/bliki/ProjectionalEditing.html, https://github.com/JetBrains/jetpad-projectional, https://github.com/JetBrains/jetpad-mapper/wiki/JetPad-Mappers#applications

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
