### ISSUE TITLE
feat(agents): OpenAI API restricted to 3 queries/min

### ISSUE THREAD

**Issue by hlm628** [stencila/stencila#1863]
Can we get a paid OpenAI token? The restriction to 3 queries/min makes testing a bit of a pain.

Would also be nice to experiment with GPT-4 models.

**Comment by nokome** [comment]
Yeah definitely this was on my to do list. Will try to get it done within the next hour.

**Comment by nokome** [comment]
Done

![image](https://github.com/stencila/stencila/assets/1152336/9463b155-8193-4657-acd4-75db78d6c3cb)


![image](https://github.com/stencila/stencila/assets/1152336/719cfeb2-62f8-4861-9049-a247024cf3df)
