### ISSUE TITLE
feat(api keys): store in local file

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1909]
Currently, to use the AI assistants you need to set API keys as env vars (e.g. `OPENAI_API_KEY`, `ANTHROPIC_API_KEY`). The ability to specify API keys using env vars should be retained. However, it is awkward to have to do this all the time. 

Instead, it would be better to be able to give Stencila API keys and have them stored in a local config file or similar. A user should be able to edit that config file directly to add or remove keys. Eventually a user should also be able to add or remove keys via a visual interface.

This seems like a common problem. How do other tools approach this?

**Comment by brettc** [comment]
Maybe this: https://docs.rs/keyring/latest/keyring/

**Comment by kusalekanayake** [comment]
<img width="575" alt="image" src="https://github.com/stencila/stencila/assets/16539995/06394e91-7674-49e9-9e9e-c59ed6d7c471">
WIP config design.

**Comment by simonwinter** [comment]
Front end look at: https://jsfe.js.org/Sink/AllFeatures

**Comment by nokome** [comment]
We currently have integrations with the following LLM providers so need inputs for these:
 
- Anthropic
- Google
- Mistral
- Ollama
- OpenAI

**Comment by kusalekanayake** [comment]
<img width="906" alt="image" src="https://github.com/stencila/stencila/assets/16539995/b7d75906-7b77-411c-a295-d0be8856f190">

Updated with the above mentioned logos.

**Comment by nokome** [comment]
See https://github.com/stencila/stencila/pull/2061#issuecomment-1955599879 for detail on the API

**Comment by nokome** [comment]
Closing as original issue (storing in local secrets store) is done.
