### ISSUE TITLE
Split the stencila repository into separate repositories?

### ISSUE THREAD

**Issue by ackerleytng** [stencila/stencila#191]
I think stencila should probably be split into a few parts - one for cpp, one for R and one for python. Each should stick to their own 'usual' way of installation, so in the python repo you should be able to do `python setup.py` to install.

The Makefile feels unwieldy too, but I'm not sure how large projects manage their makefiles.

**Comment by nokome** [comment]
Yes there are pros and cons of both mono-repo and multi-repo (for a case for mono see [this](http://danluu.com/monorepo/)). With Stencila, the various modules (e.g. C++, R, Python, web) etc are very tightly coupled so my feeling is that splitting up would cause additional problems. So, for now I think we should stick with mono.

Nonetheless, we can do a lot to decouple the modules more and give them more of a "native" feel for developers in a particular language. Certainly the `Makefile` is very big now and should probably get broken up.

I'm working on a Node.js module now and testing out some of these approaches there. But at the same time we could work on decoupling the Python module.

Just my $0.02 worth for now.

**Comment by nokome** [comment]
@ackerleytng : I decoupled the Python module #193 Would appreciate it if you could try it out and let me know if you think its an improvements. Needs a `make cpp-library build/current` first  to build the required `libstencila.a`. Will look to improve that soon. Thanks!

**Comment by ackerleytng** [comment]
Hey! I was sort of looking up best practices for this and i saw [this](http://stackoverflow.com/questions/14126234/c-makefile-compilation-dependent-library)

Not sure if you'd be willing to make such major changes to the makefile though.

**Comment by ackerleytng** [comment]
Here's the experience of someone external to the project!

When I did a git pull, I had no idea what I should do to clean up the build that I already had. (Forgot if I had done `make install` last time, or whether there even is such a make target.

So I did a `make clean` and then when I did `make cpp-library build/current`, I got this:

```
$ make cpp-library build/current
/bin/sh: 1: Rscript: not found
make: R: Command not found
make: R: Command not found
/bin/sh: 1: Rscript: not found
/bin/sh: 1: Rscript: not found
lemon cpp/stencila/syntax-excel.y
mv cpp/stencila/syntax-excel.h build/linux/x86_64/cpp/library/generated/
mv cpp/stencila/syntax-excel.c build/linux/x86_64/cpp/library/generated/syntax-excel-parser.cpp
rm cpp/stencila/syntax-excel.out
g++ --std=c++11 -O2 -Wall -Wno-unknown-pragmas -Wno-missing-braces -Wno-unused-local-typedefs -Wno-unknown-warning-option -fPIC -Wno-unused-variable -Icpp  -Ibuild/linux/x86_64/cpp/requires/boost/include -Ibuild/linux/x86_64/cpp/requires/cmark/src -Ibuild/linux/x86_64/cpp/requires/cmark/build/src -Ibuild/linux/x86_64/cpp/requires/libgit2/include -Ibuild/linux/x86_64/cpp/requires/libzip/lib -Ibuild/linux/x86_64/cpp/requires/cpp-netlib/ -Ibuild/linux/x86_64/cpp/requires/pugixml/src -Ibuild/linux/x86_64/cpp/requires/jsoncpp/dist -Ibuild/linux/x86_64/cpp/requires/tidy-html5/include -Ibuild/linux/x86_64/cpp/requires/websocketpp -Ibuild/linux/x86_64/cpp/library/generated -obuild/linux/x86_64/cpp/library/objects/stencila-syntax-excel-parser.o -c build/linux/x86_64/cpp/library/generated/syntax-excel-parser.cpp
In file included from cpp/stencila/syntax-excel.y:5:0:
cpp/stencila/syntax-tree.hpp:6:38: fatal error: boost/algorithm/string.hpp: No such file or directory
compilation terminated.
Makefile:477: recipe for target 'build/linux/x86_64/cpp/library/objects/stencila-syntax-excel-parser.o' failed
make: *** [build/linux/x86_64/cpp/library/objects/stencila-syntax-excel-parser.o] Error 1
rm build/linux/x86_64/cpp/library/generated/syntax-excel-parser.cpp
```

(I'm hoping that I don't have to build the R part if I'm only interested in the python side of things)

So then I did

```
make cpp-requires
```

(And this is taking a while since it has to download and build all the dependencies.)

Will post again when the dependencies are done! :)

**Comment by nokome** [comment]
Thanks for trying this out - it helps a lot!

I'm in the process of pulling apart the root Makefile. But need to do that step by step so as not to break everything. So the errors you see should go away. All this is a major part of the [0.23 milestone](https://github.com/stencila/stencila/milestones/0.23) due for 10 June.

I'm also up for suggestions for alternative approach - I looked at the SO article you linked to. The use of `configure` suggests dynamically linking to external binary libraries. The current approach is to link statically instead - while that _may_ be a bit more hassle for developers, it should be a lot safer for end users because you can guarantee the right versions of everything a "just there", right in the binary package. But when I refactor the C++ build I will think about this more.

When `make cpp-requires` finishes you will need to do `make cpp-library build/current` again - which should not error this time. You don't _need_ R to build the Python package - the root Makefile is checking to see if it is installed and what version it is - again this will be removed soon.

**Comment by nokome** [comment]
@ackerleytng : I'm going to close this issue. As part of the 0.23 release, based on your suggestion, I've decoupled each language module and tried to "stick to their own 'usual' way of installation" e.g. `npm install`, `python setup.py install`. Things are not complete in that regard, but I'd like to close off release 0.23 and come back to some of these build issues for 0.25. Feel free to open another issue specific to a particular issue. Or reopen this one if you think more splitting up is needed - i.e. into completely separate repos - but I'd like to try out this more decoupled setup before going to that extent. Thanks for your input.
