### ISSUE TITLE
exec show, followed by a line with no spaces results in a completely blank page

### ISSUE THREAD

**Issue by ackerleytng** [stencila/stencila#192]
In stencil.cila, If i have something like

```
exec show
test
```

with no spaces before `test`, and I do 

```
stencila-py . view
```

the webpage turns up completely blank.

**Comment by nokome** [comment]
I can confirm that. The cila get's parsed to `'<pre data-exec="exec show"></pre>\ntest'`. The front end JS doesn't like the orphan text node `test` and raises an exception. Fixes:

- `CilaParser` should create a `<p>test</p>`
- `Stencil::page` should ensure there are no text child nodes of the root document
- frontend JS should more gracefully handle orphan text - but that probably a matter for substance

**Comment by nokome** [comment]
Hey @ackerleytng thanks for submitting this issue! I'm closing it now as 8c2a3a5 and 0f6b135053af7fa2836cb33627bc363acffe5a5d should deal with it (and there's now some related unit tests) :)
