### ISSUE TITLE
feat(source view): bottom panel

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1958]
### Summary

The `SourceView` needs some design! At present there are three things that we've just thrown in there in random places:

- dropdown for the format
- toggle for line wrapping
- breadcrumbs for current node

![image](https://github.com/stencila/stencila/assets/1152336/d45e1a00-a87a-40ce-ad93-a9852a3ad56c)

To keep things as visually uncluttered as possible, I suggest that as much as possible we put things into the bottom panel ala VSCode.

@kusalekanayake Could you do a design for that bottom panel please:

- Most of it will be straightforward I think and follow the lead of other editors.
- For the breadcrumbs I wonder about using the same icons for each type that we use elsewhere?
- It should be responsive e.g. hide breadcrumb labels on small screens

**Comment by kusalekanayake** [comment]
@mike-parkin Have added some preliminary designs which should be enough to style the toolbar with the above mentioned features. I'll have a look to see if adding the icons instead for the breadcrumbs works and does not make it too visually confusing. Will also look to see what else we can add to this in the future. 

![ToolbarIsolated](https://github.com/stencila/stencila/assets/16539995/96104e6a-06b1-4905-9e40-9f49805f73f5)
![Toolbar](https://github.com/stencila/stencila/assets/16539995/7afcd6b1-31a3-4a1b-9d3a-4882cde161c8)
![wrap-text](https://github.com/stencila/stencila/assets/16539995/23989dd9-d34e-4639-93cb-f7f7cb7ef47c)

**Comment by simonwinter** [comment]
> @mike-parkin Have added some preliminary designs which should be enough to style the toolbar with the above mentioned features. I'll have a look to see if adding the icons instead for the breadcrumbs works and does not make it too visually confusing. Will also look to see what else we can add to this in the future. This figma link should hopefully work: https://www.figma.com/file/v86ud2R9zKX8ARl3jzPg7K/Stencila-Design-System?type=design&node-id=508-6684&mode=dev
> 
> Panel isolated: ![Toolbar](https://private-user-images.githubusercontent.com/16539995/300305508-4e87a7ff-27d2-442d-bfab-05d23abfa8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODg3NDYsIm5iZiI6MTcwNjQ4ODQ0NiwicGF0aCI6Ii8xNjUzOTk5NS8zMDAzMDU1MDgtNGU4N2E3ZmYtMjdkMi00NDJkLWJmYWItMDVkMjNhYmZhOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwMzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NGM0MjhjYzJlMjRhN2Y1NDRjOGQxYzY0Nzg1MmZkYTEzZWYxMzM0NDlkMGMzNTkzMjg1M2M5NjIxOTk2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKCrkKifTuqDaoyNqtHhGQU2bzzpMROlvaYwtwIaqcA)
> 
> Panel in context: ![ToolbarIsolated](https://private-user-images.githubusercontent.com/16539995/300305512-7b6fff26-a3fb-4597-8114-5b49078ebdb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODg3NDYsIm5iZiI6MTcwNjQ4ODQ0NiwicGF0aCI6Ii8xNjUzOTk5NS8zMDAzMDU1MTItN2I2ZmZmMjYtYTNmYi00NTk3LTgxMTQtNWI0OTA3OGViZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwMzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZGFkODA5ZDNhNDMyNjlhYTc1MDI5ZjI5MWYyNTc5M2Q2NWZkZjcxMWEwMmQ3ZGYwNDczMTk2ZTAwOTY3NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVYG_hfFizGe63hxN_wXTrpDqiKJwOjNuIw3iAC6sbg)
> 
> Wrap text Icon: ![wrap-text](https://private-user-images.githubusercontent.com/16539995/300294377-300a2221-f5c8-4945-a03e-177c5b0a338c.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODg3NDYsIm5iZiI6MTcwNjQ4ODQ0NiwicGF0aCI6Ii8xNjUzOTk5NS8zMDAyOTQzNzctMzAwYTIyMjEtZjVjOC00OTQ1LWEwM2UtMTc3YzViMGEzMzhjLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwMzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyY2UwMzUwN2NjOWVjMGRjMGFhNGM4YzkyODlhMWUzODUxNTU4YzM4ZGVlYTE4YWVhMTA1YjNkMzIwYTJhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3H1N5wWDWG6nbZeVTI618q51unTsr9Ny138NssvMWDY)

Looking nice @kusalekanayake - there's some chrome on the way soon to wrap around the edges!

**Comment by kusalekanayake** [comment]
@simonwinter thought's on this hover/active state for the side panel? A similar interaction for the document specific info in the top right.
![HoverAndActiveState](https://github.com/stencila/stencila/assets/16539995/9b65d643-b864-49c3-8494-5306d355e584)
