### ISSUE TITLE
feat(markdown): merge instructions and replacements

### ISSUE THREAD

**Issue by brettc** [stencila/stencila#1960]
### Summary

Instructions that replace text (both inline and block) currently duplicate the original text in Markdown. So we get something like this:
```
%% @do-something-that-replaces-the-block
%>

Here is the text

%%

~~

Here is the text

~>

Here is the replaced text.

~~
```

We should coalesce these intelligently in the markdown codec.

### Reference Issues

See discussion here:
#1916 

### Implementation PR
Which was partially addressed here:
#1959

**Comment by nokome** [comment]
Closing as superseded.
