### ISSUE TITLE
feat(source view): Left gutter style and nesting for blocks

### ISSUE THREAD

**Issue by kusalekanayake** [stencila/stencila#1976]
### Summary
As a coder **I want to know what lines/chunks of the document are associated with what web component**, so I can **know the context of each section that I am working on and work on it accordingly.**

This means the left gutter, in a similar fashion to other ides should show couple sections of code together. e.g. If statements, paragraphs, instruction blocks. 

There is the catch that some of them may be nested within others as well as we need to have an understanding of state, e.g. The instruction block needs to run because we don't know if it has processed the instruction.

## Design

I have been looking at two main ways that this could exist, one is reasonably subtle using just colours while the other uses icons and nesting with more intent. Neither show state yet.

![Image](https://github.com/stencila/stencila/assets/16539995/e9108812-21f2-40a4-b756-0059a8e6a2c4)

![Image](https://github.com/stencila/stencila/assets/16539995/b6551a00-ae44-444d-b999-9cec8b5da0e3)

**Comment by nokome** [comment]
Thanks @kusalekanayake. I personally prefer the second option with icons and nesting. I think it would link well to the visual editor. Yes, it is quite busy but I suggest we give a toggle in the bottom toolbar for users that would prefer to hide it.

**Comment by kusalekanayake** [comment]
Great, will push that design further to handle more nesting and potentially state. Adding a toggle in the bottom panel sounds appropriate too.

**Comment by nokome** [comment]
> handle more nesting

You might want to consider a maximum nesting level of 2 or 3.

**Comment by brettc** [comment]
Like @nokome, I like the second pic. These provide great visual feedback on what you are doing. They also look like they invite some interaction too. Folding and dragging are some obvious generic actions, but I imagine clicking on a particular icon could bring up some context-specific actions that could be applied to the block, like using an appropriate assistant (generate image / correct grammar etc).

**Comment by kusalekanayake** [comment]
@mike-parkin has already partially implement this design but this is the current approach. Smaller bars means more potential for compact nesting.

![Left gutter stacked](https://github.com/stencila/stencila/assets/16539995/d034774e-95d9-490b-a43d-17cb9b308dfb)

**Comment by kusalekanayake** [comment]
I'll have to map the components to colours and icons. I have a list of icons I've been chipping away at so will be able to attach colours to that at some point.

![Icons](https://github.com/stencila/stencila/assets/16539995/17c5e3e4-2433-4e0a-a345-9bf281653e97)

**Comment by kusalekanayake** [comment]
Woooo nice one @mike-parkin!

**Comment by nokome** [comment]
Closed by #1997
