### ISSUE TITLE
feat(web components): add component for displaying the authors of a node

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1980]
### Summary

As a user I would like to be able to inspect the `authors` property of node types that have that property:

![image](https://github.com/stencila/stencila/assets/1152336/d0ccd912-3046-4718-aa8c-7d519fdf58ad)

### Thoughts on implementation

I quickly coined the name "infoblock" and created `web/src/nodes/helpers/block-infobox.ts` for it and used it like this:

```html
      <stencila-block-infobox icon="paragraph" title="Paragraph">
          <slot name="authors" slot="authors"></slot>
      </stencila-block-infobox>
```

This was basically just a quick spike to test the assumption that slots could be "forwarded" like that (they can!). But as I've been stubbing out the web component classes for each node type I've been thinking this is probably not the right way to think about it and certainly the wrong name (because some components will be a lot more than info boxes i.e. have editable properties).

Instead I wonder if we should establish a more composition oriented pattern of using helper components for specific, shared properties of node types. In this case, `authors`. Something like this:

```html
<div>
  <stencila-node-type icon="paragraph" title="Paragraph">
  </stencila-node-type>
  <stencila-node-authors>
     <slot name="authors" slot="authors"></slot>
  </stencila-node-header>
</div>
```

I think this pattern would extend better when we come to other properties that are common across node type. For example, there are a lot of shared properties of all the node types that extend `Executable`.

### Types of authors

Note that in the schema there are several types of nodes that can be in the `authors` property: `Person`, `Organization`, `SoftwareApplication` and `AuthorRole` e.g. in examples/nodes/list/list.dom.html:

```html
              <div slot=authors>
                <stencila-person id=per_111111134 given-names='["Alice"]'>
                </stencila-person>
                <stencila-person id=per_111111135 given-names='["Zoe"]'>
                </stencila-person>
                <stencila-author-role id=aut_111111137 role-name=Generator>
                  <stencila-software-application id=sap_111111136 name=GPT>
                  </stencila-software-application>
                </stencila-author-role>
              </div>
```

We'll try to populate `authors` only with `AuthorRole`s but this component should allow for a mix of all of them.

**Comment by kusalekanayake** [comment]
Have added time stamps and alternative view to get feedback on that may be more space efficient. Could be good if there is less horizontal space.
![infoBlockWithDate](https://github.com/stencila/stencila/assets/16539995/3988a462-85db-4008-80e6-d8772c63cf0e)
![InfoBlockWithTopTitle](https://github.com/stencila/stencila/assets/16539995/fadd5268-eaeb-4c10-90e9-796d18344529)

**Comment by nokome** [comment]
Thanks @kusalekanayake I personally prefer that new option. Do you think we should use "time ago" style times?

**Comment by kusalekanayake** [comment]
That could be a good approach. Are the time/dates associated with each entry, the last time they used that role?

**Comment by kusalekanayake** [comment]
![InfoWithRelativeTime](https://github.com/stencila/stencila/assets/16539995/7f935e08-fe63-40e3-b657-2179707e9b97)

**Comment by nokome** [comment]
> Are the time/dates associated with each entry, the last time they used that role?

Yes (well that was the plan, timestamping these is not yet implemented)

**Comment by nokome** [comment]
The current state of implementation is this:

![image](https://github.com/stencila/stencila/assets/1152336/38d8645c-d16c-4510-821e-6f23dffd996f)

For reference the "DOM HTML" sent to the browser for this example is:

```html
<div slot="authors">
  <stencila-person id="per_zJP6SvP1AvpSfDbb25j9Vxat2SNA" given-names="[&quot;Alice&quot;]">
  </stencila-person>
  <stencila-person id="per_zJP6SvP1AvpSfDbb25j9Vxat2SkE" given-names="[&quot;Zoe&quot;]">
  </stencila-person>
  <stencila-author-role id="aut_zJP6SvP1AvpSfDbb25j9Vxat2T8J" role-name="Generator">
    <stencila-software-application id="sap_zJP6SvP1AvpSfDbb25j9Vxat2TH8" name="GPT">
    </stencila-software-application>
  </stencila-author-role>
</div>
```

We do not yet have timestamps on `AuthorRole`. It would be useful to implement that, and have more examples, before finishing these designs.

**Comment by nokome** [comment]
Done.
