### ISSUE TITLE
chore(web): add an `iconForNodeType` function

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1985]
### Summary

As a Stencila Typescript developer I would like a function to get the name of the icon associated with each node type in the Stencila Schema e.g.

```ts
import { NodeType } from '../types'

/**
 * Get the name of the icon associated with a Stencila Schema node type
 * 
 * Returns a generic icon for node types for which an icon has not
 * yet been specified.
 * 
 * @param nodeType The name of the Stencila Schema node type
 */
export function iconForNodeType(nodeType: NodeType): string {
}
```

Note that at present `type NodeType = string`. However, we have a [Rust enum for this](https://github.com/stencila/stencila/blob/e11ec397176b7645b7a43eec94fcb30d4dd4a3d9/rust/node-type/src/node_type.rs) so in time we may generate the corresponding TypeScript discriminated union type.

**Comment by mike-parkin** [comment]
Hey @nokome, I can bootstrap this one up, then we can add the rest of the icons as they materialize,

Its somewhat related to the gutter I'm working on, so will need to be able to fetch icons based on the NodeType :)

**Comment by nokome** [comment]
Go for it @mike-parkin! I know @kusalekanayake was going to decide what icons to use for each node type but not sure how far he got with that. Maybe check in Figma?

**Comment by nokome** [comment]
Closing as now provided by the `nodeUi` function.
