### ISSUE TITLE
feat(assistants): tune the instruction examples

### ISSUE THREAD

**Issue by brettc** [stencila/stencila#2003]
### Summary

Custom assistants contain a list of "instruction-examples", from which we created sentence embeddings. These embeddings are then used to match an appropriate stencila assistant for responding to the command. 

The current instruction examples are mostly what used to be there as part of a regex (which was the old way of matching them), and thus are pretty short and don't contain much context. For example:

For example, here is the current definition of `insert-math-block`
```md
version: "0.1.0"
preference-rank: 100
instruction-type: insert-blocks
instruction-examples:
  - write an equation
  - write a math equation
  - write some math
  - insert a math equation
  - insert a LaTeX equation
expected-nodes: MathBlock
```
Each line in the list has a separate embedding.
The problem is that these sentences contain very little information, and the embeddings end up close to similar sentences for `insert-code-chunk`

I suspect longer sentences, with specific examples including equation names and mathematical concepts, might give us better chance of matching what the user will typically write, which will contain more context, and be enhanced with information from the document too.

There is some testing code in the assistants directory that can be used to play with this (`tests/specialised.rs`)

**Comment by nokome** [comment]
Closing, outdated/superseded.
