### ISSUE TITLE
bug(source view): node type gutter indicator glitches

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction URL (if applicable)

http://localhost:9000/nodes/article-ark/article-ark.json?view=source

### branch

main

### commit hash

804069e0abdf1790c6534009674b62e0c589a036

### Description

Some examples from `examples/nodes/article-ark/article-ark.json`:

### Duplicated icons for `CodeBlock`, `CodeChunk`, `MathBlock`, (others?)

![image](https://github.com/stencila/stencila/assets/1152336/6f2c1aee-6dc1-4148-a3ad-90bb606b00c0)

### When line wrapping is on, gutters works,... until it doesn't

I'm not sure it this is easily fixable. It may not be worth fixing if it isn't as it only seems to appear at really narrow widths:

[Screencast from 2024-02-19 15-53-00.webm](https://github.com/stencila/stencila/assets/1152336/58109df3-e5e2-4474-a1de-5a45b248811b)

### Broken range for `QuoteBlock`

I'm putting this here for completeness but suspect it is an issue with the calculation of character ranges for `QuoteBlock` in the Rust encoding to Markdown:

![image](https://github.com/stencila/stencila/assets/1152336/31a5a0f5-5ab3-42e4-b326-7cfc89ba2a0c)

**Comment by mike-parkin** [comment]
If we see these logs here relelated to the code block,

We can see that the lines with opening and closing delimiters are using the same start / end values

however the line in between with the 'code' content of the block, is also a `CodeBlock` node containing the `property: "code"` field and start\end values only cover the position of the content on that line. 

This is the same for the `MathBock` and the `CodeChunk` in the same example doc (article-ark.md).

![image](https://github.com/stencila/stencila/assets/73506758/9f58cb9b-08e7-429f-9d0e-325bbc8722c5)

![image](https://github.com/stencila/stencila/assets/73506758/8d9b5495-b143-4dd5-9e1f-0b529d252a4b)

**Comment by nokome** [comment]
> however the line in between with the 'code' content of the block, is also a `CodeBlock` node containing the `property: "code"` field and start\end values only cover the position of the content on that line.

That is the intended behaviour: each `MappingEntry` provides the start and end character for either the node as a whole, or if `property` is defined, for the property of that node. So for this use case, the gutter should only use entries where there is no property.

**Comment by mike-parkin** [comment]
TL:DR;
In relation to the above: 
![image](https://github.com/stencila/stencila/assets/73506758/10587d8c-ebb1-4a39-a059-a429bab9b703)

If I log all available nodes at that pos I do get two CodeBlocks with the same nodeId, this piece of code in the `nodesAt` method of `Format` is filtering out the duplicates, which is leaving us with the single node with incorrect inputs. 
```
        if (!nodes.find((existing) => existing.nodeId === entry.nodeId)) {
          nodes.push({ ...entry, start, end })
        }
```
I'll use that condition to check for the porperty field :)

**Comment by nokome** [comment]
No longer relevant, removed.
