### ISSUE TITLE
bug(split view): extra vertical scroll bar, duplicated node card

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In split view we get this:

![image](https://github.com/stencila/stencila/assets/1152336/5b1f0da5-e699-4583-bd41-2c26eb4721f9)

I suggest that we need to do some refactoring here: remove the "info sidebar" from `SourceView` and make create a new `InfoView` (which will get toggled on/off by the info icon in top right, and slide out from the right). This view will be responsible for rendering summary info about the document as a whole (e.g. AI usage etc) and pop-up "node cards" for the currently selected node type, regardless of which view is in the centre - visual editor, source editor, or split view.

**Comment by simonwinter** [comment]
To do:

- [ ] Remove the info sidebar from source view
- [ ] Create a new `InfoView`
- [ ] Toggle the view on/off via the toolbar
- [ ] Animate info view - slide in/out from right
- [ ] Review how info is sent to the info view - perhaps a context at a higher level?

I think we will need a context which will wrap at least the document (inside whatever view - Source editor ect) + the `InfoView`. Once I get the above set up, we'll need to look at the components that ado get rendered as noted above by @nokome:

> summary info about the document as a whole (e.g. AI usage etc) and pop-up "node cards" for the currently selected node type, regardless of which view is in the centre

**Comment by nokome** [comment]
No longer relevant.
