### ISSUE TITLE
test(r kernel): run tests on other machine locally

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2078]
Currently all tests in `kernel_r::tests` fail on CI despite R being installed there. Rather than try to debug this on CI, we should first get some other devs to try running those tests locally on their own machines.

```console
RUST_LOG=trace cargo test -p kernel-r -- --nocapture
```

For this to work, R will have to be installed on that machine.  Might also be worth trying within an R ocker container.

**Comment by ignatiusm** [comment]
@nokome - just pull updates and ran `RUST_LOG=trace cargo test -p kernel-r -- --nocapture` all 15 tests failed. See screenshots for a selection of error messages:

![image](https://github.com/stencila/stencila/assets/11403879/80859c6f-86b3-4abe-9606-55fad89d08dd)

![image](https://github.com/stencila/stencila/assets/11403879/0dc5f8b6-027d-4d22-a7b3-1675972cf3a2)

![image](https://github.com/stencila/stencila/assets/11403879/c1b9084e-0d93-4f4e-9710-76a329cfbad9)

I'm using R version 4.3.2 ("Eye Holes" !?!)

**Comment by ignatiusm** [comment]
Running `DEV=true Rscript kernel-r/src/kernel.r` from the rust dir resulted in this error:

![image](https://github.com/stencila/stencila/assets/11403879/0292b174-d0e1-458a-be93-473ca2af0bd3)

Looks like `jsonlite` and `base64enc` packages did not successfully install.

**Comment by nokome** [comment]
Oh right, of course. Thanks for that! Very useful.

**Comment by nokome** [comment]
I _think_ the issue was with `repo` instead of `repos`. Now a couple of tests pass on CI built not all of them. @ignatiusm could you try `DEV=true Rscript rust/kernel-r/src/kernel.r` again please with the current push on that branch.

**Comment by ignatiusm** [comment]
Alas the same error, but with `Cairo` now too 😬 

![image](https://github.com/stencila/stencila/assets/11403879/87d5c7ce-74b5-4267-9623-ce79ffd1f261)

**Comment by ignatiusm** [comment]
Okay, on my linux machine I can run `DEV=true Rscript rust/kernel-r/src/kernel.r` - except I get a warning that Cairo did not install correctly. However, the "repl" still works as expected for simple `EVAL` statements.
