### ISSUE TITLE
feat(design): Implement clearable fields in config panel

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#2095]
### Summary

The input fields now are designed to have a button which clears the field. Once pressed the field resets.

- [ ] Ensure the look and feel matches the design

See: https://www.figma.com/file/v86ud2R9zKX8ARl3jzPg7K/Stencila-Design-System?type=design&node-id=1028%3A59203&mode=dev

**Comment by nokome** [comment]
Closing as this functionality removed (#2309).
