### ISSUE TITLE
Frontend Keys Design Audit

### ISSUE THREAD

**Issue by kusalekanayake** [stencila/stencila#2097]
Things to consider:

- The windows need pop out a little more (colour/contrast wise)
- Turn off spellcheck within input fields
- Save or "Save keys" instead "Save me" 
- Clear field icon/button
- Not actually saving. - save button sends a get request.

Potentially look at having each field save itself?
- When you click out of the field it saves the request

**Comment by nokome** [comment]
@simonwinter this is looking great but could you take a look at these issues that Kusal and I identified the other day. I think the "Potentially look at having each field save itself?" items should be ignored at this at this stage. The main issue if the "Not actually saving. - save button sends a get request."

We should spend too much time on this - implementing and iterating on the designs for "node cards" which we still have Kusal's time is more important - but it would also be nice to draw a line under this little part of the UI.
