### ISSUE TITLE
fix(config): fix secret retrieval and setting

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#2111]
### Summary

Currently there are a couple of challenges to the saving of the settings panel:

- [ ] GET ~/secrets is fetched on every page load. It should only occur when the secrets config panel is opened
- [ ] Existing secrets should not be able to be modified directly, instead we should clear the existing value before adding a new value
- [ ] OR - users should be able to pasted in a new value which replaces the old value.

This first point will require some loading UI. There are existing designs which applies an overlay on top of the panel, making the elements inaccessible until the request has completed.

**Potentially:**

- [ ] An alternative approach would be to treat operations on keys a lot more atomically and just fire a POST when a secret is set and a DELETE when the clear button is pressed.

This approach is nicer. It does require some UI, UX and potentially some rust API work:

- A user clears a field (fire a DELETE - do we prevent any interaction until we get confirmation?)
- A user enters text into the field & loses focus on the field:
  - Make sure the field is deactivated
  - Send the request
  - Indicate a request is happening on that field
  - Update the UI to show that the field was successfully saved
  - Display the redacted version of the secret that was saved

**Comment by nokome** [comment]
Closing as this functionality removed (#2309).
