### ISSUE TITLE
fix(`<stencila-ui-node-execution-ended>`): refresh the humanized representation and show the ISO 8601 date/time in the tooltip

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2125]
The current implementation is here:

https://github.com/stencila/stencila/blob/bbe35ecb008cb630c0f7249eb70d09fee7badb34/web/src/ui/nodes/properties/execution-ended.ts

It is fine, but the humanized time does not update and the tooltip currently shows the raw timestamp.

@mike-parkin could you please work on this and submit a PR for it. I can't imagine it would take more than an hour but please let me know if you think it will because I might de-prioritize it in that case.

**Comment by mike-parkin** [comment]
I think this won't take very long, I'll give it an hour, but allow for two, the tooltip will take about 5-10 at most, and will see about adding an interval every couple of minutes to update the timeago string
