### ISSUE TITLE
feat(node card padding): reduce vertical height of node cards

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#2154]
### Summary

Look at vertical padding around the elements in the node cards

**Comment by nokome** [comment]
An example of the excessive vertical spacing from http://localhost:9000/nodes/code-chunk/code-chunk.json?view=split (after executing last chunk):

![image](https://github.com/stencila/stencila/assets/1152336/2e7a8218-3b76-4a33-84c1-2471f441ce2e)
