### ISSUE TITLE
feat(node-card): Rendering issues to address

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#2187]
### Summary

Following on the work of #2174, there are a few issues that have fallen out of this issue:

- [x] there are new `in-flow` & `on-demand` components. They are copy+pasted from the original `node-card` component. There's much that can be shared, particularly the styles between the components. Let's see what we can rationalise here.
- [ ] The `styled-block` and `styled-inline` components are causing some rendering issues (see below). Ideally we'd be able to merge the styles together to resolve these issues.
- [x] Output overflow not providing scrolling.
- [ ] Tooltips displayed on the `on-demand` instances are not displaying correctly (i.e. missing bg colour)
- [ ] If a node-card's title is a programming language, ensure that it renders the correct title, capitalisation etc.

![CleanShot 2024-04-03 at 16 55 26](https://github.com/stencila/stencila/assets/1104537/33e60501-b4a8-4b02-aa45-01bcd5b71255)
_Styled block not merging bg colour & padding. Also note the elements are not displayed full width_

![CleanShot 2024-04-03 at 16 57 44](https://github.com/stencila/stencila/assets/1104537/8c8db250-a086-4256-b5a4-c8a94075534e)
_Inline block not merging bg colour and padding_

![CleanShot 2024-04-03 at 16 58 55](https://github.com/stencila/stencila/assets/1104537/fa9eed09-1ebf-4b18-b956-cf15140bfa15)
_Dynamically generated classes are not rendering as expected_

![CleanShot 2024-04-03 at 17 00 07](https://github.com/stencila/stencila/assets/1104537/e5cd6e9b-98bf-4561-a663-0f24a145b2e3)
_Missing scrollbar on output with overflow_

![CleanShot 2024-04-08 at 13 57 27](https://github.com/stencila/stencila/assets/1104537/3879f58f-6f10-46cf-bffe-392f3d495655)
_Tooltips on top of tooltips!_

**Comment by nokome** [comment]
Closing as mostly done
