### ISSUE TITLE
feat(web view): show detailed information of each block

### ISSUE THREAD

**Issue by simonwinter** [stencila/stencila#2201]
### Summary

**Description:**

Like the previous work, the vscode extension should have a side panel that allows people to see details about a particular block. This will mean we have a web view which will render the existing components we've previously developed for node-cards.

**Details:**

- [ ] @nokome to set up the rendering so we can inject our components
- [ ] Prioritise single node view (no need to worry about an entire document)
- [ ] Bring in existing node cards

**Comment by nokome** [comment]
Closing this as mostly done and/or superseded
