### ISSUE TITLE
feat(web): add styling and folding for admonitions

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2280]
During testing I noticed that `<stencila-admonition>` was missing so have stubbed one out with a bunch of `TODOs` in it related to styling:

https://github.com/stencila/stencila/blob/main/web/src/nodes/admonition.ts

Currently it looks like this:

![image](https://github.com/stencila/stencila/assets/1152336/dd4682cc-0467-4c4f-81cb-adeeb94ed612)

But should look more like all the other admonitions, "callouts", and "alert boxes" on the web e.g.

- https://v1.tailwindcss.com/components/alerts#titled
- https://flowbite.com/docs/components/alerts/
- https://docusaurus.io/docs/markdown-features/admonitions
- https://mystmd.org/guide/admonitions

**Comment by mike-parkin** [comment]
@nokome thanks for the TODOs, would you like me to treat these nested paragraph nodes the same as list items, table cells captions etc...

**Comment by mike-parkin** [comment]
@nokome here is the "draft" style I've chosen for the admonition

![image](https://github.com/stencila/stencila/assets/73506758/68b61c9d-7ea1-4035-85e1-fa76a8d8e371)

No rush, but when you get round to it,
Just leave a list of any requested changes in a comment here :)

**Comment by nokome** [comment]
Thanks @mike-parkin 

> treat these nested paragraph nodes the same as list items, table cells captions

Yes, that seems appropriate.

> Just leave a list of any requested changes in a comment here

I feel like the borders could be a little more rounded and a little lighter maybe? But maybe get a second, or third opinion.
