### ISSUE TITLE
Boolean literals in Mini

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#230]
In Mini add literals for Boolean values: `true` and `false`. This is the use case that I just wanted it for: `points(mytable) | theme({mark: {filled:true, color: '#208'}})`

**Comment by oliver----** [comment]
Introduced via https://github.com/substance/mini/pull/8
Published as substance-mini@0.7.0

**Comment by oliver----** [comment]
Wait for it. Having issues with generated tokens.

**Comment by oliver----** [comment]
This ready now as 'substance@0.7.1'

**Comment by oliver----** [comment]
Update included in PR #242
