### ISSUE TITLE
Mini: keyword arguments for function calls

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#231]
It would be really good to have keyword function arguments soon. The following is a motivating example with respect to plotting functions. In the plotting functions we have multiple encoding channels, most of which are optional. It's difficult to have a nice plotting quickstart without keyword args (temporary hacks could included using objects for encodings but it would be a shame to have to resort to that).

Here, the variable `z` is encoded to the `color` channel:

![image](https://cloud.githubusercontent.com/assets/1152336/24123835/0986729a-0e26-11e7-9a15-df44ac4babb8.png)

But, currently, if we want to encode it instead to the `size` channel then we need to do this:

![image](https://cloud.githubusercontent.com/assets/1152336/24123856/2d4f7834-0e26-11e7-9c4a-bedaf0785512.png)

If keyword arguments were enabled for `callFunction` then we'd be able to do this instead:

```
mytable | points('x', 'y', size='z') | titles('Price', 'Supply', size='Quality')
```

And ultimately given default parameter values and with symbols this could be written as:
```
mytable | points(size=.z) | titles('Price', 'Supply', size='Quality')
```

Keyword args are already enabled in the syntax, just need to map them to the function signature in the right way. @oliver---- if you point me to the place in the code I don't mind giving this a try if you don't have time.

**Comment by nokome** [comment]
OK, I think I've figured out where this needs to be done: CellEngine.js line 126 - tells me! I'm going to give this a go now by giving each function a property called `args` - a list of argument names - and then mapping to those.

**Comment by nokome** [comment]
So, I thought I was getting close. The `JsContext` is working as expected: mapping named variables into an array of values expected by `fun.pars` (see `JsContext.test.js` on `fix-plotting-functions` branch) But it seems that the mini parser is no longer handling named arguments - I remember this worked a week or so ago. For example, here in a call, we should get [5,8] in the returned array. The parser error is "mismatched input '=' expecting ')'" . This is on master with a fresh npm install.

![image](https://cloud.githubusercontent.com/assets/1152336/24178383/aacec7be-0f0d-11e7-8123-0d99ad7a84b4.png)

@oliver---- if you can fix this I'll be sure to buy you several :beers: next time!

**Comment by oliver----** [comment]
@nokome ah, I am sorry for that. I must have removed this in some un-explainable state of mind ;)
Will do it, with 🍻 or without -- and also 🍷  does work.

**Comment by oliver----** [comment]
Almost there: https://github.com/substance/mini/pull/6

**Comment by oliver----** [comment]
@nokome published as substance-mini 0.6.0

Take a look at https://github.com/substance/mini/blob/bb0e030378989ee4548589f3bc6b2b432e25b263/test/engine/TestEngine.js#L55
to see how I have used it in the tests

**Comment by nokome** [comment]
@oliver---- great, thanks! I'm integrating these changes into CellEngine.js now

**Comment by nokome** [comment]
This is now working! Closing...

![image](https://cloud.githubusercontent.com/assets/1152336/24225958/6329090e-0fc8-11e7-9eb4-010efc901d70.png)

**Comment by oliver----** [comment]
Sweeeet 💯
