### ISSUE TITLE
Critical issues

### ISSUE THREAD

**Issue by michael** [stencila/stencila#232]
Latest Substance changes (black-/whitelisting of commands) introduced regressions. Tools/commands are broken in Stencila. I just reverted back to 1.0.0-beta.7.0-preview.0, where things still worked.

@oliver---- if you can please provide a fix

Some other issues I've noticed:

- [x] When editing a mini lang cell native selection gets recovered always on first position
- [ ] The body element gets style `cursor: default` set. So we don't see a text cursor anymore. Could't find the code that does that.

**Comment by oliver----** [comment]
Pls merge #229

**Comment by oliver----** [comment]
The regression is not related to Substance. More it was a left over of old and now wrong API

**Comment by oliver----** [comment]
You should revert your revert

**Comment by michael** [comment]
Will do!

**Comment by michael** [comment]
Done. Thank you!

**Comment by nokome** [comment]
Thanks @oliver---- ! :+1:

**Comment by oliver----** [comment]
@michael @nokome I have arrived in Vienna. All smooth.

**Comment by michael** [comment]
Excellent! :) Thanks for the update.

**Comment by oliver----** [comment]
@michael me neither.

**Comment by oliver----** [comment]
I would suggest, not to leave it to the body to set the cursor?

**Comment by oliver----** [comment]
Seems to be the VegaLite renderer doing that.

**Comment by michael** [comment]
That's evil. Why would they want to do that? :/

**Comment by oliver----** [comment]
@michael dunno. But vega does it. Have you tried the 'Break on' feature in Chrome?

**Comment by michael** [comment]
'Break on'?

**Comment by oliver----** [comment]
I already start liking vega :) 
It also seems to be so kind to cache the rendering result and providing the correct result only on every second call.

**Comment by oliver----** [comment]
'Break on' gives you a way to find out who is changing an element.

**Comment by michael** [comment]
Yeah, seems we soon need Dejavis Light 📊 ;)

**Comment by oliver----** [comment]
Closing this as it has a very noisy title

**Comment by oliver----** [comment]
@michael maybe we could be more specific in future? I am not very fond of such gathered issues. Tolerating it when external people are writing issues. As we are not external, we could take the time to create dedicated ones. A title 'Critical issues' is in my point of view just lacking of some exclamation marks in the title.
