### ISSUE TITLE
feat(vscode): Would be nice to see kernel executable path 

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2333]
Surfacing what path the kernel executable is running from would be beneficial to a user debugging and understanding what packages will / won't be available from a venv. 

This could also be beneficial to store in the provenance records as well.  

In Python this would be accessed as: 
```
import sys
sys.executable
```

**Comment by nokome** [comment]
Thanks for the suggestion, and yes I agree. The most natural place to put this along side the other `SoftwareApplication` (LLM) schema.org objects in the "authors" property. That may feel a little _unnatural_ initially but would be internally consistent, and could be surfaced elsewhere too.

**Comment by jduckles** [comment]
I do think that is reasonable as different authors may run blocks in different environments. Is that work you've done to dump the environment for prompts captured in the Schema too. For example, could/do you log the set of installed packages into the schema?

**Comment by nokome** [comment]
When there is a sibling `devbox.json` next to the document, the paths resolve to the binaries in the Nix store:

![image](https://github.com/user-attachments/assets/20ec35de-d54a-4d72-b8c5-93136786cd09)
