### ISSUE TITLE
feat(cli) - by default don't show "special kernels"

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2334]
For user experience consistency, all kernels should be accessed in a consistent way. 

In `cli kernels command` consider suppressing kernels that aren't accessed by backtick blocks.  Add a flag for "special" kernels or somesuch and only show them with a `--all` 

Currently the `style` kernel can be accessed as 
    
    ::: style 

Which is inconsistent with other kernels being accessed as:
 
    ```python exec 
      import rand
      rand.randint(1,6)
      ```

**Comment by nokome** [comment]
I've taken the approach in 5567d229eca5ce4b5a8f817a86f4e733a6d1a87e of adding a `KernelType` enum. The listing of kernels now starts with and is ordered by, and can be filtered by the type.

![image](https://github.com/user-attachments/assets/2169dc0e-7276-4aa3-8073-71bd279da9c7)

Although this is not exactly what was specified in this issue, I think it is a better more internally consistent solution, particularly for the type of user that is likely to be using this command.
