### ISSUE TITLE
bug(vscode) - R blocks hang with "Running" forever

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2348]
Any R block will hang on Mac saying "Running", left overnight (to see if it was doing package installs or something) and nothing changed. 

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/2e110753-f016-43c1-b775-0817ae5c9b6c">

**Comment by jduckles** [comment]
`ps -aux |grep stencila` shows me R is running with following command: 

`/Library/Frameworks/R.framework/Resources/bin/exec/R --no-echo --no-restore --file=/Users/jduckles/Library/Application~+~Support/io.stencila.stencila/kernels/r`

Running that interactively shows me: 
`Fatal error: R home directory is not defined`

Setting `R_HOME=/Library/Frameworks/R.framework/Resources/` gets the kernel running:

`R_HOME=/Library/Frameworks/R.framework/Resources/ /Library/Frameworks/R.framework/Resources/bin/exec/R --no-echo --no-restore --no-init-file --no-restore --file=/Users/jduckles/Library/Application~+~Support/io.stencila.stencila/kernels/r`

**Comment by nokome** [comment]
Thanks for this info, it is useful. Could you please run the following (using the `kernels exec` command which is a way to test running ad-hoc snippets of code in each kernel) and share the outputs:

```console
cargo run -p cli kernels exec r "1 + 1"
```

```console
R_HOME=/Library/Frameworks/R.framework/Resources/ cargo run -p cli kernels exec r "1 + 1"
```

You could also/instead run `stencila kernels exec ..` if you have that installed.

**Comment by jduckles** [comment]
```
cargo run -p cli kernels exec r "1 + 1"
```
Outputs 2 as expected 🤔 

In same environment (just to check) the following still fails:
```
/Library/Frameworks/R.framework/Resources/bin/exec/R --no-echo --no-restore --file=/Users/jduckles/Library/Application~+~Support/io.stencila.stencila/kernels/r
```
```
Fatal error: R home directory is not defined
```

**Comment by nokome** [comment]
That's weird, I suspected what is happening is that in your `~/.bashrc` or similar you have `export R_HOME=/path/to/R` but when you start VSCode it does not have access to that env var. But that second test of yours in the same env goes against that???

Regardless, I think we can fix this in Stencila by setting R_HOME if that is not already set. But need to check the conventions for that. I thought there was some config file that it would fall back to.

**Comment by nokome** [comment]
Closing this as it seems to have been fixed.
