### ISSUE TITLE
feat(document menu): add expand all option to the preview menu

### ISSUE THREAD

**Issue by mike-parkin** [stencila/stencila#2352]
### Summary

Add the ''Expand All Node Cards" option to the preview menu,

Upon clicking. all node cards should be expanded. 

For simplicity this should be an isolated function to expand all the cards this will be the easiest way to  avoid any conflicting states with the node chips.

This will be useful for when e2e tests are integrated so we do not have find and open the cards in before each test case.

Would recommend adding "collapse all" option as well.

**Comment by nokome** [comment]
Closed
