### ISSUE TITLE
Mini: array and object literals

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#237]
Expressions like `{a:4}` and `[1,2,3]` are parsed when pasted into cell. But when you try to type them from scratch an error is thrown : `Uncaught TypeError: Cannot read property 'items' of undefined`

**Comment by oliver----** [comment]
@nokome almost done: https://github.com/substance/mini/pull/7

**Comment by oliver----** [comment]
published as 0.6.1

**Comment by michael** [comment]
Fixed.
