### ISSUE TITLE
Mini: pipe operator

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#238]
The pipe operator is not passing on named arguments. Also it seems to be calling a function twice - once without the piped first argument, and then a second time with the `_pipe` but without named arguments. See the hack here: https://github.com/stencila/stencila/blob/fix-plotting-functions/src/document/CellEngine.js#L133. This hack does not seem to work when there is more than one pipe in an expression.

**Comment by oliver----** [comment]
Fixed via https://github.com/substance/mini/pull/7

**Comment by oliver----** [comment]
Use `substance-mini: ^0.6.1`

**Comment by michael** [comment]
Nice! Will try!

**Comment by michael** [comment]
Working! Thanks a lot!
