### ISSUE TITLE
bug(vscode) - Larger (4+) numbers of backticks being rewritten to just 3

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2390]
I've been trying to wrap literal expressions I want to show users that they would type into their editor. To do so I've been wrapping things liks:

    ````markdown
    ```python exec
    import random
    random.randint(1,6)
    ```
    ````

Periodically Stencila/ LSP seems to be rewriting my stronger four backtick sections to just 3, eliminating their effect.

**Comment by nokome** [comment]
A backtick fenced code block like this gets parsed to a `CodeBlock`. A `CodeBlock` does not "know" which format it was parsed from or how many backticks are used and when it is encoded back to Markdown assumes that 3 backticks will do, which is clearly a wrong assumption in these cases.

 We can fix this, without having to add an ad-hoc property to the `CodeBlock` node type by scanning the `code` property and finding the maximum number of starting backticks and adding one more than that (min 3).

**Comment by nokome** [comment]
Added a `MarkdownEncodeContext::enclosing_backticks` function, applied it to `CodeBlock` and `CodeChunk` encoding, and added tests in 6cf886b31a2fcf79781594a917cb963cd1b580c9.
