### ISSUE TITLE
bug(Walkthrough): Walkthrough bugs (Math)

### ISSUE THREAD

**Issue by kusalekanayake** [stencila/stencila#2411]
### What happened?

While trying to record some walkthroughs for our VS Code extension page, I encountered some issues with the create flows. Most importantly, the accepting of the suggestions doesn't work (See bellow gif). It works for the fix prompt found later in the walkthrough. 

![CleanShot 2024-11-13 at 10 42 54](https://github.com/user-attachments/assets/9bc8379c-cf9e-4862-bc07-2526de973761)

Other found bugs:

- [ ] Unable accept create suggestions
- [ ] Unable to add modifiers like x3

These issues have only been found within the walkthroughs.

### Which product?

Stencila VSCode extension

### Which version?

0.0.12

**Comment by nokome** [comment]
Thanks for reporting this. I can confirm this bug, but seemingly only within a walkthough. Will investigate further try to get a fix out soon.
