### ISSUE TITLE
fix(preview): Styling inline code

### ISSUE THREAD

**Issue by kusalekanayake** [stencila/stencila#2413]
The current default styling of inline code is a little out of place with the font size being larger than what it should be to fit with the default body text. Alongside this the backticks that are used to denote the inline code should not be able visible in the preview. 

<img width="603" alt="image" src="https://github.com/user-attachments/assets/9f3698bd-208f-464c-a5d7-41a87df9854c">

<img width="641" alt="image" src="https://github.com/user-attachments/assets/92c8d428-aef3-4701-a396-a196b56f5a25">

**Comment by jduckles** [comment]
Yes! The passthrough of the backticks has kind of irked me, but I wasn't going to say anything 😆
