### ISSUE TITLE
feat(preview): Create card, re-adding revise option 

### ISSUE THREAD

**Issue by kusalekanayake** [stencila/stencila#2415]
### Which component?

Stencila VSCode extension

### What's your idea?

While adding the carousel, we removed the ability to revise a prompt in the preview UI. This is a small issue to re-add the ability to revise a prompt. It can function the way it has previously

![image](https://github.com/user-attachments/assets/8b5befea-36c8-42ad-b999-8d0af77de898)

Maybe something like this once the revise option has been selected?
![image](https://github.com/user-attachments/assets/615042ec-eea2-4247-a130-d02300b7e9e8)

**Comment by nokome** [comment]
Closed in #2426
