### ISSUE TITLE
bug(web): node chip overlaps make for difficult interactions

### ISSUE THREAD

**Issue by kusalekanayake** [stencila/stencila#2416]
### What happened?

![CleanShot 2024-11-14 at 10 53 12](https://github.com/user-attachments/assets/d6eefaca-c194-4611-9271-51d935caa9e6)
Selecting specific node chips can be a challenge when there are several different chips stack upon each other. There may have been some work started in the past around the interactions between different node chips and how they could stack. If we are able to make them stack more consistently it would vastly improve the experience of users interacting with the node chips.

### Which product?

Stencila VSCode extension

**Comment by nokome** [comment]
Closing, completed in #2442.
