### ISSUE TITLE
Inline cells are not updating

### ISSUE THREAD

**Issue by michael** [stencila/stencila#242]
Reproduce:

Go to

http://localhost:4000/examples/document/?documentId=guide-mini

And use the radius slider:

![image](https://cloud.githubusercontent.com/assets/2931/24235525/9aac7d36-1002-11e7-9080-5e4505643521.png)

- area inline cell is undefined at the beginning and only gets activated if you wrap it with a selection

@oliver---- can you take a look?

**Comment by oliver----** [comment]
BTW, area is `pi*r^2`;)

**Comment by oliver----** [comment]
Fixed via https://github.com/stencila/stencila/pull/244
