### ISSUE TITLE
bug(vscode): long mermaid diagrams over-run their container element

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2436]
### What happened?

<img width="827" alt="image" src="https://github.com/user-attachments/assets/bc6a7935-ac1e-4fcc-bc58-09dbad359f5f">

````raw
```mermaid exec
flowchart TD
    A[Create Sourdough Starter] --> B[Feed Starter Regularly]
    B --> C[Mix Starter with Water and Flour]
    C --> D[Autolyse]
    D --> E[Add Salt]
    E --> F[Knead Dough]
    F --> G[Bulk Fermentation]
    G --> H[Shape Dough]
    H --> I[Final Proof]
    I --> J[Preheat Oven]
    J --> K[Bake Bread]
    K --> L[Cool and Enjoy]
```
````

### Which product?

Stencila VSCode extension

### Which version?

v0.0.15

### Log output

```shell
NA
```

**Comment by jduckles** [comment]
Alright, this doesn't duplicate in a shorter file by itself. Will try to narrow down furhter the circumstances.

**Comment by nokome** [comment]
I think this could be a walkthrough related issue. The styling of the `stencila-walkthough-step` is to blame (i.e. me 😊 ).

**Comment by jduckles** [comment]
I was just coming here to say that!

**Comment by nokome** [comment]
@mike-parkin can you please check this still an issue, fix it if it is, or close this if it isn't

**Comment by mike-parkin** [comment]
Loaded up the mermaid walkthrough to check, It all seems to be gong as expected since resolving the max-height of the walkthough steps.

![image](https://github.com/user-attachments/assets/b6e5b158-3210-4e46-86e6-077c2a4aab31)
