### ISSUE TITLE
bug(vscode): Change `Command-->` `Command-<-` for next suggestions

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2451]
### What happened?

Command + Arrow is already used in VSCode to go to the beginning or end of the line.

I suggest changing this Stencila default to avoid annoying users who are already used to and are using it. 

### Which product?

Stencila VSCode extension

### Which version?

v0.0.17

**Comment by rowanc1** [comment]
🙏

**Comment by nokome** [comment]
Suggestions for a better set of key bindings for this would be gratefully received.

**Comment by rowanc1** [comment]
`cmd-[` is used in many graphics/slide programs to change the depth of the layer. Which is kinda similar here?

**Comment by jduckles** [comment]
That would make it simliar `command-shift-[` which moves through browser tabs or in VSCode case document tabs (which is in my muscle memory in browserland). 

I like `cmd-[` as an idea. Trying it, I don't see that its doing anything in VSCode.

**Comment by nokome** [comment]
Unfortunately `Cmd+[` and `Cmd+Shift+[` already have default bindings in VSCode. However, `Cmd+Alt+[` is not used by default and has a similar purpose in VSCode's Jupyter Notebook interface:

![image](https://github.com/user-attachments/assets/de44aeb7-864e-457c-a849-e1596a3e639a)

So I will go ahead with:

- `Ctrl + Alt +  [`: got to previous suggestion (wraps)
- `Ctrl + Alt +  ]`: go to next suggestion (wraps)
- `Ctrl + Alt +  \` (adjacent key): accept current suggestion
