### ISSUE TITLE
bug(vscode): provenance chips / bars go off screen for crowded / large font screens

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2452]
### What happened?

Saw this in a user test today when the font size was cranked up during screen sharing:

![Screen-Recording-2024-11-28-11-10-58](https://github.com/user-attachments/assets/05932a8f-95e6-4d0c-b1b6-a8dfd2a4114a)

### Which product?

Stencila VSCode extension

### Which version?

v0.0.18

**Comment by mike-parkin** [comment]
the easiest way to fix this is to increase the x-padding of the document window (an extra 1rem should do it).

alternatively I can set a window breakpoint in the component to reduce the offset when the innerwidth gets below a certain point.

Here's what is looks like with the padding added:

![image](https://github.com/user-attachments/assets/7df548ec-29d2-493a-97e7-251e990a5492)

**Comment by nokome** [comment]
I'm wondering if both make the padding and the reduced offset on smaller devices make sense (i.e. remove "alternatively" from your suggestion :))
