### ISSUE TITLE
feat(cli): `convert` formats

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2454]
### Which component?

Stencila CLI

### What's your idea?

As we're starting to add more formats, it would be nice if there was a flag to show available formats. 

`pandoc` uses: 

`--list-input-formats` and `--list-output-formats`

We could adopt the same flags for: 
`stencila convert --list-input-formats` or
`stencila convert --list-output-formats`

**Comment by mduckles** [comment]
does the command `codecs' do it? or should there be different ones for input and output?
![Screenshot 2024-11-28 at 15 36 02](https://github.com/user-attachments/assets/589d4dbd-7e8b-4e80-975c-b3543bad4b21)

**Comment by jduckles** [comment]
So we may want to reveal this over in the `stencila convert` area for user convenience? Maybe with file extensions as a column instead of status? 🤔

**Comment by nokome** [comment]
Yes, the `codecs` command is intended for this. I was thinking that we could add more columns e.g. `Input formats`, `Output formats`.

> Maybe just a note in stencils convert that you can see available formats with stencila codecs would suffice.

Yep, I think that is better than adding more options to `convert`.

Note that several commands (`convert`, `execute`, `render`) have format related arguments (generally `--from` and `--to`) and so the note should probably be attached to those options, or to all of those commands, not just to `convert`.

**Comment by nokome** [comment]
CLI help test comes from the doc comments on structs like this. So this is where to add additional notes:

![image](https://github.com/user-attachments/assets/b2748ced-8b8a-4a34-82ac-255ea0931369)

For adding more columns to the `codecs` table this is the place:

![image](https://github.com/user-attachments/assets/d5a74919-82f7-4743-afb8-1132d7735696)

See `rust/kernels/src/cli.rs` for an example of a more fully implemented table with colours etc.

**Comment by jduckles** [comment]
Closed by #2456
