### ISSUE TITLE
Some mini runtime errors not caught

### ISSUE THREAD

**Issue by michael** [stencila/stencila#252]
If I typed `doesNotExist()` into a minilang cell, I would expect it to end up catched and added to the runtime errors object. Currently have that Exception popping up in the CellEngine.

![image](https://cloud.githubusercontent.com/assets/2931/24317922/5a24bd6c-1162-11e7-8bfb-630c202a7050.png)

**Comment by oliver----** [comment]
Still I think the display needs some love, but this particular issue is fixed.
