### ISSUE TITLE
Problem with evaluation order

### ISSUE THREAD

**Issue by michael** [stencila/stencila#254]
Observing that table function gets called before concat(repeat...) has completed evaluating. This produces some subsequent errors because we have more cells depending on the table, which has missing data.

Here's the snippet from the guide document.

```js
table({
species: {type: 'nominal', values: concat(repeat('setosa',50), repeat('versicolor',50), repeat('virginica',50))},
sepal_length: {values: [5.1,4.9,4.7,4.6,5,5.4,4.6,5,4.4,4.9,5.4,4.8,4.8,4.3,5.8,5.7,5.4,5.1,5.7,5.1,5.4,5.1,4.6,5.1,4.8,5,5,5.2,5.2,4.7,4.8,5.4,5.2,5.5,4.9,5,5.5,4.9,4.4,5.1,5,4.5,4.4,5,5.1,4.8,5.1,4.6,5.3,5,7,6.4,6.9,5.5,6.5,5.7,6.3,4.9,6.6,5.2,5,5.9,6,6.1,5.6,6.7,5.6,5.8,6.2,5.6,5.9,6.1,6.3,6.1,6.4,6.6,6.8,6.7,6,5.7,5.5,5.5,5.8,6,5.4,6,6.7,6.3,5.6,5.5,5.5,6.1,5.8,5,5.6,5.7,5.7,6.2,5.1,5.7,6.3,5.8,7.1,6.3,6.5,7.6,4.9,7.3,6.7,7.2,6.5,6.4,6.8,5.7,5.8,6.4,6.5,7.7,7.7,6,6.9,5.6,7.7,6.3,6.7,7.2,6.2,6.1,6.4,7.2,7.4,7.9,6.4,6.3,6.1,7.7,6.3,6.4,6,6.9,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9]},
sepal_width: {values: [3.5,3,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,3.7,3.4,3,3,4,4.4,3.9,3.5,3.8,3.8,3.4,3.7,3.6,3.3,3.4,3,3.4,3.5,3.4,3.2,3.1,3.4,4.1,4.2,3.1,3.2,3.5,3.6,3,3.4,3.5,2.3,3.2,3.5,3.8,3,3.8,3.2,3.7,3.3,3.2,3.2,3.1,2.3,2.8,2.8,3.3,2.4,2.9,2.7,2,3,2.2,2.9,2.9,3.1,3,2.7,2.2,2.5,3.2,2.8,2.5,2.8,2.9,3,2.8,3,2.9,2.6,2.4,2.4,2.7,2.7,3,3.4,3.1,2.3,3,2.5,2.6,3,2.6,2.3,2.7,3,2.9,2.9,2.5,2.8,3.3,2.7,3,2.9,3,3,2.5,2.9,2.5,3.6,3.2,2.7,3,2.5,2.8,3.2,3,3.8,2.6,2.2,3.2,2.8,2.8,2.7,3.3,3.2,2.8,3,2.8,3,2.8,3.8,2.8,2.8,2.6,3,3.4,3.1,3,3.1,3.1,3.1,2.7,3.2,3.3,3,2.5,3,3.4,3]}
})
```

**Comment by michael** [comment]
This can be observed when looking at the plot cells. On the first pass they error and once the table got complete, the plots are displayed properly. (this happens quite fast)

```js
plot(data, 'points', 'sepal_length', 'sepal_width')
```

**Comment by oliver----** [comment]
I don't think it is wrong order. But what is still missing, is that the engine propagates PENDING instead of undefined. And in that case, for example, not call a function.

**Comment by michael** [comment]
I see.. better we move that to 0.26 then? And things are basically working.

**Comment by oliver----** [comment]
I an taking a look.

**Comment by oliver----** [comment]
@michael how can I open the guide?
Maybe you add some documentation about how to do this.

**Comment by michael** [comment]
Sorry, we are just about to merge in Nokome's work on the guides. Currently they are rather empty. Give us few minutes.

**Comment by michael** [comment]
You can open guides by going to http://localhost:4000/examples/dashboard/

and the link takes you there. You should be able to change the files in guides and you should see the dashboard and document example update as you reload.

**Comment by michael** [comment]
There should be some proper documents now when you go to:

http://localhost:4000/examples/dashboard/

**Comment by oliver----** [comment]
Thx.

Pending state handling is almost ready.

**Comment by michael** [comment]
@oliver---- FYI: We are now starting to silently releasing 0.25.x versions of all the packages until we are happy with the results. As a final step we will then make the desktop builds. Would like to do that in a few hours as we have to leave early tomorrow early. Would like to go through the finish line together with Nokome :)

**Comment by michael** [comment]
Oh ok.. then we will wait for that :+ thanks a lot!
