### ISSUE TITLE
Maybe make integer display a bit less bold

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#256]
![image](https://cloud.githubusercontent.com/assets/284099/24327766/f5b5a71a-11d9-11e7-8fe2-817c2126c177.png)

**Comment by oliver----** [comment]
In contrast to the float display:
![image](https://cloud.githubusercontent.com/assets/284099/24327784/1e407480-11da-11e7-8609-a40b37d2345c.png)

**Comment by michael** [comment]
Fix via #257
