### ISSUE TITLE
C/C++/Cling

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#265]
Can you consider C/C++ support also: https://root.cern.ch/cling

**Comment by nokome** [comment]
Hey @sirinath : using `cling` is a great idea (but I would say that, I'm a C++ fan!). I don't think it would be to hard to do. Would be useful for people doing computation intensive simulations. Probably not a priority for the next couple of releases but may be an option around 0.28 or 0.29.

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
