### ISSUE TITLE
Streams, Multidimensional Observable Data Structures (Series, DataTables, Panels, Tensors, Tables, Data Cubes)

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#266]
Can you consider streaming lists and tables. Data is updated from a streaming source. When new data comes the data is added along a dimension. E.g. you have a table of stock prices. This is updated when new pieces come up. This can be used to compute technicals on these data structures.

See: https://github.com/QuantStack/xtensor, https://github.com/QuantStack/xproperty

**Comment by nokome** [comment]
@sirinath : another great idea! My first thoughts are that this could be an `Input` type with either (a) a timer with an update frequency - e.g. for HTTP requests, or (b) binding to events for a streaming source. Would need to cache the source content to ensure reproduciblilty. (a) is probably a good easy place to start. 

Not sure where we prioritize this, given here are so many other things to do, but will definitely keep it in mind.

**Comment by sirinath** [comment]
Make sure they are tunes for ultra low latency sensitive, high throughput application with perhaps large about of in memory and disk cached data.

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
