### ISSUE TITLE
Data Store / DB

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#268]
Sometimes you might need to store the list and table data in a DB. So a DB to store structured, semi structured data is great.

**Comment by nokome** [comment]
Thanks @sirinath. Yes, we have a prototype `SQLiteContext` for storing and accessing data SQLite databases. We'll look to generalise that to Postgres and other DBs soon.

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
