### ISSUE TITLE
Own Language

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#269]
FFI into other languages will have a computational overhead. For Ultra Low Latency application this might be an obstacle. So it is possible to have own embedded language which can be high performance.

Key features would be

 - higher order function - like LINQ, http://quasar-analytics.org/
 - effect racking for better optimisation
 - easy to model structural and semi structured data
 - visual rendering - http://www.curl.com/, https://www.wolfram.com/cdf/

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
