### ISSUE TITLE
Editing | Rendering | Processing | Side effects / headless mode

### ISSUE THREAD

**Issue by sirinath** [stencila/stencila#274]
Make sure the architecture is such that editing components and rendering does not interfere with execution speed.

Also the ability to run the document for side effect without rendering and editing facility.  E.g. if I set up a sheet for trading, I might not want or be able to see the rendering part in production. I just want it to get the data an send the orders. What matters here is seed, accuracy and robustness.

**Comment by nokome** [comment]
Thanks for this suggestion. Yes, this would be useful for a number of reasons including rendering articles and CI type testing of sheets.
