### ISSUE TITLE
Problems with pipe operator

### ISSUE THREAD

**Issue by michael** [stencila/stencila#279]
Based on observations in the example document the initial computation works. However as updates to the data are made (e.g. changing the the filter from 'temp<=20' to 'temp<=25') cells with pipes are not updating.

![image](https://cloud.githubusercontent.com/assets/2931/24654504/2f11e958-193a-11e7-870c-d95f23c0a32b.png)

**Comment by oliver----** [comment]
Fixed via https://github.com/substance/mini/pull/13

**Comment by oliver----** [comment]
publish as substance-mini@0.8.1

**Comment by michael** [comment]
thanks a lot!
