### ISSUE TITLE
Stencila 0.25 patch release

### ISSUE THREAD

**Issue by michael** [stencila/stencila#281]
We should do a small patch release soon, just to get rid of some obvious bugs. 

We should include those fixes: 

- [x] #279 Problems with pipe operator. @oliver---- you think that is easy to fix? Alternatively we could just remove all uses of pipes from the example docs.
- [x] https://github.com/stencila/desktop/issues/8 external links
- [x] fixes in example doc #278 

@nokome Anything more? Let's try to keep this small though, as we don't have much time available this week.

**Comment by nokome** [comment]
Can't think of anything else off the top of my head.
