### ISSUE TITLE
feature-remote-contexts: ability to execute in remote contexts

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#283]
Currently, `run()` and `call()` cells can only execute code in an in-browser `JsContext`. The `feature-remote-contexts` branch adds support for executing cells in R, Python, SQLite and Node execution contexts by:

- [x] registering or discovering "peers" - other Stencila `Hosts` which support the instantiation of `RContext`, `PythonContext` etc
- [x] using the `ContextHttpClient` class to instantiate and connect to a remote context 
- [x] adding these contexts as options in the "language dropdown" (really it should be a context dropdown)

**Comment by nokome** [comment]
Woooooooot! Cells with execution in remote contexts...

![image](https://cloud.githubusercontent.com/assets/1152336/25167467/b5cf8b30-2533-11e7-8676-b722e582b5be.png)

**Comment by michael** [comment]
Wow! Nice work! :)

For the language dropdown.. can you just put some ugly buttons there, and I will try to find some time and rework. Want to develop a Menu abstraction, that we can use for different purposes in Stencila and Texture.

**Comment by nokome** [comment]
Closing this. Plenty of UI stuff still to do (like better selection of context, and stop execution etc). Looks like this for now:

![image](https://cloud.githubusercontent.com/assets/1152336/25561416/f87be2e6-2d1f-11e7-8b5e-dd8ab859c674.png)
