### ISSUE TITLE
Cell errors are not displayed when a variable is assigned

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#295]
For example:

![image](https://user-images.githubusercontent.com/1152336/27800836-f8008242-6012-11e7-918c-88bd3c6002e3.png)

versus:

![image](https://user-images.githubusercontent.com/1152336/27800813-d9937080-6012-11e7-992d-bf26d2d5c8a8.png)

this does not happen with Mini cells:

![image](https://user-images.githubusercontent.com/1152336/27800883-35f7b660-6013-11e7-839b-d0487b7c65a5.png)

**Comment by oliver----** [comment]
Fixed.
