### ISSUE TITLE
Cells should not execute while a previous execution is pending

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#298]
Particularly for external language cells that take a long time to execute you don't want additional execution requests for every keystroke. The code should still be able to be edited but execution requests should be blocked until any previous execution is completed. Some visual feedback about what is going on is needed. 

The user should probably have the option of cancelling any previous long running executions (even if we can't cancel it, it should at least be removed as a blocking execution).

**Comment by oliver----** [comment]
This is good now.
