### ISSUE TITLE
Pasting into Ace-Editor throws an error

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#303]

**Comment by oliver----** [comment]
@michael can't reproduce, could you please paste your exception here?
Make sure to have the latest version.

**Comment by oliver----** [comment]
This seems to work for me.

Reopen if necessary.

**Comment by michael** [comment]
It happens when you paste rich text (e.g. from the document) into Ace. 

Stacktrace:

![image](https://user-images.githubusercontent.com/2931/27928238-b7e5d5b2-628e-11e7-8a89-8d055150a221.png)

**Comment by oliver----** [comment]
Fixed.
