### ISSUE TITLE
Stencila app branding

### ISSUE THREAD

**Issue by michael** [stencila/stencila#308]
Making Stencila more unique we can a apply a more bluish style that goes well with the Stencila green. Here's a mockup. 

![image](https://user-images.githubusercontent.com/2931/27903932-5afba960-623b-11e7-9229-84a5d3d6c599.png)

However, let's schedule this for 0.30, and wait a bit to see if we will really go with those colors (logo etc.).

**Comment by nokome** [comment]
A good feature of the blue is that it distinguishes UI elements from document content (which is mostly black text with other colours in plots).

**Comment by nokome** [comment]
@michael : it would be nice to do this, at least to some extent, for the next release. Even just colours and icon styles...

![image](https://user-images.githubusercontent.com/1152336/37638792-7afb9344-2c73-11e8-9222-d029c9dc79b9.png)
