### ISSUE TITLE
Introduce definition of external functions

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#310]
We want to be able to expose a new function implemented in a cell something like
```
myfun = function(x:int, y:int)
return x+y
```

**Comment by nokome** [comment]
I think that this should be a fairly high priority so that we can define built in Mini functions using this approach.

To be be able to specify the external language, and to specify the type of the return value, the syntax needs to be something like this (which is very similar to Typescript's typing syntax):
```
myfunc = function js(x:int, y:int):int
return x+y
```

Do we need to allow type specification to be optional? What are the pros/cons of making it optional or not? e.g.
```
myfunc = function js(x, y)
return x+y
```

Multiple dispatch will be very useful for keeping a tidy function namespace in Mini and should be implemented as part of this. See [src/js-context/functions/types/_multifunc.js](src/js-context/functions/types/_multifunc.js) for our current implementation of that.

**Comment by nokome** [comment]
Thinking some more about how Mini function definitions would actually be defined...

A user defined R function like this

```
myfunc = function r(x:int, y:int):int
return x + y
```

Could be implemented as a Mini function in Javascript as:

```js
const myfunc = {
  name: 'myfunc',
  inputs: [
    {
      name: 'x',
      type: 'int'
    },{
      name: 'y',
      type: 'int'
    },
  ],
  output: {
    type: 'int'
  },
  language: 'r',
  code: 'return x + y'
}
```

A builtin Mini function with some additional documentation could look something like:

```js
const sum = {
  name: 'sum',
  description: 'Adds up some numbers',
  inputs: [
    {
      name: 'values',
      type: '[number]',
      description: 'The numbers to add up'
    }
  ],
  output: {
    type: 'number'
  },
  language: 'js',
  code: function(values) { return stdlib.sum(values) }
}
```

**Comment by nokome** [comment]
Another proposal for moving ahead with this...

We should treat functions just like other parts of the platform and make them "first class citizens" just like `Documents` and `Sheets`. We would define a `Function` data model using an XML schema (as we are doing for `Sheets`, and will do for `Documents`) and UI components that would allow editing of functions as standalone entities along the lines of what @michael proposed [here](https://medium.com/@_mql/reproducible-science-for-people-who-dont-code-5850abe806db).

In the short term, I don't think we should do any UI for `Functions` and instead just focus on:

- defining a data model
- wrapping existing Javascript functions (e.g. from stdlib) to quickly establish functionality in Mini (although we should be careful not to rush naming!). 
- we might also want to wrap some functions in R and Python to test generality of the data model

In the longer term, we can add UI Components allowing users to do basic CRUD on `Functions`.

1.5 years ago (around January 2016 :open_mouth:) we put a fair bit of thought into functions - and were moving towards making them first class citizens - both user defined functions and reflection of existing functions. See discussion at https://github.com/stencila/stencila/issues/96. We don't need to be bound by this prior work, but some of it could be useful for avoiding reinventing our own wheels :):

- We were calling user defined functions "snippets" and developed a schema for that: https://github.com/stencila/stencila/blob/d5b2bd50dfd9ffe8da4d2ffcd900a3c3506e2d27/snippets/schema.json

- We had a class in the `RContext` which extracted a function spec from the builtin documentation so it could be passed to the UI as a JSON object: https://github.com/stencila/stencila/blob/d5b2bd50dfd9ffe8da4d2ffcd900a3c3506e2d27/r/stencila/function.R

- We had a UI component for providing function tool tips, ala Google Sheets:
https://github.com/stencila/stencila/blob/d5b2bd50dfd9ffe8da4d2ffcd900a3c3506e2d27/web/sheet/ui/FunctionComponent.js

![c8b8a5fe-c0a0-11e5-9928-742660a16c3a](https://user-images.githubusercontent.com/1152336/29898519-3c30dd9a-8e3a-11e7-99bf-81a9c041133f.gif)

@michael and @oliver---- : I think we all agreed this issue should be a high priority (it's needed to be able to do anything useful with sheets!) and it's something that could be developed in parallel to the ongoing work on the sheets UI. Let me know you thoughts and we can coordinate on who will do what, when.

**Comment by nokome** [comment]
Also of relevance is https://github.com/stencila/stencila/issues/172 regarding our previous approach to implementing Excel functions using R and which provides a list of the most commonly used Excel functions.

**Comment by oliver----** [comment]
Closing this, because we take a totally different approach (#351)  than proposed here.
