### ISSUE TITLE
Execution engine should indicate which inputs have changed

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#318]
Currently, the execution engine determines whether a cell needs to be re-executed depending on whether any of its inputs, or it's code, have changed. When re-executing a cell it sends any inputs to the execution engine in an object e.g. `{ "data": {"type": "table", "format": "json", ...}`. That is inefficient if a large input, say a large data table, hasn't changed. For example, consider a SQL cell:

```
filtered_data = sql(data)
SELECT * FROM data WHERE x<10
```
Any time that the code is changed, the variable `data` is resent to the `SQLiteContext` (and converted into the database table `data`). Instead, the execution context could cache cell inputs and the execution engine could just send inputs that had changed.

This would require changes to the execution engine and to the execution contexts .

Note that this issue is orthogonal to #317 - "pointer" types would still require fetching of data between execution contexts even if there had been no change to them.

**Comment by oliver----** [comment]
I think this is obsolete, or solved appropriately now.

Reopen if you think this is not correct.

**Comment by nokome** [comment]
I don't think this is solved yet. There is still transfer of (potentially large) inputs from the client to the execution context even if those inputs don't change (ie. only the cell code changes). But contrary to what I said above, I think this is best solved, at least initially, via pointers. So happy to keep this closed.
