### ISSUE TITLE
Preparing DataTables

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#323]
There needs to be some foundation for working on DataTables.

- Data Model
- Basic UI setup

**Comment by nokome** [comment]
@oliver---- : I had a go at starting a schema in #324. Really just an initial try by me - feel free to modify it as  needed.

**Comment by oliver----** [comment]
What do you think about using ODF 1.2 tables?

**Comment by nokome** [comment]
Sure, if it's suitable. I was thinking that the ODF spreadsheet spec wouldn't be suitable because it doesn't have a strict tabular structure with field types etc (?). But maybe the ODF database spec includes something we could use. BTW, a RNG schema is available here: http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-schema.rng

**Comment by oliver----** [comment]
@nokome not sure. Currently I have the feeling, that we could be faster with just using a custom model.
I will meditate over your proposed RNG 😄

**Comment by oliver----** [comment]
Looking at the schema, I don't think it is a good idea to go down this route.
I would recommend to look at data-tables as sheets with restrictions. The whole RDF thing and the relational schema is for maintaining data sources. This would be an enormous detour from our original track.

**Comment by nokome** [comment]
@oliver---- : thanks for having a look at that.

Re using ODF 1.2 tables: I agree. They are too different a use case and trying to make them fit Datables would be more effort than it is worth. Yes, I think we should use a custom model.

Re the proposed custom schema in https://github.com/stencila/stencila/pull/324. Let's move the discussion regarding that over there so we can get more specific about the bits that we like and don't like. I'm not sure what you mean by the "RDF thing" (I know RDF is but I can't see where it comes into that schema). I agree that the relational aspect of that schema (`<element name="primaryKey">` and `<element name="foreignKeys">`) should be dropped. I put them in for completeness/consistency with the Frictionless Table Schema spec as the starting point for these discussions but they go beyond the simple tabular data editor. 

I don't agree that  we should treat `Datatables` as `Sheets` "with restrictions" - at least not to the extent of having a shared XML schema. I think they are distinct enough to warrant separate schemas and I'm concerned that trying to tie them together in a shared schema would constrain both.

**Comment by oliver----** [comment]
We have finally come up with a decision how to approach this.

As discussed in #324 we go for a Datatable implementation which is actually based on Sheets. For that it is necessary to allow typing in Sheets. The data model will consist of a set of data rows, plus column meta data (such as name, and type, etc.). Datatables are strictly typed Sheets, i.e. cells must adhere to the column type -- whereas in Sheets, the column data-type is optional, and can be overridden for a single cell.

Technically we evaluated two approaches for rendering Sheets in HTML:
- `<table>`: has the advantage that many rendering features such as borders and spanning cells are built-in, but the draw-back that there are some constraints how cells are rendered regarding overflowing content
- `<div>`with flexbox: this has the advantage of giving full control over how cells are rendered, but there is no builtin mechanism for spanning and border collapsing

ATM we prefer the first, but we would be able to switch to the latter if we find ourselves blocked by the limitations.

Generally we will implement the rendering using a **viewport** starting at a specific row and column. This way we solve two challenges: layout of col/row headers must be the same as the data cells, and constant rendering complexity with large sheets/tables. I.e., when scrolling, the viewport is changed and re-rendered, which happens in the same time no matter how large the table is.
