### ISSUE TITLE
Better print to PDF in browser

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#332]
One of the most requested features is the ability to print a document to PDF. Currently, printing to PDF produces a single page with poor rendering of some elements (e.g. cells).

We need to add a print stylesheet with `@media print` rules to give better results. In the first instance this will be available to users using open.stenci.la e.g. via the R package. Eventually, we'll add a Print menu item to Stencila Desktop.

@michael : I've assigned myself to this and aim to have it done by 4 Sep. But feel free to chip in if you have ideas about how best to approach this.

**Comment by michael** [comment]
I think we should not invest a lot of time into this now, as we will throw it away again soon. When we approach the Reproducible Document Stack project we will be able to generate a static HTML version of a document, without all the UI elements (toolbars etc.). This will then look ok when printed via the web browser print dialog. However ultimately we may want a proper printing solution with proper typesetting e.g. through LaTeX but that is a whole project on it's own.

**Comment by nokome** [comment]
Thanks, I'm hoping this will be fairly quick - not aiming for perfect print results at this point - just the ability for authors (in this particular use case, university students) to be able to easily save their work when in the browser (not in the desktop).

Not sure that we will throw it away - I suspect authors using Stencila in the browser (e.g in this context https://community.stenci.la/t/development-update-r-package-get-rstudio-integration-and-sql-execution-context) will still expect to get reasonable results from printing via the browser dialog, even though there might be better server-side PDF generation.
