### ISSUE TITLE
Basic Sheet Editing: Overwriting a cell via typing

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#338]
![stencila-sheet-type-over](https://user-images.githubusercontent.com/284099/30217107-701cd15a-94b5-11e7-984c-a7b4255f46bb.gif)

**Comment by nokome** [comment]
+1 for this. Currently to enter data a column of data `1, 2, 3` you need to type `Enter, 1, Enter, Enter, 2, Enter, Enter, 3, Enter` whereas in Excel etc it would be `1, Enter, 2, Enter, 3, Enter`

**Comment by michael** [comment]
Working now
