### ISSUE TITLE
Basic Sheet Editing: Select All

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#345]
There are two stages for selecting cells via `CMD/CTRL+A`:
- the first time, the selection is expanded locally to form a rectangular hull of all *connected* cells (whatever this means) that can be reached from the `anchor`

![stencila-sheet-select-all-1](https://user-images.githubusercontent.com/284099/30219496-7f48addc-94bc-11e7-824a-6cf733307657.gif)

- the second time literally all rows and columns are selected

![stencila-sheet-select-all-2](https://user-images.githubusercontent.com/284099/30219340-0fb7c8cc-94bc-11e7-9a1e-a00597867ffb.gif)

**Comment by nokome** [comment]
Currently `Ctrl+A` selects the entire sheet. I think that is OK for now. We can implement the two-stage select all later. @oliver----  can I close this and thus #337.
