### ISSUE TITLE
Sheet UI

### ISSUE THREAD

**Issue by michael** [stencila/stencila#363]
Attempt to define complete UI for Sheet editor.

![image](https://user-images.githubusercontent.com/2931/31386282-8a6c09d4-adc6-11e7-87d4-370069f0310f.png)

Elements:

- Paint Format/Types: We use it to transfer cell types and units, not for transferring styles.
- Suggestion: Always show the cell type and unit (takes up 2 lines in the column headers)
- View: Let's you toggle between source and display mode
- Linter View: a panel docked at the bottom of the screen, can toggled on and off, clicking on an item takes you to erroneous cell

Not covered:

- Ability to inspect cell type (when column type is overridden), we will be able to access that via context menu, but maybe we want some indicator in the toolbar (e.g. when a single cell is selected to display "Number (EUR)"

**Comment by nokome** [comment]
Looks good! Some comments:

- re types and units. I was thinking about this yesterday with regard to dealing with categorical data. I'm leaning towards *not* having two separate concepts, and instead extending the type hierarchy - e.g. `EUR` and `USD` are subtypes of `currency` which is a subtype of `number`. I think we can get the same benefits of "units" without having to introduce another concept. Eventually, users will be able to contribute custom types e.g. `nucleotide` which is derived from `string` and can only have values `A, T, C, G`

- Paint Format/Types: while I can see this may be necessary in the long term, I'm wondering if we should keep it out for now - it's a convenience feature we can be achieved by manually selecting type of the column - and I think we need to avoid the painting icon to avoid confusion with format painting

- re column headers: my preference is to have a single line with an icon for the type. The icon takes up less room but also reduces confusion between the name of the type and the name of the column. Also, if the column is named then the capital letter alias e.g. `A` should go grey to indicate it is the least preferred name for the column.

- re warnings: I think they are needed as well as errors for things that the linter picks up which may not necessarily be errors (e.g. a formula `= sum(A1:A9)` that misses the adjacent data cell `A10` like excel does also we might want linter "suggestions" like "this column only numbers in it; we recommend changing it's type from `auto` to `number`"

- the linter should also report on test failiures (forumla cells that have been tagged as 'test' cells and which return true/false)

- to the left of the linter messages (or as part of a linter toggler) it would be good to have a small panel with "scores": % of cells with warnings, with errors, with test failiures, % of cells covered by tests

**Comment by michael** [comment]
Updated mockup with compact column headers.

![image](https://user-images.githubusercontent.com/2931/31660920-4a5de074-b339-11e7-8a21-5f92fb00ecfd.png)

**Comment by nokome** [comment]
Closing this as it is now outdated.
