### ISSUE TITLE
Type checking for Mini expressions

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#411]
- `plus`: should add numbers, and call `libcore.concat()` for other types
- `minus`, `mult`, `divide`, and `pow`: only for numeric types, and error otherwise

**Comment by nokome** [comment]
Closing this because over in the `stencila/mini` repo we are unifying operators and function calls; https://github.com/stencila/mini/pull/18. So this will be dealt with by the usual dynamic type checking at the point function call.
