### ISSUE TITLE
Resizing a column does not re-render plot cells

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#413]
A sheet cell with a plot in it e.g. `=plot([1,2],[3,4])` does not get re-rendered when the column width is adjusted, until you scroll it out, and then back into, the viewport:

![peek 2017-10-23 10-05](https://user-images.githubusercontent.com/1152336/31878342-111dc8f6-b7da-11e7-98a2-fafd460cc735.gif)

**Comment by Integral** [comment]
Fixed via #419.
