### ISSUE TITLE
Idea: Less obtrusive errors

### ISSUE THREAD

**Issue by michael** [stencila/stencila#416]
In order to not have errors pop up all the time during editing we could do the following:

- underline the erroneous code bit (error annotation)
- when you have the cursor inside the error anno
   - pressing ctrl + space reveals the error (esc hides it again)
   - alternatively: right click shows the error in a context menu (cmp. spell checking)

**Comment by nokome** [comment]
@michael : is this issue still relevant? I seem to recall that you took a different approach.

**Comment by nokome** [comment]
The https://github.com/stencila/mini/pull/20 PR is related - it reduces the number of error messages generated while the user is still completing an expression.
