### ISSUE TITLE
Basic Sheet Editing: typing over does not work after confirm with ENTER

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#425]
- ENTER cell
- ENTER to confirm (moves selection to next cell)
- Then typing does not open the cell editor

**Comment by Integral** [comment]
@oliver---- can't reproduce this issue in develop branch. Are you sure?

**Comment by oliver----** [comment]
Let me check...

**Comment by oliver----** [comment]
you are right.
Seems to be working now.

**Comment by oliver----** [comment]
Thx

**Comment by Integral** [comment]
welks
