### ISSUE TITLE
MiniContext

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#428]
The binary operator `*` seems to have precedence over the operator `/` - they should have equal precedence i.e left to right. The following test fails, it returns 0.25 = `1/(2*2)` when it should be 1 = `(1/2)*2`:

```
test('MiniContext: 1/2*2', t => {
  let c = setupContextWithFunctions()
  c.executeCode('1/2*2').then((res) => {
    let val = res.value
    t.equal(val.data, 1, 'value should be correct')
    t.end()
  })
})
```

**Comment by oliver----** [comment]
You were right. 
I have conflated expressions with same precedence.

Fixed via ed4dff6c2136a1eaf6bdd8eed30d82fa6318cab3
