### ISSUE TITLE
Support cite work by title or author's name

### ISSUE THREAD

**Issue by rgaiacs** [stencila/stencila#436]
[BibLaTeX](http://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) has some commands that make easy for writers to cite a work using the title (`\citetitle`) and author's name (`\citeauthor`). Would be great if Stencila has something similar.

# Current behaviour

In http://builds.stenci.la/stencila/ensure-an-array-for-each-type-2017-10-27-be9e9e5/examples/article/index.html?example=external-cells we can insert a citation and select the work to be used.

![screenshot from 2017-11-02 14-12-34](https://user-images.githubusercontent.com/1506457/32330703-ca09c1d4-bfd8-11e7-8c2c-ae20646eeb24.png)

# User Interface Improvement Proposal

At the top of the pop up box, the user can select if Stencila is going to use the default reference style (number, APA, ...) or use work title or author's name.

![stencila](https://user-images.githubusercontent.com/1506457/32331036-bb06b2e0-bfd9-11e7-92c3-a2d8cb7470bd.png)

**Comment by nokome** [comment]
Thanks for the feedback @rgaiacs! I agree that we should allow authors to see citations using styles other than numbers. I personally prefer to use the APA style in-text citations e.g (Jones, 1998) because it's a much easier way to see whom you cited where.

Instead of being able to set the style for each citation, I wonder if this should be a document level setting? It would be very unusual to use different citation styles in different parts of the document. Would a document level "citation style" setting work for you?

**Comment by rgaiacs** [comment]
>  I agree that we should allow authors to see citations using styles other than numbers.

This is a different feature.

> Instead of being able to set the style for each citation, I wonder if this should be a document level setting?

A document level setting will solve the (other) problem: support different citation styles.

What I would like is the ability to access the title or author of a work and include it in the text without typing it and with automatically update if the work change.

# User case

I'm using the tool X for my work and I want to cite it (e.g. IPython Notebook) so in LaTeX (with BibLaTeX) I could write

```
using \citetitle{IPython} was ...
```

and I would end up with

> using IPython Notebook was ...

At the time of the publication, the tool X was re-branded to Y so in LaTeX (with BibLaTeX) I could keep my `.tex` file unchanged, change only the `.bib` and the output would have

> Using Jupyter Notebook was ...

**Comment by nokome** [comment]
Ah, OK, I see the difference now. Sorry for the confusion.

We'll be doing a prioritization of features, including this one, in a couple of weeks.
