### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by remram44** [stencila/stencila#439]
I'm using the `&peers=http://localhost:2000` trick from your [getting started guide](https://community.stenci.la/t/getting-started-with-stencila/47), however it doesn't work. The client can't connect to the peer/server/docker container because of a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) error (Chrome dev console says: `Failed to load http://localhost:2100/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://builds.stenci.la' is therefore not allowed access.`).

You'll need to add the header to the replies from the "peer" process that runs in the Docker image.

**Comment by nokome** [comment]
Thanks for filing this @remram44 . I actually fixed this a few weeks ago:: https://github.com/stencila/node/commit/f6b3d010cca41ab6c45906090f67e6f03d528cde but that change hasn't made it into the `stencila/alpha:latest` image yet. To use `http://builds.stenci.la/...&peers=http://localhost:2100` you have to run the `0.29-preview` version:

```
docker run -p 2100:2000 stencila/alpha:0.29-preview
```
Nonetheless, I need to do some tidyups of docs...
