### ISSUE TITLE
Function tooltip and help panel

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#440]
Function tooltip should have a minimize/maximize button and a link to a help panel which displays function documentation. Similar to how Google sheets to it:

![peek-2017-11-12 22-35](https://user-images.githubusercontent.com/1152336/32712645-8c7034d2-c7fa-11e7-83d3-5c42e59e4e16.gif)

**Comment by michael** [comment]
Needs to be improved but first iteration done.
