### ISSUE TITLE
Mouse based selection of cell or cell range in cell expressions

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#442]
Currently when writing an expression in a sheet cell, it is necessary to type in cell ranges e.g A1:A10. It should be possible to use the mouse to insert cell ranges.

![peek-2017-11-12 22-57](https://user-images.githubusercontent.com/1152336/32713189-faca73a0-c7fc-11e7-9a88-e68ec01421d8.gif)

**Comment by michael** [comment]
First iteration done.
