### ISSUE TITLE
Discuss: Reactive Programming in Sheets

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#451]
I am about to summarize our discussions and write technical specifications for the 'Cell-Editor' topic.

Sheets are currently less reactive than Documents. 
While we do not want to change the Enter/Confirm pattern for editing cells, 
there is the desire to see the preliminary result of the evaluation in a reactive way.

There are two ways of doing it:
- Cell Preview
- Complete Propagation with preliminary expression

A preview requires a means to evaluate a detached expression (only inputs, no impact on other cells).
The latter requires to update the engine with the preliminary expression, and re-evaluating the cell when confirmed or cancelled. 
Both is technically possible, the first probably a bit easier.

What is your opinion?

~~~Now I want to make sure that we really are clear that a non-reactive, enter-confirm UX pattern is what we want in Sheets. Or is there a possibility that user's could like a reactive pattern, despite technical internal problems?~~~

**Comment by oliver----** [comment]
IMO, a strong argument for the non-reactive pattern is that it is common in Sheet interfaces.

**Comment by oliver----** [comment]
Maybe we should open a question in the forum and try to get feedback?

**Comment by oliver----** [comment]
There is another aspect related to this: Undo/Redo.
In a confirm/edit, undos are bound to the time the user is editing a cell. Global undos are reverting the whole change of a cell.
In a reactive version, undos would be on keystroke level.

**Comment by oliver----** [comment]
ping @nokome @michael @Integral

**Comment by nokome** [comment]
> Or is there a possibility that user's could like a reactive pattern

I think this is a definite possibility and IMO the argument that it's not reactive in other interfaces is not that strong.

One option is to have reactive expression editing in the formula bar and 'update on enter' in cells ( where you can't see cells output anyway). Not necessary advocating for that (yet), just noting it as an option.

**Comment by oliver----** [comment]
We have been playing through the idea of a reactive UX as we do in documents.
There are two aspects here, the reactiveness of the evaluation and the granularity of changes.

There are some common interactions in sheets (cancel change, type over a cell) which are not typical in the document. E.g. you can not cancel a change to a paragraph, but use undo. You need to delete and insert in order to replace the content of a paragraph.  From that point-of-view we would rather prefer to stick with the current model, i.e. having a detached editor, updating the model on blur or confirm.

Still there is room to increase reactiveness of the evaluation in the existing approach. 
Changing the title to reflect this change in the question.

**Comment by michael** [comment]
What we could do to have a more reactive feel is show a preview of the computed value while editing an expression (like Google Sheets does). This would mean that you see the output of that cell, but without triggering updates to dependent cells until you confirmed your changes with ENTER.

**Comment by oliver----** [comment]
Added this to the description.

**Comment by oliver----** [comment]
I would opt for the Preview, because it is technically easier, and kind of a requirement anyways.

**Comment by Integral** [comment]
Good idea, could you maybe sketch it? Visually.

**Comment by Integral** [comment]
Not sure that cell editor could be reactive thing... Just can't imagine
what are you talking about. I think there are also some user expectations
regarding enter button and navigation

**Comment by oliver----** [comment]
Reactiveness means here that a cell is evaluated immediately when you change it. In the document this is the case already. In sheets, as we edit the cell in a detached editor, i.e. it is not changing the model directly, you see the updated  evaluation only when leaving the cell editor. This is not reactive.
We were discussing how much reactiveness is actually desired.
Michael opted from the beginning for a Preview evaluation. I.e. not the whole sheet is evaluated while you edit a cell, just the value for the cell is shown.
Still it is technically also possible to propagate that change through the whole sheet. While being more reactive, this increases more noise, and it is not consistent with the actual changes to the model (which are done on confirm/blur).

**Comment by oliver----** [comment]
Let's go for the Preview.

**Comment by redbar0n** [comment]
Hi, coming from Google Sheets here, and discovered Stencil while searching for reactive spreadsheets that would especially allow reactivity long-running custom functions. That was the reason Stencil looked interesting/unique, so I would encourage to keep investing in this feature. Pardon for any ignorance about Stencil's current abilities, as I just briefly skimmed the landing page and found this issue.

I would suggest a third option for reactivity, that you might want to keep in mind for future improvements to the reactivity:

3. While editing a cell, do not evaluate whole sheet reactively. But after there are changes to the cell model, done on confirm/blur, _then_ start to propagate changes throughout the whole sheet. That would help with long-running custom functions. If a custom function takes 30 sec to complete (e.g. like finding the MAX in a very very long list), the user would like to have the first available answer as soon as possible, but to have it change reactively (e.g. when a higher MAX is found). The cell with the custom function should probably have some slightly highlighted frame or something, indicating that it has updated reactively.
