### ISSUE TITLE
Discuss: Stencila Tests

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#457]
Currently we have implemented tests using regular cells that return a value of a specific type 'test'.

From #445 we have this requirement:
> This is a somewhat different topic, but related to how test fails are recorded in the issue panel. Instead of having separate test cells it would probably be better to have tests as cell attributes. For example, currently, if I had 10 cols x 1000 rows of cells that I wanted to apply the same test to, I would have to create 10 cols x 1000 rows of test cells. Instead, if tests were an attribute of cells, then I could create a test and apply it to all those cells. This is also related to having tests defined to each type e.g. a "human height" type might have tests to check value greater than 0 and less then 3m (ie. types have tests and cells can have additional custom tests).

This means, it is desired that a test is not just a cell itself, but something that is applied to one or multiple cells. This changes the nature of a test in Stencila.

Trying to develop a definition so we better understand what we want:

```
A test is defined as an expression and a set of cells that the test is applied on.
Whenever one of the cells has been (re-)computed, the expression is evaluated.
The expression is a lambda expression, evaluating to a result that is 
captured as a test result.
```

Example:
```
cells: C1:C10,
language: js,
source:  assert(value > 0, 'The value should be greater zero.')
```

**Comment by oliver----** [comment]
@nokome Need your help here

**Comment by oliver----** [comment]
The same approach could be applied for 'conditional formatting'. The result would be mapped to cell a state, that could change the visual appearance of a cell.

**Comment by oliver----** [comment]
@nokome what is your opinion

**Comment by oliver----** [comment]
Feeling more and more confident about this.
G-Spreadsheets have something similar (Data validation and Conditional Formatting) defined visually.

**Comment by nokome** [comment]
Hey @oliver---- : thanks, yes my thinking is very much aligned to this (I have something that looks very similar to the above example scribbled down on some paper :smile: ).

See https://github.com/stencila/stencila/issues/97 re conditional formatting

Related to this, I've been doing some thinking about type hierarchies and defining types in the libraries e.g. `libcore`, `libecons` etc. Essentially defining each type based on a set of assertions. I'll draft a StEP for it as soon as I can!

**Comment by oliver----** [comment]
What about ?
```
cells: "C1:C10",
language: "mini",
assertion:  "value > 0", -> boolean expression
message: "The value should be greater zero."
```

**Comment by oliver----** [comment]
A slightly different model using XML:
```
<tests>
  <test>
    <cells>A1:B10</cells>
    <assertion message="Value should be greater zero" test="value > 0" language="mini"/>
  </test>
</tests>
```
This would allow 1. for multiple cell ranges, 2. multiple assertions. (I suppose @michael would like to keep it simple UX wise)
