### ISSUE TITLE
StEP: Guideline for writing a StEP

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#460]
There should be a blue-print for a StEP so that is understood what a StEP should be:

Proposal:
- Introduction: provide an informal context and motivation
- Definitions: provide terms used in Stencila
- Concepts: explain concepts and rationale
- [Distinction]: if necessary position to existing solutions
- Examples
- Implementation: links to specifications etc.

**Comment by oliver----** [comment]
@nokome you certainly have something to add :)

**Comment by nokome** [comment]
Thanks, good suggestions. Will leave @daniellecrobinson to have a first go at this tomorrow.
