### ISSUE TITLE
StEP: yml header does not look nice on github

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#461]
![image](https://user-images.githubusercontent.com/284099/33749429-ff0c0610-dbcd-11e7-8d2f-71fb5b9be686.png)

**Comment by nokome** [comment]
This was due to missing YAML delimiters at the top of the file. Fixed in 2d9477d8cf60881146699cc1819336dd0956bd70

If folks don't like YAML headers we could easily drop them - right now we don't need machine readability of the headers.
