### ISSUE TITLE
Allow entering a cell that is off-screen

### ISSUE THREAD

**Issue by michael** [stencila/stencila#466]
Currently if the anchor cell is off screen, FormulaEditor does not get a position and will be rendered at pos 0,0.

What we probably want here, is to first scroll the selection into place, then open the editor.

**Comment by oliver----** [comment]
This seems to better now:
- In general the sheet scrolls to the focused cell e.g. when selection changes via undo/redo
- clicking into the formula bar, does not show the hovering formula editor, which feels ok
