### ISSUE TITLE
Allow cross document cell references in cell engine

### ISSUE THREAD

**Issue by michael** [stencila/stencila#491]
E.g. `=plot(doc1.data)` or `plot(sheet1.A1:B5)`

**Comment by michael** [comment]
Let's use ids for now that qualify as variables. Just as a first iteration. Since ids should not change we need to introduce aliases soon e.g. a name per document.

**Comment by oliver----** [comment]
A first iteration has been done via #514.
As opposed to the proposal, I have used the notation known from Excel (`sheet1!A1:B10`).
