### ISSUE TITLE
Make a website update

### ISSUE THREAD

**Issue by michael** [stencila/stencila#494]
I think it is very important to rework the website, and we should start the discussion soon.

The goal of a new website should be:

- Introduce Stencila and emphasis its strengths
- Provide previews (examples for people to try out)
- Make clear Stencila is a community effort and invite people to discuss new features and prototypes (not just a link to the forum but a call to action paragraph on the website)

I also think we should stop announcing versions or have a roadmap of ready-to-use releases. I'd rather communicate that we do regular previews, where we ask for feedback. We are already doing this but we should communicate it on the website. 

I'd recommend to remove the current Desktop app download from the webpage, and instead fill the startpage with an introduction.

Let's discuss this more in one of our next calls. I think it's really important to get this right early in the year, so we can start talking about Stencila online.

**Comment by michael** [comment]
Regarding versioning. I think people are confused with Stencila versions. Maybe we should leave the 0.x phase behind and start announcing previews. Like let's say end of January we could announce "Stencila Preview 1" together with a call for feedback and user testing?

**Comment by nokome** [comment]
Yes, this needs attention soon. I am planning on revising the website early in the new year to be ready for the third week of January. Things like screenshots of good examples and links to documentation that we're also working on need to be done as part of this and will take some time.

As part of this we need to improve the messaging around versioning and what and when parts are ready to use. In what way do you think people are confused about the current versioning? I'm personally not keen to start labelling releases as "preview" (feels like that could go on for a long time) but would rather make it clearer, including within interface, that Stencila is in "beta" and return to more of a "release early and often" strategy. This may mean that we remove features that are not ready e.g. IssueManager and only add them in when they are ready and as part of a release.

**Comment by apawlik** [comment]
I will move these comments to the `website` repo and close this issue here
