### ISSUE TITLE
Array values are not recognised in Mini

### ISSUE THREAD

**Issue by michael** [stencila/stencila#510]
![image](https://user-images.githubusercontent.com/2931/35349205-952d2d72-013a-11e8-9126-b784f98d05b2.png)

When I switch to Javascript:

![image](https://user-images.githubusercontent.com/2931/35349229-a48ca75c-013a-11e8-86c5-b7fec8c612b6.png)

**Comment by oliver----** [comment]
It seems that there is a bug in the marshalling done in MiniContext.

**Comment by oliver----** [comment]
This is working now.
