### ISSUE TITLE
Syntax for grouped bar chart

### ISSUE THREAD

**Issue by michael** [stencila/stencila#515]
Tried to replicate a common use case (grouped bars) to our Mini plot functions.

Original:

![image](https://user-images.githubusercontent.com/2931/35508607-45b48104-04f1-11e8-9e23-b6be068a6124.png)

![image](https://user-images.githubusercontent.com/2931/35508596-3986bdac-04f1-11e8-9f2c-86022a21f820.png)

Proposal:

```js
data = table({
  animal: ['giraffe', 'orangutan', 'monkey'],
  sf: [20, 14,23],
  la: [12, 18, 29]
})

trace1 = dtrace(data, x='animal', y: 'sf_zoo', yLabel: 'SF Zoo')
trace2 = dtrace(data, x='species', y: 'la_zoo', yLabel: 'LA Zoo')

bars([trace1, trace2])
```

Maybe it's a good idea to piggy back on Plot.lys approach, as it's alraedy well documented and then we don't need to come up with another syntax nobody is familiar with.

**Comment by michael** [comment]
@nokome to be able to cover certain basic use-cases for plotting we should find a way to expose the whole Plot.ly functionality in a generic way. W can still experiment with better syntaxes for plotting but I'd love to have a 

plotly() function in mini, that I can according to the plotly API. What do you think? Is it hard to implement that?

**Comment by nokome** [comment]
@michael : this is a great idea! It would allow us to get a lot of plotly functionality quickly, let people use a pure plotly syntax if they like, and give us time design a  family of Mini `plot` functions we all like.

**Comment by nokome** [comment]
Closing in favour of https://github.com/stencila/libcore/issues/19
