### ISSUE TITLE
Variables aren't propagated properly when fixing an error in the generating cell

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#516]
Just look at this:
![](http://g.recordit.co/NJFNklM63A.gif)

So what's happening there?
I've got two variables with 3d arrays (x,y,z), when I add one more dimension table function returns error because it can't build a table of arrays with different dimensions. But if remove one dimension - nothing will happen. Visually table cell got executed, but actually the error will gone only if you update cell with table definition, you can just add one space and it will recompute cell properly.

**Comment by michael** [comment]
That's an issue with cell update propagation, we discovered that when preparing for the webinar. Good you tracked it in an issue! We'll work on a fix in the coming days.

**Comment by oliver----** [comment]
This is working now.
