### ISSUE TITLE
Don't allow references and other annotations inside of code cells

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#519]
Do we really want it?
<img width="824" alt="screen shot 2018-02-07 at 01 32 13" src="https://user-images.githubusercontent.com/182010/35887870-ca802c38-0ba6-11e8-9f69-f3c872cc7925.png">

**Comment by oliver----** [comment]
@Integral what exactly is happening here?

**Comment by Integral** [comment]
It is citation and other references inside code cell. You can insert it there. I think that these tools should be deactivated inside code editor.

**Comment by oliver----** [comment]
Right.

**Comment by Integral** [comment]
@oliver---- This is actually much more interesting. You can insert xref annotation via tool, but if you paste it will tell you that `<xref> is not valid in <source-code>`. Is it interesting for you?

**Comment by michael** [comment]
Fixed via https://github.com/substance/substance/pull/1160
