### ISSUE TITLE
Can't move cursor out of cell editor in reproducible figure

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#522]
![](http://g.recordit.co/2U0flWdugu.gif)
Usually you can navigate using up/down keys within document. If you enter cell editor you can still use left/right for navigation inside editor and up/down will help you to leave editor.
If you put the cursor inside cell editor in repro-fig, you will not be able to use up/down. Even more: if you put cursor in regular cell editor you will also not be able to use up/down to leave editor. It will only put the cursor in the beginning or end of code. Thought everything comes back to normal state if you put the cursor just inside paragraph.

**Comment by michael** [comment]
Again, this is because of repro-fig being an isolated node. It's not part of the text flow.

**Comment by oliver----** [comment]
We should consider to 'open' isolated nodes such as figures, and make this work better (e.g. fixing #523)
