### ISSUE TITLE
Can't remove selection if it's ending/starting inside code editor

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#523]
This one for instance:
<img width="826" alt="screen shot 2018-02-07 at 02 39 17" src="https://user-images.githubusercontent.com/182010/35890286-1e60a72a-0bb0-11e8-9c99-b83094158faa.png">
It will error with `coordinates are within two different surfaces. Can not create a selection.`
It might be worth... If there is something, say a repro-fig as in screenshot, it's hard to remove those lines... You can't put cell inside selection. Only using arrow-shift combination.

**Comment by oliver----** [comment]
This is something we should work on: because cells are 'open' isolated nodes, it is possible to partially select inside it.
We should detect these 'mixed' selections and treat cells like regular isolated nodes.
