### ISSUE TITLE
Copy cell

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#524]
It's really hard to copy cell. You can't select it. Only code inside (which will be copied as a text) or cell and piece of next and prev paras.

**Comment by michael** [comment]
You need a node selection. Press ESC or toggle the ellipsis menu, then ctrl + c and it should work.

**Comment by oliver----** [comment]
There are two ways to select a cell: `ESC` or clicking on the ellipses icon.

**Comment by oliver----** [comment]
Closing this, because it is more a UX problem with selecting cells, than a copy'n'paste problem.
