### ISSUE TITLE
Work towards a kiosk-ish landing page for Stencila demos

### ISSUE THREAD

**Issue by michael** [stencila/stencila#530]
Having alpha.stenci.la is a nice way to let curious users have a play with Stencila.

However I think, we should try to move towards more user-friendly tutorials. Compared to what Observable does our landing page looks techy and a bit scary to new users. Could we do something similar?

https://beta.observablehq.com/collection/introduction

We still keep the tech examples but not expose them on the landing page and only use them for development and presentations when needed.

**Comment by nokome** [comment]
Yes, `alpha.stenci.la` is intended to only have a lifespan of a few weeks and not for widespread use. We will reinstate and refresh a lot of the functionality that we had in https://github.com/stencila/hub circa 2016 with a landing page of examples, user login etc and a deploy it as `beta.stenci.la`. That will be the topic of a sprint we're doing next week (with @finlay @richardmansfield, @hamishmack). So an initial version should be ready within two to three weeks.
