### ISSUE TITLE
Delay processing of cells while typing

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#534]
At the moment, while editing a cell, errors are displayed too eagerly.
It is natural that the code is not correct while it is edited.
Thus, the engine should analyse and evaluate a cell only when the user is idle.

**Comment by nokome** [comment]
Agree that a small amount of idle before `analyseCode` or `executeCode` is appropriate but too much could be laggy. In addition to this idle, I suggest an idle in the *display* of syntax errors. ie. `analyseCode` could be done without delay (or with small idle) but any syntax errors only get displayed if idle for a while (i.e. user has finished typing).

**Comment by Integral** [comment]
@nokome, take a look at #623.
![](http://g.recordit.co/5SDvz2kvxL.gif)
