### ISSUE TITLE
Allow selection of graphs/tables

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#537]
While we didn't finish with embeddable things like graphs, current implementation lacks graph selection.
When I'm click on graph or table I'd love to select it visually. Currently you have to navigate to top left cell behind graph via arrows to edit formula and graph didn't got selected. My proposal would be to set selection visually on undocked figure and activate cell editor on figure click.

**Comment by nokome** [comment]
+1 for this.

**Comment by michael** [comment]
This is important to work on. E.g. double click on the image should open the cell editor.

**Comment by Integral** [comment]
@michael there are number of problems here.
First of all we should somehow understand if given cell is of overflowed type (let's give this name for our undocked tables and graphs). Without understanding that we can only analyse selection [during bounding rect computation](https://github.com/stencila/stencila/blob/develop/src/sheet/SheetView.js#L146), e.g. searching for `.sc-cell-overflow` inside cell element. I would consider this approach as a hack.
Next problem we will have with z-index, as we want to render selection on top of overflowed figure and we don't want to do that for other cells, e.g. this is what we will see:
![screen shot 2018-02-13 at 01 38 33](https://user-images.githubusercontent.com/182010/36124035-b2169fca-105f-11e8-8054-79e1e32bcffb.png)
![screen shot 2018-02-13 at 01 38 42](https://user-images.githubusercontent.com/182010/36124036-b2330f84-105f-11e8-8c05-4c75a149233d.png)
So we will need to either change styles of selection, either using other selection type.

But what I thought... Maybe we just need to render selection inside cell? Just highlight overflowed cell with some border? Other selection would be still under figure, we will just need to toggle this highlighting, which is also could be tricky... What do you think?
