### ISSUE TITLE
Cell referencing bugs

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#541]
Don't wan't to spoil issue list too much, so I will left everything belonged to cell referencing here.

1. You can select a range with column header:
![](http://g.recordit.co/vqsK4Rv3sm.gif)

2. Afterwards you can do funny things like this (which isn't possible without column header reference):
![](http://g.recordit.co/sJJohIlI47.gif)

3. I think we shouldn't allow insertion of cell reference before `=` sign:
![](http://g.recordit.co/0CVjEPfn1Q.gif)

4. If you write smth like `=A1:B4` it will return table. If you write =A1:A4 it will return `[object Object]`

**Comment by michael** [comment]
@Integral can you take over the visual-referencing related bugs?

Number 4 is engine related. @oliver---- should we treat one dimensional ranges as arrays or rather tables with one column?

**Comment by Integral** [comment]
@michael could you please check #611?
I'm not sure about 3 (insertion of cell reference before = sign). It will not allow you to do that, but still will show you active range... Ideally we shouldn't show that as well...

**Comment by michael** [comment]
Thanks @Integral. This works better. Will merge this now, but we certainly need to tweak more. Also need some time testing and figure out what exact behaviour we want.
