### ISSUE TITLE
Improve styles of hosts dialog

### ISSUE THREAD

**Issue by michael** [stencila/stencila#555]
There's nested scrollbars and stuff, etc. Can we make this look just a bit nicer? ;)

![image](https://user-images.githubusercontent.com/2931/36100003-f74adb98-1004-11e8-8e0f-43b57a6c453f.png)

**Comment by michael** [comment]
Also, is the add hosts functionality already working?

@nokome what would I need to enter here, e.g. to use the public instance running at cloud.stenci.la?

**Comment by Integral** [comment]
You can add a host, yes

**Comment by Integral** [comment]
see #560

**Comment by michael** [comment]
Maybe you can add a placeholder into that input field to show what it should look like to add a new host URL:

**Comment by Integral** [comment]
Good point!
![screen shot 2018-02-13 at 14 14 48](https://user-images.githubusercontent.com/182010/36147200-5879cdc0-10c8-11e8-9bf9-eb20cad04724.png)
