### ISSUE TITLE
Make document tabs editable

### ISSUE THREAD

**Issue by michael** [stencila/stencila#572]
We need an ability to edit and delete document records (tabs). Also we should be able to reorder them with drag+drop.

@Integral can you do a first pass, and just enable a small input field when double clicking on a tab? 

![image](https://user-images.githubusercontent.com/2931/36218968-49db7b1c-11b6-11e8-97e9-236e9277b03d.png)

The delete button could in a drop down menu as done in Google Sheets.

![image](https://user-images.githubusercontent.com/2931/36218915-246c6170-11b6-11e8-83dd-9b9e160151f4.png)

Or maybe we display a small "x" right away. But then we would need an extra confirmation so you don't accidentally delete a document.

**Comment by Integral** [comment]
Nice! I will start tomorrow, thx!

**Comment by Integral** [comment]
Renaming and deletion are in `tabs-actions`, will try to work on dnd sorting tomorrow.

**Comment by michael** [comment]
Done via #585.
