### ISSUE TITLE
Shortcut for Heading 2 fails

### ISSUE THREAD

**Issue by ghost** [stencila/stencila#574]
Great tool!

When using the Ctrl+Alt+2 shortcut to format paragraphs into heading 2, I get back the symbol for quotes (I use a UK keyboard). Headings 1 and 3 work just fine.

Giulia

**Comment by michael** [comment]
Maybe we should consider using different keyboard bindings if they happen to collide with character inputs. What OS are you using?

You have a suggestion what keyboard shortcuts you prefer for changing heading levels?
