### ISSUE TITLE
X scrolling behaves strangely

### ISSUE THREAD

**Issue by Integral** [stencila/stencila#575]
Sorry for bad issue name, I will try to explain now, firstly look at image:
![](http://g.recordit.co/aP1Sm1yijY.gif)
Here you can see two attempts to scroll sheet horizontally.
At first I'm trying to drag scroll thumb from the very left edge. It is not working, you can see how I guide mouse to right edge.
During second attempt I'm start dragging few columns righter and it's starting to scroll viewport only after I moved cursor through half of screen size.

**Comment by michael** [comment]
It‘s a known issue, but thank you for tracking it.

**Comment by Integral** [comment]
always pleasure for me ;)
