### ISSUE TITLE
Cell language menu: disable menu items for languages not currently available

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#586]
Currently, if you select a language which is not available you get an error. It would be less confusing if the menu item for languages that are not available was greyed out.

![image](https://user-images.githubusercontent.com/1152336/36407657-fe90b11e-1664-11e8-83b9-b0396e196ae4.png)

**Comment by michael** [comment]
I'm not sure this is a good idea. You should be able to edit the full document, even if the contexts are not available. If I wanted to create an R cell in the train and host is tipsy, I should be able to do that.

We could maybe add a green or red light next to the menu items to indicate if the contexts are available.

**Comment by nokome** [comment]
@michael : yes, you are right, better to have an indicator on menu items rather than disabling them altogether.
