### ISSUE TITLE
Cell range selection only updating on backspace

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#587]
When in a cell, the outlined cell selection only shows on backspace:

![peek 2018-02-20 17-54](https://user-images.githubusercontent.com/1152336/36408042-b36c5f8c-1667-11e8-9ff0-0e1cf0fd1111.gif)

**Comment by michael** [comment]
@Integral can you reproduce this? I can't.

**Comment by oliver----** [comment]
This has been fixed via #673
