### ISSUE TITLE
Finalise Sheet Schema

### ISSUE THREAD

**Issue by michael** [stencila/stencila#589]
Aside from hunting bugs we should not forget to finalise the XML schema. Making changes to the schema will break existing documents, unless we introduce migrations (which is a burden I'd like to push until we have a good feel we got the spec right). 

So let's try to get to a close-to final official serialization format soon, so we won't break it right after the launch. Here's a proposal up for discussion:

### (1) Internal representation (currently = serialization format too)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sheet PUBLIC "SheetML 0.1.0" "http://stenci.la/SheetML-0.1.0.dtd">
<sheet>
  <meta>
    <columns>
      <col name="temp" type="number"/>
      <col name="sales" type="number"/>
      <col name="sunny" type="string"/>
      <!-- many empty cols to fill the sheet -->
    </columns>
  </meta>
  <data>
    <row>
      <cell src="18"></cell>
      <cell src="50"></cell>
      <cell src="no"></cell>
    </row>
    <row>
      <cell src="20"></cell>
      <cell src="126"></cell>
      <cell src="yes"></cell>
    </row>
    <row>
      <cell src="=sum(A1:A2)"><![CDATA[{"type":"integer","data": 38}]]></cell>
      <cell src="=sum(B1:B2)"><![CDATA[{"type":"integer","data": 176}]]></cell>
      <cell src="=sum(A3:B3)" type="number"><![CDATA[{"type":"integer","data": 214}]]></cell>
    </row>
    <!-- many empty rows to fill the sheet -->
  </data>
</sheet>
```

- Removed name,title,description fields (we have title and id properties in the manifest already)
- Using the cell text for the output now and a `src` attribute for the input
- Static cells don't need a redundant output (we just keep `src="foo"`)
- To model output, we should rely on CDATA and a JSON string inside. We can't just use plain text here (e.g. when a plot.ly chart is the output of a cell, or a table)

### (2) Advertise a more `open` official serialisation format?

I know this is already a kind of optimisation, but if we don't want to break this soon we'd need to think about how we can streamline the representation, as the verbose (in-memory) representation will certainly not be accepted by the community.

Here's an idea:

`sheet1.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sheet PUBLIC "SheetML 0.1.0" "http://stenci.la/SheetML-0.1.0.dtd">
<sheet>
  <meta>
    <columns>
      <col name="temp" type="number"/>
      <col name="sales" type="number"/>
      <col name="sunny" type="string"/>
    </columns>
  </meta>
  <data fill-rows="50" fill-cols="20" src-file="sheet1.src.csv" out-file="sheet1.out.csv">
    <cell-types>
      <cell-type row="3" col="3" type="number"/>
    </cell-types>
  </data>
</sheet>
```

`sheet1.src.csv`

```
18,50,no
20,126,yes
sum(A1:A2),sum(B1:B2),sum(A3:B3)
```

`sheet1.out.csv`

```
,,
,,
"{\"type\":\"integer\",\"data\": 38}","{\"type\":\"integer\",\"data\": 176}","{\"type\":\"integer\",\"data\": 214}"
```

- we keep the column information in the XML (column names and types)
- we move the data (source and output into separate csv files for better accessibility and smaller footprint)
- `src-file` and `out-file` specify the location of the data as CSV files
- `<cell-types>` element is there to override types for individual cells (not possible to do that in CSV)
- `fill-rows` and `fill-cols` attributes not to have explicitly include the fill-up cells in the serialisation format
- we can store the CSV string also inline in the document as a CDATA (however people may argue it's a lock-in)

I'd approach this similar to Texture where we expand the official JATS4M XML into the internal TextureJATS. So we would specify two XML schemas and implement a transform step in between.

**Comment by michael** [comment]
@nokome @oliver---- I can move forward with (1) if you agree with the suggested format?

**Comment by nokome** [comment]
@michael : (1) looks good to me. I am not sure about removing title and description but happy to go ahead without them to keep things minimal and add them back in later if they are indeed necessary.

**Comment by michael** [comment]
Sum up for implementing (1)

- source always go into `src` attribute
- static cells don't have a value (because src=value)
- value goes into CDATA block as `cell` content
  - this is only a serialisation step! we should never update the cell value during runtime
  - so we should have two schemas already like DarArticle (with cached values) and TextureArticle (without cached values) even if we don't do (2)

@Integral you could help with this but I think i need to do a first round to be certain about the implementation. Want to do it similar to how we do it in the article, it works well there.

**Comment by michael** [comment]
We will shift this and keep the current model for the release.
