### ISSUE TITLE
Errors are not cleared after delete of erroneous sheet cells

### ISSUE THREAD

**Issue by michael** [stencila/stencila#596]

**Comment by Integral** [comment]
All that I can said now that the reason behind this is that cell still have error state and sheet engine adapter is calling engine.removeCell.

**Comment by Integral** [comment]
Proposed fix here: #610

**Comment by oliver----** [comment]
This is particularly the case when changing a cell from an expression to a constant.
The engine should wipe errors when analysing constant cells.
