### ISSUE TITLE
Paused cells

### ISSUE THREAD

**Issue by michael** [stencila/stencila#602]
We need to model paused and global cells in the Dar format. This is important to support imported RMarkdown/Jupyter documents. Since we want to conform to JATS we would need to abuse an existing attribute (e.g. `code-type`)?

@nokome @oliver----  thoughts?

```
<code specific-use="cell" code-type="paused global">
  <named-content>
    <alternatives>
      <code specific-use="source" language="javascript"><![CDATA[x = 5*5]]></code>
      <code specific-use="output" language="json"><![CDATA[{ "value_type": "number", "value": 25}]]></code>
    </alternatives>
  </named-content>
</code>
```

**Comment by nokome** [comment]
I don't think the global flag is necessary since we have moved to a simplified execution model where all code in external language cells is executed is the global context of the context.

Using `code-type` seems OK but what about `executable="no"`?

**Comment by oliver----** [comment]
Ah, ok. Was not aware of this.
So, cells with 'external' languages should be executed sequentially? Or is this done already?
What about purely functional contexts, such as mini?
What about transclusions?

**Comment by oliver----** [comment]
I just realized that even mini could call functions with side-effects.

**Comment by nokome** [comment]
> So, cells with 'external' languages should be executed sequentially?

Sequential but "overriden" by dependency analysis. Like in your figure (?):
![image](https://user-images.githubusercontent.com/1152336/36715675-1595a36e-1bfc-11e8-8489-6b117c480745.png)

> What about purely functional contexts, such as mini?

Seems to me that because currently each Mini cell can only do a single assignment they are "side effect" free and the dependency analysis capture everything, so n o need for sequential.

> I just realized that even mini could call functions with side-effects.

No, although we don't enforce it all Mini functions should be implemented to be pure and side effect free.

**Comment by oliver----** [comment]
Yeah. We have to ensure, that functions are side-effect free.

**Comment by oliver----** [comment]
@nokome BTW, did you spot the 'issue' in the figure above?
If all external cells are assumed to have unknown deps via global state, a consequence of reactive evaluation would be that 'B' always triggers C-E, while there is no explicit dependency between them.
For instance, consider 3 ggplots in a notebook would update even if only the first need to.
Or do you want to move away from reactive updates here?

**Comment by nokome** [comment]
No, I didn't spot that. Good point. I suppose I was thinking mainly of the `$1`, `$2` applying on the initial full "reproduce" execution of the entire document. I'm not sure having the sequential reactive update is necessarily a bad thing. Would need to think about it more and/or try it out.

**Comment by michael** [comment]
Closing in favour of #620
