### ISSUE TITLE
Running stateful code (Jupyter/Rmarkdown) in Stencila

### ISSUE THREAD

**Issue by michael** [stencila/stencila#603]
I wonder how the execution model should look like for those. In Stencila we most often want to run code stateless, by passing in all inputs explicitly.

```
jsContext._executeCode('var x = a*a', {a: 5})
```

However for RMarkdown/Jupyter we would need to have one stateful session per user and document and run cells one after another and keep the state.

```
pyContext._executeCode('a = 5')
pyContext._executeCode('x = a*a')
```

Would we need to put a flag (global: true) or sometehing to mark the difference?

I wonder if for running such documents, we should simplify the execution model and run all code from the beginning to the end. The incremental execution (as done in the Jupyter interface could lead to invalid results) and we need this in the first place for compatibility.

I would also say it's not a good idea to mix global execution with stencila cells that have dependency analysis. This would become very confusing.

**Comment by oliver----** [comment]
@nokome will there still be an option to run 'external' code in a pure way?
Or do we want to cover this using mini, only?
