### ISSUE TITLE
Simplified Runtime/Hosts Panel

### ISSUE THREAD

**Issue by michael** [stencila/stencila#612]
![image](https://user-images.githubusercontent.com/2931/37090604-486c7c5e-2205-11e8-8447-546ecc786cd2.png)

- we use auto discovery for default hosts (e.g. Stencila hub + localhost)
- by selecting a host a user implicitly determines the runtime identifier (each host is exposing it) and we store it in the manifest.xml
- you can manually connect to a host using a separate dialog (there you enter a host url, including an API token etc.). this can be used to connect to custom images with custom libraries etc.
- clicking on the info sign opens a dialog with details about the the runtime (what languages in which versions, what libraries, which mini function libraries)

**Comment by michael** [comment]
Ok, some more thoughts on this. It is actually very important to select a runtime explicitly, and store that identifier in the manifest. Those runtimes need to be registered and verified, so it is actually problematic if allow creating new runtimes from the user interface (as the project would then no longer be reproducible).

What we probably want is a select box to choose an officially supported runtime in Stencila (Stencila Core / Mega). Then we list available hosts that provide exactly that runtime (we need a way to ping a host and ask for it's runtime and version)

Visually it could look like this:

![image](https://user-images.githubusercontent.com/2931/37106516-5095e154-2232-11e8-916d-dd0457f907fc.png)

**Comment by nokome** [comment]
This looks good and a big improvement of what we currently have.

I prefer "Environment" to "Runtime" - I think it is more accurate. I think of the container images (Docker, Singularity, whatever) encapsulating a computational environment and the "runtime" being the language runtime which is providing the HTTP server for the host (e.g. R, Node). That is the terminology we used over in stencila/images anyway.

One thing for us to consider is that users will be able to install Stencila language packages locally (e.g. https://stencila.github.io/r/) and run a host that is executing within their local environment (e.g. the R packages thay have installed). This will give flexibility for users early in project lifecycles and not require Docker or connecting to an remote host (closer to publication they could use an existing or custom image). Hosts need to include in their manifest the environment's that they support, including a possibly ill-defined local environment which might be in the list above as `local/local`. I'll work on this tomorrow.

**Comment by michael** [comment]
With these local/local environments, will you be able to also use other languages, e.g. SQL? Like I install the R language package, will I get just an R environment or Stencila Core + my custom R?

We may run into the situation that we need to disable some mini functions, which are backed by other contexts (e.g. Python), right?

Imo, if we were able to create a nice Stencila Mega image that would be suitable for most scientists, with some effort I'm sure we could win them over to switch to Stencila for authoring repro docs. Of course they continue to work and test in IDE's such as RStudio but only for developing algorithms which can then be made available in Stencila as functions (as part of the Dar).

**Comment by michael** [comment]
@nokome can we discuss this tomorrow morning and confirm so we can start implementing it?

**Comment by nokome** [comment]
> With these local/local environments, will you be able to also use other languages, e.g. SQL? Like I install the R language package, will I get just an R environment or Stencila Core + my custom R?

Most `Hosts` support more than one `Context` e.g. the R `Host` provides a `RContext` and a `SqliteContext`. The `local` "environment" just represents the current machine. So if you install the R language package you get your local, custom environment (all the R packages plus system libraries e.g. libxml2 they depend upon).

> We may run into the situation that we need to disable some mini functions, which are backed by other contexts (e.g. Python), right?

Yes, but they won't need to be disabled, they just won't get registered in the first place. When we connect to an execution context e.g. `PythonContext` we call it's `getLibraries` method to get a list of functions implemented in Python.

I have started on some documentation of the Host API, including an `environs` endpoint here: https://github.com/stencila/stencila/blob/doc-updates/docs/computation/hosts.md . Also, I have upgraded the `stencila-node` package to this new API so it's the best place to try things out. 

I think the authentication flow is the most challenging bit. Previously, users could manually enter a URL with a 'ticket' in it: e.g. `http://127.0.0.1:2000/?ticket=27b9083e2eb77314581d95a6`. But if autodiscovery is the default we need to have an input box for users to add such access tokens if a specific host nedds one.

**Comment by nokome** [comment]
An update. The `/environs` endpoint is implemented in `stencila/node` and over in https://github.com/stencila/node/pull/26 I've been working on a better authorisation mechanism (and data pointers, which are related). The handling of execution context types in the manifest is also simplified.

I have started #619 to update the `Host` here in the client so it can use this new API. I expect to have that finished tomorrow so that the UI elements of this issue can be started.

**Comment by michael** [comment]
Keep in mind we don't need to expose all planned functionality in the initial release. For the initial desktop release this panel should help discover problems with stencila-mega image that is run locally. Maybe for the start leave out the UI's for adding remove remote engines/enter user credentials etc. We can add them later once we have a clear picture of what user inputs we need.
