### ISSUE TITLE
Reinstate inline cells

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#618]
Previously, Stencila documents had `InlineCell` nodes e.g. https://github.com/stencila/stencila/tree/a8c1c3462c10a6fb406f02fca31ea62acd5f7b29/src/document/nodes/inline-cell,  single expression cells that display text inline. These are often used in reproducible documents e.g. this snippets from the RMarkdown that generated https://elifesciences.org/articles/30274:

```
bars represent s.e.m. from `r length(subset(data2, Lot==1 & Time==0)$value)` independent biological repeats..
```
Perhaps these could be represented in JATS using `<code executable="yes" language="r">`? e.g.

```
bars represent s.e.m. from <code executable="yes" language="r">length(subset(data2, Lot==1 & Time==0)$value)</code> independent biological repeats.
```

**Comment by michael** [comment]
Yeah we can bring those back. There's a bit of work involves though:

1. Decide on a JATS tagging style for inline cells
2. Add converters to go from DarArticle to TextureArticle (where we can use custom tags e.g. inline-cell
3. Review the UI/UX and port over from the old Stencila build.

Not sure we should address this for the April release? Or a bit later?

**Comment by nokome** [comment]
It would be nice to have in the April release but could also probably wait if that is not possible. Lack of inline cells will be a blocker for displaying some of the RMarkdown examples shortlisted for eLIfe RDS. But we can still progress those examples using placeholders for inline cell content - and wait for a later release for them to be properly rendered.

**Comment by michael** [comment]
I started with defining a tagging style in JATS and our internal TextureXML:

- https://github.com/substance/dar/blob/master/DarArticle.md#named-contentcontent-typeinline-cell
- https://github.com/substance/texture/blob/master/docs/TextureXML.md#inline-cell

@nokome would it be ok to allow only leave nodes (means no variables can be defined in inline cells (aka output nodes)?

**Comment by nokome** [comment]
Great. Yes, inline cells should be limited to expressions like sheet cells.
