### ISSUE TITLE
UI/UX Cell status (including paused state)

### ISSUE THREAD

**Issue by michael** [stencila/stencila#620]
Here's how the UI could look like for a cell that is paused and need to be run manually.

![image](https://user-images.githubusercontent.com/2931/37907518-a3a6796c-3105-11e8-80c7-86fcf8d6fd11.png)

Here's all other possible states:

![image](https://user-images.githubusercontent.com/2931/37907990-f11a78fa-3106-11e8-97d1-489d2c5e9e4e.png)

NOTE: We decided to not add additional icons, and keep things clean with a simple green,yellow,red (traffic light) color coding. For running cells we would display a wider grey bar, which fades in and out.

**Comment by nokome** [comment]
This is all looking great! :tada: 

I agree that we should stick with the traffic light colour coding. Also agree that a fading in/out grey for running cells is very useful. My only suggestion is that _all_ status colour bars be made 3 or 4px wide - currently they are 2px and, to my eye at least, too narrow.

**Comment by nokome** [comment]
I could be useful to have a description of cell status (e.g. 'Running', 'Errored' etc) when mousing over the cell, or the cell status color bars?

**Comment by michael** [comment]
@integral could you add the tooltips?

**Comment by apawlik** [comment]
A note on colours use - we should consider accessibility issues for colour-blind users. Red+green is not the best option.
