### ISSUE TITLE
Improve UX of function help tooltip

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#641]
At the moment the tooltip is shown whenever the cursor is on a function or inside the parameters.
This is basically good, however, it is a bit obtrusive with that popup being visible all the time.

Alternatives:
1. Only show the tooltip when cursor is on the function name.
2. Only show the tooltip when idle
3. Let the user decide to turn off automatic popups and trigger explicitly (e.g. as it is in Elipse using `Ctrl+Space`)
4. Only show tooltip when typing.
5. Disable the tooltip on arguments for functions that span over multiple lines.

**Comment by oliver----** [comment]
Added alternative `4.`

**Comment by apawlik** [comment]
Hmm, I kind of like 1, actually :-) I think it is similar to some other applications (cannot recall any at the moment...but it seems familiar). 
3. would be good but I am not sure what is the awareness among our target users that there actually **is** an option to turn the popups off.

**Comment by oliver----** [comment]
Right, with `3.` the problem is really that in anyway it is a bit obscure to new users.
In Sublime it is a combi of `4.` and `3.`, i.e. the popup shows automatically while you type, otherwise you can trigger it using `Ctrl-Space`.

**Comment by michael** [comment]
I most like `3.`, as it gives full control and zero noise. The only problem is that you'd need to learn a shortcut, which means many users may miss the functionality. I'd definitely go for 3 and maybe combine it with `1.`.

**Comment by Integral** [comment]
Yeah, those things might be kind of a revelation. For instance I didn't
know about this shortcut in Sublime. So we need to find a proper way to
tell users about this thing. Maybe we should print combo while user is in
1. state?

**Comment by nokome** [comment]
My preference is to implement `1` and then maybe add `3` later.

**Comment by michael** [comment]
@Integral can you implement `1` and make a PR?

**Comment by Integral** [comment]
Another option, we could switch off tooltip for a big arguments or multiline arguments. @oliver---- what do you think?

**Comment by oliver----** [comment]
Personal I am in favor of a more consistent solution. But I will add your suggestion to the alternatives :)
