### ISSUE TITLE
Cell ranges overlay does not handle transclusions

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#663]
In a sheet, when a cell formula transcludes data from another sheet, the cell range is erroneously indicated to be in the current sheet:

![image](https://user-images.githubusercontent.com/1152336/39608628-eb8f5a46-4f96-11e8-934a-53f920344d8e.png)

In this screenshot, the function tool-tip is also broken, but that is a different issue :)

**Comment by oliver----** [comment]
Will take a look into this one.
