### ISSUE TITLE
Error message goes away if cell code editor is blurred

### ISSUE THREAD

**Issue by michael** [stencila/stencila#665]
I think we should always show the error message. Thoughts?

**Comment by oliver----** [comment]
How does that look like?

**Comment by michael** [comment]
![no-error-on-blur](https://user-images.githubusercontent.com/2931/39620592-06034136-4f8c-11e8-9f2c-c1f2031af828.gif)

**Comment by oliver----** [comment]
Right, that is strange. @Integral do you have an idea how to fix this.
I think it happens, because the Cell is rerendered because of loosing the focus.
And the current renderer hides the error too eagerly (originally intended to reduce obtrusive error message while typing)

**Comment by Integral** [comment]
Need to investigate, you can leave it to me and I will look at this in the
evening.
Re too eagerly, would be ok if I will increase timeout? So it will stay a
bit longer?

**Comment by oliver----** [comment]
Re timing: Alright.
Re eagerly: No. It should detect if the cell error/status has changed, which is only happening if the user actively updates the source. Just re-rendering with everything being the same should not change the visual appearance.

**Comment by oliver----** [comment]
The originally intended idea was:
"When the user is typing, show errors with a delay, but valid results instantly"

**Comment by oliver----** [comment]
So we need to come up with an interpretation of "when the user is typing". My suggestion is to simplify this to "when the cell state is changing".

**Comment by Integral** [comment]
E.g. so every time when the cell state is changing we will reset timeout
and start counting until 1 second for instance. So if nothing will change
we will show error (if it's there). Right?

**Comment by oliver----** [comment]
Sounds good :)

**Comment by Integral** [comment]
@oliver---- I have a feeling that it's exactly what we are doing currently :) I will look into that

**Comment by oliver----** [comment]
I don't think that the cell state changes when changing the focus.

**Comment by Integral** [comment]
It's a bug definitely!

**Comment by oliver----** [comment]
This will be fixed via #672
