### ISSUE TITLE
Func value regression

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#666]
Trying out the latest function return value implementation, I faced an error in ContextHttpClient: it tries to unpack `value.data` while `value` already seems to be unpacked.

![image](https://user-images.githubusercontent.com/284099/39623144-f82e3de6-4f94-11e8-8c1f-846304f67048.png)

**Comment by nokome** [comment]
Thanks @oliver----, but I can't reproduce this error. 

https://github.com/stencila/node/commit/0fd3e4d7f6724889b5f178abe2baff7d90501607 (which you said you were using?) was supposed to fix it. This is what I get with that commit (master at time of writing) and https://github.com/stencila/stencila/commit/ad062de65a7c987189bd35de2b82013befca253d (develop at time of writing). By starting the dev server here and in stencila/node doing:

```bash
STENCILA_AUTH=false npm start
```

Then going to `http://localhost:4000/example.html?archive=repro-pub&hosts=http://localhost:2000`:

![image](https://user-images.githubusercontent.com/1152336/39688102-44cdf460-5225-11e8-917a-a78ac6cfc017.png)

So it may have been an issue with linking.
