### ISSUE TITLE
Fatal error when switching between documents

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#677]
This error occurs when you start writing a function in an article, and then switch to a sheet. For example you start writing `plot(Data!A...)` and then switch to the sheet to see what the range should be.

![image](https://user-images.githubusercontent.com/1152336/39684339-4874e1a2-520f-11e8-912c-4ad249241c85.png)

My experiments suggest that this only you have an **unfinished** function call in the article cell e.g. `sum` and `sum(1,2,3)` are fine but `sum(` will fail.

This is a 'fatal' error because it prevents the user from being able to switch back to the article - which in the desktop means you have to close the app and reopen the document.

**Comment by oliver----** [comment]
@nokome this does not happen for me (on latest stencila@develop)
Any idea how to narrow this down?

**Comment by oliver----** [comment]
Anyways, technically this happens when the selection points to a none existing surface.
I will add a guard to the respective code in substance.

**Comment by oliver----** [comment]
@nokome If you can reproduce the error, could you try if #678 fixes the issue?

**Comment by nokome** [comment]
Yes, fixes #678 fixes the issue? Thanks!
