### ISSUE TITLE
Which repo for Beta Testers to file issues in?

### ISSUE THREAD

**Issue by apawlik** [stencila/stencila#680]
For the first cycle of our Beta Testing programme (related to Stencila Desktop release). Where should we ask the Beta Testers to file in issues? The main `stencila` repository or `desktop`? Understandably some issues will be more relevant to one than the other, but we should make it easy for our Testers and point them to one place.

What is your preference?
@michael @oliver---- @nokome

**Comment by nokome** [comment]
I think different users will have different preferences as to where they would like to file feedback/bugs. So maybe we should avoid being too prescriptive but suggest this order:

1. https://community.stenci.la : For usability/UX issues, "how do I do..." questions etc. It's more accessible and less intimidating to beginners and the more people post there the more it will become for others to get help, share tips etc. Users can also put bugs there if they like and we can organise them into Github issues when they are reproduced etc)

2. `stencila/stencila` repo : If the user has a Githu account and the 'issue' is a bug.

3. `stencila/desktop` repo: If the 'issue' is a bug related to menu items, installation etc. But we might merge this repo into `stencila/stencila` so this should probably be the last on the list.

**Comment by apawlik** [comment]
Thanks! OK. I will update the test feedback form and get that incorporated into the guidelines. I would opt for 1 and 2. It's just that I don't want the Testers to ponder "Is this bug belonging to stencila repo or desktop repo". Probably not a common thing but just want to make Testers' life as easy as possible.

**Comment by apawlik** [comment]
I was thinking for the errors to be submitted via GH issues or through this form https://goo.gl/forms/VBdrzPqzMAGI7Hxk1 
But yes, I think FOrum and Gitter are great for "How do I...?"

**Comment by oliver----** [comment]
The form is nice!

**Comment by apawlik** [comment]
@oliver---- Cheers :-) Well, we're getting ready for the testing. I think it will be a pretty cool experience and us, as well as our community will learn a lot.
I'm closing this issue for now. Feel free to reopen, if anything new comes up.
