### ISSUE TITLE
When using a variable from Javascript context it is considered an output declaration

### ISSUE THREAD

**Issue by michael** [stencila/stencila#685]
![image](https://user-images.githubusercontent.com/2931/39992746-0e17c29e-5774-11e8-8a6b-c3f795fea394.png)

This should only happen if I write:

```
var numbers = ...
```

**Comment by michael** [comment]
There seems to be generally a problem with parsing JS cells, and things are wrongly considered a cell-graph input variable, when they are just local vars.

![image](https://user-images.githubusercontent.com/2931/39995572-f27121b2-577c-11e8-8ed1-e3f8698a26b8.png)

**Comment by oliver----** [comment]
The current implementation is too naive. Will take a look at https://github.com/ForbesLindesay/acorn-globals/commits/master
Either use it, or learn from it.

**Comment by oliver----** [comment]
BTW, can confirm, that in both cases JsContext produces wrong analysis:
- output on a statement with just an identifier
- declaring inputs for variables in anonymous functions

**Comment by oliver----** [comment]
@nokome and me had a short discussion what to do about this:
We want to extract JavascriptContext from the node repo, to be able to share the code with the browser-only version. @nokome will setup this repo, and I will pick it up to do some cleanup, and fix the issues mentioned here.
