### ISSUE TITLE
Debugging Javascript Cells

### ISSUE THREAD

**Issue by michael** [stencila/stencila#686]
I'm trying to leverage Javascript cells for some simple tasks (like converting between data representations such as mapping from a Stencila table object to a 2d array) and I'm having problems as there's no good way to inspect code at runtime.

Do we have any ideas how we could approach debugging custom code cells? Especially for Javascript it would be so good to have some way to inspect values as the code is executed. This is a major problem for me in other systems as well (e.g. Observable).

I just used this trick:

- turn auto evaluation off
- add some js code including a debugger statement
- turn code evaluation on again

Now I can inspect the values:

![image](https://user-images.githubusercontent.com/2931/39996729-d366cf16-5780-11e8-879b-22c89cc6804c.png)

**Comment by oliver----** [comment]
What you do here is the only way I can imagine. With externally run code, there could be a way with remote debuggers -- but this is not trivial.

**Comment by michael** [comment]
Yeah definitely not trivial, but I've started thinking of how it could be solved UX wise. If we could make this happen one day, it would be a whole new level of a dev experience.

Given our dependency graph we would always only need to debug a very local piece of code. Let's assume you have auto eval turned off. Now let's say there would be a command `RunAndHalt` (cmd+shift+enter) that runs all code until the line where the cursor is and stops there. Then with mouseover over the variable names (e.g. surface_data) we could show a variable inspector popover (like Chrome debugger does). Instead of step next/ step into, we could just run the same thing for the next line.

![image](https://user-images.githubusercontent.com/2931/39998270-d5b0321c-5785-11e8-85ab-6a9f50f5aecc.png)

At least if we had an inspector for primitive datatypes (no matter what language) that would be already super helpful.

**Comment by oliver----** [comment]
When it comes to remote debugging, you are actually not really in charge. I.e. you can need to connect the debugger and visualize what you get.
So, I fear this is out-of-scope for a long time.
