### ISSUE TITLE
Seeing warning "Too many active WebGL contexts"

### ISSUE THREAD

**Issue by michael** [stencila/stencila#687]
![image](https://user-images.githubusercontent.com/2931/40001281-31b8fd98-578e-11e8-8dc2-d6fc3a3157b9.png)

This happens if rerendering of Plotly value (that uses WebGL) is triggered too often. It also gets increasingly slow. 

Maybe we need to call some method to dispose the old context.

**Comment by oliver----** [comment]
`Plotly.purge()` should do the trick: https://community.plot.ly/t/how-to-unmount-remove-destroy-a-plotly-chart-and-its-plotly-instance-object/1147/3
Also I suggest to replace `rerender()` of the PlotlyValueComponent with a debounced one: https://lodash.com/docs/4.17.10#debounce

**Comment by michael** [comment]
Oh thanks for looking that up. @Integral want to take this one? I will soon merge my introduction example, then you have something to test.

**Comment by oliver----** [comment]
@Integral can you do this one?

**Comment by Integral** [comment]
I'm not sure that we can fix that. First of all we are [already calling purge method](https://github.com/stencila/stencila/blob/develop/src/shared/PlotlyValueComponent.js#L48). And [here](https://github.com/plotly/plotly.js/issues/337#issuecomment-197892374) you can read a response to this issue of Plotly's maintainer. And it looks like they didn't fix that yet.

**Comment by Integral** [comment]
And regarding debounce strategy... I can do that, but you give an example of too often rerendering? Is it really happening?

**Comment by oliver----** [comment]
I suppose the example is the new introduction @michael has created.
There are other API alternatives: https://plot.ly/javascript/plotlyjs-function-reference
Maybe there are other options that work.

@michael please let @Integral know how to reproduce this error.

**Comment by bytesnz** [comment]
I am also seeing the same issue. I have a page with 4 scatter-gl plots on it that are redrawn (`purge` and `newPlot`) when zooming in on data (as it downloads higher resolution data). Once the graphs are redrawn a couple of times, you start getting the WebGL warning messages. Was wondering if the GL context wasn't being "removed completely" on `purge`?

**Comment by panchagil** [comment]
Hi, I had a similar problem when updating the mesh of a mesh3d plot. The solution was to use the function [Plotly.react](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyreact).

**Comment by gnestor** [comment]
Replacing `Plotly.newPlot` with `Plotly.react` also worked for us 👍
