### ISSUE TITLE
Case Sensitive Functions

### ISSUE THREAD

**Issue by campbellyamane** [stencila/stencila#689]
For example, =sum and =SUM are treated differently. I'm not sure if this is because =sum may ultimately have a different purpose, but if not, it may make for an easier user experience if the functions were not case sensitive.

**Comment by oliver----** [comment]
Thanks. You are right. While in general programming case-sensitive function names are common, this is not common in Spreadsheets.
This is technically easy to solve, we just need to decide :)
@nokome your take on this?

**Comment by michael** [comment]
While not common in spreadsheets, I still think there's value in having function names case sensitive. That way we can enforce a consistent coding style across sheets and articles. Of course we shouldn't expose any uppercase functions then.

At least we should enforce naming guidelines for Mini functions (lowercase, underscore separated,...), for external language cells we can't and there we would expect the code being case sensitive too.

**Comment by nokome** [comment]
Sorry, to be slow to respond on this. As Michael says this only applies to Mini (in sheets or articles). My thoughts on this were to: 

- enforce a naming convention of `snake_case`
- reserves all caps function names e.g. `SUM` for Excel compatibility functions (i.e functions that behave just like Excel ones). This will allow us to:
    - much more easily convert Excel spreadsheets safely while also allowing us t,
    - define a better :) set of native Mini functions (ie. I think we can learn and make better names and arguments for Mini functions and use named args etc. and not try to slavishly follow Excel)
