### ISSUE TITLE
Auto-closing Functions

### ISSUE THREAD

**Issue by campbellyamane** [stencila/stencila#690]
For example if I type "=SUM(A1:A4", I will get an error because I didn't include the closing parenthese. I'm not sure how much you would want to assume of a user, but some sort of auto-closing tag system would be useful.

**Comment by campbellyamane** [comment]
Yeah, either that or when a user presses enter, the close paren is automatically added. That's more of a stylistic choice I suppose though.

**Comment by oliver----** [comment]
It just should be deterministic, i.e. not depend on the current state. It might be pretty difficult to 'understand' this without full language analysis (think of nested function calls).
So this is probably the reason why existing code editors do it when the user opens a paren.
