### ISSUE TITLE
Sheets: Entering a sheet cell via enter does not set the selection anymore

### ISSUE THREAD

**Issue by michael** [stencila/stencila#691]
Could be a Substance regression (@oliver can you confirm). I've updated to Substance preview.55.

Reproduce:

- Enter cell with enter
- Start typing (cursor is not set and first character is overwritten all the time)

**Comment by oliver----** [comment]
Will check!

**Comment by oliver----** [comment]
It was a breaking change in substance. 

It is about sufaceIds in the context of nested surfaces. The safest thing is not to hand-code surfaceIds, but just use `targetSurface.getSurfaceId()`
