### ISSUE TITLE
Improve Cell Menu UX

### ISSUE THREAD

**Issue by oliver----** [stencila/stencila#698]
While it was a nice trick to bind node selection and the cell ellipses menu, I just don't like the UX.
@michael maybe you have an idea to improve this?

> FWIW, this way we achieved a keyboard navigation to the menu without an extra keyboard shortcut et al.

**Comment by michael** [comment]
Yeah it's not ideal. I'd suggest to address this once we have the app state API's in place. As if we decouple the ellipses menu from the node selection, we need to make sure the popup gets closed when you click somewhere else. I'd like to solve this with a single overlay for all cell menus, and ensure there can always be one overlay at a time.

We can use a separate keyboard shortcut for bringing up the ellipsis menu. E.g. while you are typing the code, and once the navigation is done continue at the same cursor pos.
