### ISSUE TITLE
Do not show function usage popover when external language is used

### ISSUE THREAD

**Issue by michael** [stencila/stencila#699]
Currently when I switched a cell to Javascript, it still displays function tooltips for Mini.

![image](https://user-images.githubusercontent.com/2931/40167339-185f6d3e-59c1-11e8-913e-8b6c361a5de2.png)

**Comment by Integral** [comment]
Leave it to me please

**Comment by michael** [comment]
ok :)

**Comment by michael** [comment]
I guess we could pass a property `disableFunctionUsage: true` to the CodeEditor? And then the command needs to check this somehow.

**Comment by Integral** [comment]
@michael will try, thx!
