### ISSUE TITLE
Extract model-related code into a shared place

### ISSUE THREAD

**Issue by michael** [stencila/stencila#700]
I'd like to start with the webpage generator and I'd like to design it so that we can utilise the infrastructure we already have in Texture and Stencila but do it without the UI (e.g. label generation, citation rendering etc., value computation)

I'd propose to extract all model-related code so we can use it without the editors

- `substance/dar` has models for DarArticle and DarSheet
- `stencila/engine` has the engine implementation (dar would then require the engine, so we can open and run stencila projects headless)
- `substance/texture` has the article editor component
- `stencila/sheets` has the sheet editor component
- `substance/dar-gen` - module to build a static site based on a Dar
- `stencila/stencila` has the stencila app and integrates dar, texture, and sheets and dar-gen

Currently we have StencilaArchive and TextureArchive, and thus some redundant code. I'd favor moving towards a generic DarArchive implementation that is used by both integrations.

It would be good to do this split soon, so I can make dar-gen depend only on dar. I'm aiming to complete this work by end of June for a demo at eLife.

@oliver---- @nokome thoughts?

**Comment by nokome** [comment]
I'm in favour of this (and as I said in my email, perhaps doing some renaming). I feel like it would be worth doing a cleanup of `stencila/stencila` first (there is quite a lot of dead code) rather than during a reorganisation.
