### ISSUE TITLE
Upgrade to FontAwesome 5

### ISSUE THREAD

**Issue by michael** [stencila/stencila#701]
We should finally upgrade to FontAwesome 5. We'll get better icons.

@Integral want to take this one?

**Comment by michael** [comment]
@Integral actually this should be done first in Texture, got the wrong repo.

**Comment by Integral** [comment]
@michael I need your feedback. When you said that we'll get better icons, do you mean that we should use svg now?
Fontawesome 5 provides different tools for icon rendering. We can still use webfonts, but we could also use so called SVG with JS. What was your idea?
