### ISSUE TITLE
using JavaScript with library (e.g. d3)

### ISSUE THREAD

**Issue by de-code** [stencila/stencila#706]
The plotly library doesn't provide the chart I am looking for (hive plot) and I'd use d3 directly for it. I also have some JavaScript code that doesn't seem to be on a cdn.

What is the recommended way of integrating it? Can I add JavaScript files to the project? How would I import it? And what methods of debugging are there? (e.g. console.log - which doesn't work)

**Comment by nokome** [comment]
Thanks, this is useful feedback and idea.

> What is the recommended way of integrating it?

To improve reproducibility, we have been focused on the idea of providing a pre-defined, versioned environment for each language, including Javascript. For JS, we are currently doing that via https://github.com/stencila/libcore which has these dependencies which get bundled into `stencila-envcore.min.js`:

```
  "dependencies": {
    "@stdlib/stdlib": "0.0.36",
    "jstat": "1.7.1",
    "lodash": "4.17.10"
  },
```

The approach would be to add commonly used modules, like d3, into that bundle. We have refactored the Javascript execution context and put it into its own repo and in a forthcoming release will make these modules available as global names in the JS cells.

But nonetheless, there are instances where you have a less commonly used JS module that you want to use, In which case you could load it from the project...

> Can I add JavaScript files to the project?

There is not UI for doing this but it should be possible to just add it to the folder and put an entry in the manifest.xml

> How would I import it? 

In the desktop, you can use Node.js context to `require` a module:

![image](https://user-images.githubusercontent.com/1152336/40640065-6d1324aa-6368-11e8-92ca-faba5d7107c1.png)

We need to make the `cwd` of contexts like NodeContext, RContext etc, the project folder. Currently, that is not the case, so unfortunately it is necessary to hardwire a path as above.

> And what methods of debugging are there? (e.g. console.log - which doesn't work)

You can add `debugger` to the JS cell and open up the dev console e.g.

![image](https://user-images.githubusercontent.com/1152336/40639771-db7fdaa2-6366-11e8-92da-9a45eb93f270.png)

Currently, `console` is not available but we intend to enable it to allow for simple debugging. In that case, as with `print` statements in Python and R, the `stdout` would be captured and become the cell output value of type `string`. 

See https://github.com/stencila/stencila/issues/686 for some ideas and discussion on debugging JS cells.
