### ISSUE TITLE
Adding cell is replacing cell instead of adding a new one

### ISSUE THREAD

**Issue by de-code** [stencila/stencila#707]
When selecting a cell and pressing Escape the cell is highlighted. After pressing Ctrl+Enter the cell is replaced.

**Comment by nokome** [comment]
I can confirm that this behaviour exists in both Stencila Desktop 0.28.0 and current `develop` branch. When a user is in a cell and wants to create a new cell immediately after it, they have to press `Esc`, then `Enter`, then `Ctrl+Enter`. Missing out the middle `Enter` replaces the current cell.
