### ISSUE TITLE
Stencila Desktop - menu colours: white on light grey

### ISSUE THREAD

**Issue by de-code** [stencila/stencila#708]
This may be depending on the theme, but for me the top level menu items are shown with a white foreground colour on a light grey background which makes the menu barely visible. The sub menu items are showing up fine (black on light grey).

(This is on Kubuntu 16.04)

**Comment by nokome** [comment]
@de-code : could you post a screenshot, I seem to get a different appearance on Ubuntu 16.04: light grey text on white background for deactivated commands, black text on white background for activated commands

![image](https://user-images.githubusercontent.com/1152336/40638905-190e50ec-6362-11e8-9a45-eaf2ef48bb7b.png)

**Comment by de-code** [comment]
Apologies, I meant the app menu. This is what it looks like for me:

![image](https://user-images.githubusercontent.com/1016473/40704996-44c94a42-641c-11e8-95be-91fa1f4556a9.png)

**Comment by apawlik** [comment]
Hi @de-code , Sorry for late reply! It may be a theme thing. I am on Ubuntu 16.04
![image](https://user-images.githubusercontent.com/2358535/43043590-1153b23a-8deb-11e8-866e-793b2ded5a6a.png)
