### ISSUE TITLE
Recommended way of sharing documents

### ISSUE THREAD

**Issue by de-code** [stencila/stencila#709]
Currently a DAR archive consists of a directory (with the manifest etc).
If say I want to share a document with someone else, it would be more convenient if I could send a single file (e.g. a zip file). Of course the recipient could extract it. But can Stencila operate on a single file rather than a directory?

**Comment by nokome** [comment]
Yes, I expect that wanting to share and read/write a single file will probably be a common request, particular for users used to Word and Excel. That capability is currently not there but if it's something that is wanted by enough users then it should be fairly straight forward to implement by reading writing to a zip file with a custom extension e.g. `project.dar`

**Comment by taunsquared** [comment]
could there also be a way to view the xml files in a browser? I'm using Stencila to write my thesis and I'd love to share drafts, outlines, etc with folks who aren't using Stencila. If you want a lot of non-coders to use Stencila I think it will make a huge difference to be able to share a final rendered view of the document without asking folks to download an app.

**Comment by nokome** [comment]
> could there also be a way to view the xml files in a browser? 

@taunsquared : Yes, that is definitely something we want to have soon! We're working on rendering to static HTML and the [`stencila/convert`](https://github.com/stencila/convert) repo has converters for a range of formats (although they are still alpha and currently undergoing a bit of refactoring).

**Comment by apawlik** [comment]
@taunsquared Thanks for testing out Stencila. We are also going to enable soon Stencila Hub which should make sharing much easier.
