### ISSUE TITLE
"Add Reference > Or create manually" buttons fail

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#710]
See error below when clicking on one of the buttons
![image](https://user-images.githubusercontent.com/1152336/40642182-67c9a8d6-6370-11e8-8755-8d0e28fb540d.png)

**Comment by michael** [comment]
Do you still see this with the updated Texture? preview.2.1?

**Comment by nokome** [comment]
Yes, this is current develop branch of this repo with a `rm -rf node_modules` prior to `npm install`

```bash
npm list --depth=1 | grep substance-texture
├─┬ substance-texture@1.0.0-preview.2.1
```

**Comment by oliver----** [comment]
Was a regression, because we did upgrade texture, but not substance.
Unfortunately the peer-dependency version checks do not seem to work for 'preview' versions.
