### ISSUE TITLE
Error when attempting to create a new table

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#711]
When trying to insert a new table using the table toolbar icon get the following error (in 0.28.1).

![image](https://user-images.githubusercontent.com/1152336/40762586-6f677b32-64f5-11e8-8be5-6fdf190acf94.png)

**Comment by oliver----** [comment]
This was because of divergent integration of Texture's Editor in Stencila.
Have fixed it in Texture, to avoid these kind of scenarios.
