### ISSUE TITLE
Stencila Desktop - find and replace function?

### ISSUE THREAD

**Issue by taunsquared** [stencila/stencila#713]
Hi, I'm trying out Stencila Desktop by using it to write my thesis, and I'm sorely missing the "Find & Replace" function. This would be a lovely feature to have, if it's not already on a to-do list somewhere!

**Comment by apawlik** [comment]
@taunsquared Thanks for your feedback and suggestion! We're pushing it up the priority list. Also, absolutely fantastic to hear that you are trying out Stencila for your thesis writing!
