### ISSUE TITLE
Subpixel antialiasing disabled on Windows

### ISSUE THREAD

**Issue by nyanpasu64** [stencila/stencila#721]
The entire user interface of Stencila (excluding the menu bar) has subpixel antialiasing disabled, resulting in fuzzy text (especially noticeable at 96DPI screens).

I opened Developer Tools (Ctrl+Shift+I) and replaced all HTML and CSS with a single word (asdf). The resulting text was fuzzy as well, as confirmed using ShareX Ctrl+PrintScreen zoom-in.

- So this is a result of Electron/etc misconfiguration, not a misguided "enable GPU acceleration" CSS disabling subpixel.

This program should respect the user's font rendering settings. This bug is a deal-breaker for me.

**Comment by nokome** [comment]
Thanks for the bug report @jimbo1qaz. Could you tell us what operating system you are using and we'll try to fix this as part of the next release.

May be related to this issue https://github.com/electron/electron/issues/10955

**Comment by jimbo1qaz** [comment]
I am using Windows 10 x64, Version 1709 (OS Build 16299.547). The issue you linked to is on Linux, but may be related (attempting to enable GPU acceleration everywhere).

(I noticed that Visual Studio Code, another Electron app, has subpixel enabled in the main editor, status/menu, etc. but not the find panel.)
(sorry for the last line in my first post)

**Comment by Slapbox** [comment]
I'm on Windows 7 x64, seeing the same issue.  It seems to be even worse inside of webviews.

Some screenshots: https://github.com/electron/electron/issues/8708#issuecomment-411893229
