### ISSUE TITLE
Referencing KaTeX formulae

### ISSUE THREAD

**Issue by apawlik** [stencila/stencila#726]
Suggested by Alex K.

*How can the equations be labelled and automatically enumerated and how can you refer to them in the text?  For example, in Latex when you want the equation to be enumerated you write your equation inside the environment:*

```
\begin{equation}\label{my cool equation}
math expression goes here
\end{equation}
```

*Then if you want to refer to it in the text you just write \ref{my cool equation}.
In LaTeX manuscripts you use it all the time but KaTeX doesn't recognise this (nor similar environments, like equation array, etc...)*

**Comment by michael** [comment]
KaTeX is just there for rendering. What we will need to support is block formulas (with labels and cross references), which will be a Texture feature. Not sure they make it into 1.0 though.
