### ISSUE TITLE
R variables not available in following cells 

### ISSUE THREAD

**Issue by nuest** [stencila/stencila#727]
(Not sure if this is the right repo, let me know if I should post elsewhere. I only briefly checked for existing issues, hope I did not miss anything obvious.)

I am working on a write-up of the Stencila+Jupyter integration, see https://github.com/minrk/nbstencilaproxy/issues/12

I noticed the following problem when opening a document with R examples, see https://github.com/nuest/stencila-r respectively try out with https://mybinder.org/v2/gh/nuest/stencila-r/master

When the second cell ends with a plot command, the variables `z` etc. are not resolved in the third cell:

![image](https://user-images.githubusercontent.com/1325054/47666852-e3563f80-dba4-11e8-809e-ab28992c7d46.png)

If I comment out the plot, then the histogram is shown:

![image](https://user-images.githubusercontent.com/1325054/47667000-362ff700-dba5-11e8-83b5-ff5980421c41.png)

I got everything to work when putting each assignment in an extra cell (which was a pain by the way, because it is not possible to change the language of a cell when there are syntax errors in it, which there are if I paste R code to the default cells (which are mini):

![image](https://user-images.githubusercontent.com/1325054/47667575-9ecba380-dba6-11e8-8641-28043787f0f1.png)

**Comment by nokome** [comment]
Hi @nuest and thanks for the bug report!

> I got everything to work when putting each assignment in an extra cell

Yes this is a problem with the current execution model - we only allow for one output per cell. Internally the cell data model and the R dependency analysis allows for multiple named outputs but currently the execution engine assumes there is only one.

We found this to be a common usability issue in our workshops and something that need to be addressed soon. To some extent this is a hangover from our initial thinking that each cell should be be like a function call (ie. with multiple inputs and only one output) and we would just pass data values between cells. But we have come to realise that it's too different from how people expect it to work and forcing people to split things into individual cells is not an option.
