### ISSUE TITLE
How to run Stencila on my machine

### ISSUE THREAD

**Issue by michael** [stencila/stencila#77]
It's currently a bit hard to find out what's necessary to run Stencila on your machine, like a quickstart without setting up a full C++/R environment. Maybe the README should feature a short section that describes the steps needed to run Stencila using the provided docker container. Could you provide that? ~~Still~~ Already forgot what we did the other day to make it run on my OSX machine. ;)

**Comment by nokome** [comment]
Thanks @micheal, I started writing a simple INSTALL.md on the train from Linz to Vienna. I'll try to get that finished today!

**Comment by micheal** [comment]
I think you meant @michael. :)

**Comment by nokome** [comment]
Oh, I did, sorry about that!

**Comment by micheal** [comment]
All good. Man, I need to change my name. :P

**Comment by nokome** [comment]
@michael : I have updated https://github.com/stencila/stencila/tree/develop/docker. Basically you should be able to:

```
docker run --detach --publish=7373:7373 stencila/ubuntu-14.04-r-3.2 stencila-r demo/stencils/kitchen-sink serve ...
```
Then run server.js (`make web-devserve` does this) and open `http://localhost:5000/demo/stencils/simple-r/`.

But...that docker image needs some upgrades to play nice with the frontend. So, you'll have to do a `docker pull stencila/ubuntu-14.04-r-3.2` when I have done those upgrades.

Also, I'm working on the hub so you won't need to do any of this soon.

**Comment by michael** [comment]
Just ping me when the updates area ready.

 I got docker running again but not getting everything to npm install. Maybe you could use curl instead of wget in the postinstall.sh.

```bash
postinstall.sh: line 58: wget: command not found
tar: Error opening archive: Failed to open 'node_modules/mathjax.tar.gz'
mv: rename node_modules/MathJax-2.5.3 to node_modules/mathjax: No such file or directory
Shrinking MathJax
postinstall.sh: line 65: cd: node_modules/mathjax: No such file or directory
find: config: No such file or directory
find: jax/output/HTML-CSS/fonts: No such file or directory
Copying MathJax build
cp: node_modules/mathjax: No such file or directory
```

**Comment by michael** [comment]
Oh and we need to specify a sha for the substance dependency, it currently is set to master which has some breaking API changes. Will try to find the correct sha and push.

**Comment by michael** [comment]
There seems to be something wrong with the proxying also. When I open:

```http://localhost:5000/demo/stencils/simple-r/``` it downloads the page instead of displaying it. Maybe that's because of the outdated docker image.

**Comment by nokome** [comment]
@michael yeah that download thing is due to missing content-type header - I have fixed it but not updated the docker yet - need to do a binary release for that.

**Comment by michael** [comment]
ok. Let me know when it should work for me. As soon as I have a running system I can look into your Tool problem.

**Comment by nokome** [comment]
@michael : I've done the update so do a docker pull and this should wgork better - althought there are some other bugs on the front-end!

**Comment by michael** [comment]
Hey I did the docker pull, but now I get a socket error. :/

```bash
Error: socket hang up
   at createHangUpError (_http_client.js:203:15)
   at Socket.socketOnEnd (_http_client.js:288:23)
   at emitNone (events.js:72:20)
   at Socket.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:905:12)
   at doNTCallback2 (node.js:441:9)
   at process._tickCallback (node.js:355:17)
```

Let's investigate in SF!

**Comment by nokome** [comment]
@michael : mmm, sorry it didn't work, not sure what has happened there; but yes lets leave it until we're face-to-face.

**Comment by michael** [comment]
We had a bit of a crazy day.. like a whole lot of last-minute actions. ;) 

We'll take care of it soon. If it comforts you.. we also failed to tag Substance beta2 before the trip. VERY close but some new issues are blocking it.

See you in a few hours!
