### ISSUE TITLE
Install of MathJax in web module

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#78]
For some reason `npm` does not like downloading and extracting the MathJax tar ball. So `wget` is used. in `web/postinstall.sh`.

But not everyone has `wget`. See: https://github.com/stencila/stencila/issues/77#issuecomment-160266518

Use curl? Or, find a way to make MathJax work with npm? See https://github.com/mathjax/MathJax/issues/951#issuecomment-78446423 and comments above it.

**Comment by michael** [comment]
Ideally we can make this pure npm (if needed come up with our own Mathjax package on Github). Also we should get rid of the proxying where possible, so that the static version can installed, and run using a pure Node.js + npm workflow.

**Comment by nokome** [comment]
Thanks @michael . Yes, I think it should be pure npm ideally. Will ask the mathjax people about the best approach.

I agree that the static version should not rely on proxying. But we can get that by implementing a JS in-browser rendering engine. Proxying is still useful if you wn to test using with an R rendeiring engine during development.

**Comment by michael** [comment]
It's not too bad what we have now.. just a few indirections we should remove and then we are good for static and integrated development.

I think we can strip down stencil.js into a more dumb and straight forward integration, and factor out a StencilAPIClient API (currently we call this stencil backend, which is a bad name) that can either be a stub.. for local static dev... or a full-fledged integration that talks to a real backend. 

The JS in-browser rendering option would be nice too. I can help with that!

Oh and I reached out to @pkra regarding MathJax + npm. Will keep you posted.

**Comment by oliver----** [comment]
@nokome did you actually try to just npm install MathJax via github? I remember that the regular repo is executable already, i.e. has the dist in it.

**Comment by pkra** [comment]
> For some reason npm does not like downloading and extracting the MathJax tar ball. So wget is used. in web/postinstall.sh.

I'm guessing this is just the usual delay of unzipping 30K files...

> Oh and I reached out to @pkra regarding MathJax + npm. Will keep you posted.

Some over-eager user published MathJax to NPM so it's out of our control for now. 

There's also a bower module, in particular a components/MathJax module (without the PNG fonts), maintained by IPython devs. There's also https://github.com/pkra/MathJax-single-file.

**Comment by nokome** [comment]
With `"MathJax": "mathjax/MathJax#ba9afeb",` in `dependencies` I get:

```
nokome@Pluto ~/s/s/s/web (substance-beta2)> npm install
npm ERR! addLocal Could not install /tmp/npm-22830-a5a72283/git-cache-a850b384787c/ba9afeb5a743249acdea17540b48b14ebc95dbe4
npm ERR! addLocal Could not install /tmp/npm-22830-a5a72283/git-cache-1f64bad2a1fc/ba9afeb5a743249acdea17540b48b14ebc95dbe4
npm ERR! addLocal Could not install /tmp/npm-22830-a5a72283/git-cache-e3353e1273dc/ba9afeb5a743249acdea17540b48b14ebc95dbe4
npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EISDIR
npm ERR! errno -21

npm ERR! EISDIR, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nokome/stencila/source/stencila/web/npm-debug.log
```

This obscure message seems to be due to the fact that MathJax does not have a `package.json` file (see https://github.com/npm/npm/issues/7232 and links therein).

So, adding a `package.json` to mathjax/MathJax could fix this. I might create a fork and see if it works. Would prefer to be able to use latest release of MathJax than rely on the npm module that is out of date or requiring another build tool (e.g. bower).

**Comment by nokome** [comment]
So, I created a fork and added `package.json` and now `npm install` works with `"MathJax": "nokome/MathJax#24b0e9e1bfbbc466970081084a97ad0ee3b8788b"` in dependences.

@pkra : it would be great if a `package.json` could get added to Mathjax so we don't have to maintain a fork just for this. Let me know if you want a pull request.

**Comment by oliver----** [comment]
Great!

**Comment by michael** [comment]
Super! Thanks. Was it really just the package.json that needed to be added? So the full build of MathJax is already included?

**Comment by pkra** [comment]
See https://github.com/mathjax/MathJax/issues/1328

**Comment by nokome** [comment]
@michael : yes, `package.json` was all that was needed; the full repo gets downloaded and our `postinstall.sh`still does the trimming down to reduce the size.

@pkra : thanks for your new issue

Closing this now, will move to using mathjax/Mathjax in dependencies if/when  mathjax/MathJax#1328 is completed.
