### ISSUE TITLE
Chromium does not exist in expected location

### ISSUE THREAD

**Issue by stefanfritsch** [stencila/stencila#787]
Hi,

when trying to run the `.exe` of `v0.34.0` after unzipping it I get the following error:

```
C:\Python38>stencila.exe
� ERROR encoda:puppeteer Chromium does not exist in expected location: C:\snapshot\stencila\node_modules\puppeteer\.local-chromium\win32-768783\chrome-win\chrome.exe
� ERROR stencila Please provide a command.
```

I assume there are steps in the install instructions missing?

Thank you,
Stefan

**Comment by nokome** [comment]
Hi Stefan,

Thanks for the bug report. Chromium should be bundled as part of the distribution (we use it for doing some of the format conversions e.g. to PDF). I don't think there is an installation step missing, rather that Chromium is not being bundled or is not being extracted to the correct place.

I will take a look into it and get back to you here.

Thanks, Nokome
