### ISSUE TITLE
docs: Fail build when any step errors

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#789]
Currently when there is an error when building and deploying docs it is not shown as an error under GitHub actions e.g. https://github.com/stencila/stencila/runs/973355945?check_suite_focus=true#step:5:29

![image](https://user-images.githubusercontent.com/1152336/89956241-e4c4ff00-dc88-11ea-8928-c30261e4a0b5.png)

**Comment by alex-ketch** [comment]
Closed by 8d3ba65408e941bc9309eeddff7915af52133476
