### ISSUE TITLE
🌈 Contributing: Good First Issues

### ISSUE THREAD

**Issue by alex-ketch** [stencila/stencila#798]
Hi, and thank you for looking to contribute to Stencila! 💖

Below you will find links to lists of good issues which should be approachable and help familiarize yourself with the codebase.
If you have questions, or need guidance at any time, please feel free to comment on an individual issue or join us on our [Discord channel](https://discord.gg/uFtQtk9).

**If you would like to work on an issue, please leave a comment on the issue to let others know that it is being worked on.**

---

## Projects
- [↔️ Encoda](https://github.com/stencila/encoda/labels/good%20first%20issue) (TypeScript): Codecs for executable documents
- [☸️ Hub](https://github.com/stencila/hub/issues?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen) (Python, TypeScript, CSS): Hub for executable documents
- [🎨  Thema](https://github.com/stencila/thema/issues?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen) (CSS, TypeScript): Semantic themes for executable documents
- [🎨 Designa](https://github.com/stencila/designa/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) (CSS, TypeScript, WebComponents/StencilJS): Component library, design resources, and style guide
- [🐳 Dockta](https://github.com/stencila/dockta/issues?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen): A Docker image builder for researchers
- [🔧 dev-config](https://github.com/stencila/dev-config/labels/good%20first%20issue): Shared development configurations for Stencila projects

## More ways to contribute
- 🐛 Bug reports with steps on how to reproduce them are incredibly helpful in improving the platform. If you encounter problems with a project, please file an issue.
- 📚 Documentation improvements is one of the best kinds of contributions you can make. All our documentation [lives at http://help.stenci.la](http://help.stenci.la/en/), and the source can be viewed at [stencila/stencila/help](https://github.com/stencila/stencila/tree/master/help). Whilst we currently don't have a list of outstanding help articles, please [create an issue in this repository](https://github.com/stencila/stencila/issues/new/choose) if you have ideas for improvements.
- 🧐 Other: If there's something you'd like to contribute but don’t see it on this list, don’t let that discourage you. Please create an issue in the appropriate repository so that we can start a discussion.

---

Stencila strives to be a welcoming community for all, we ask everyone to read and abide by our [Contributing Guidelines](https://github.com/stencila/hub/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/stencila/policies/blob/master/conduct.md).

- [🧭 Contributing Guidelines](https://github.com/stencila/hub/blob/master/CONTRIBUTING.md)
- [🥳 Code of Conduct](https://github.com/stencila/policies/blob/master/conduct.md)
- [🗣 Stencila Discord chat](https://discord.gg/uFtQtk9)

**Comment by prathamesh3707** [comment]
can i do it

**Comment by nokome** [comment]
> can i do it

Sure @prathamesh3707 ! Just let us know if you need a hand getting started
