### ISSUE TITLE
Normalize labels across repos

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#799]
We would like to have a consistent set of issue labels across all our repos. As this is our umbrella repo, this seems to be the best place for this issue.

Note that it is possible to set [default labels for *new* repos](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization) but these are not applied to existing repos and are probably not synced if there is a change to the defaults after creation. The best option I have found so far for this is: https://github.com/Zebiano/Labeler.

One option would be to implement the syncing in Labeler by pulling the default issues and applying them to the other repos.

**Comment by nokome** [comment]
Some labelling inspo:

- https://github.com/remarkjs/remark/issues
- https://github.com/commercetools/commercetools-docs-kit/issues
- https://github.com/kubeflow/community/blob/master/issue-labels.md

**Comment by wooorm** [comment]
We have automated this and more in a Travis cron job, might be of interest: https://github.com/unifiedjs/github-tools

**Comment by nokome** [comment]
Thanks @wooorm that is indeed super useful.

Gotta say that I continue to be in awe at the amazing job you do maintaining the `unified` collective. It's an outstanding example of open source stewardship. Well done :clap: :1st_place_medal: !
