### ISSUE TITLE
MathJax currently broken in the static version

### ISSUE THREAD

**Issue by michael** [stencila/stencila#83]
It fails in StencilEquationComponent where the MathJax object is not correctly initialized.

I see this code in stencil.js

``` js
window.MathJax = {
  skipStartupTypeset: true,
  showProcessingMessages: false,
  showMathMenu: false,
  "HTML-CSS": {preferredFont: "STIX"}
};
window.Stencila.load('/get/web/mathjax/MathJax.js?config=TeX-MML-AM_HTMLorMML',MathJaxAdd);
```

Maybe we can get rid of this in favor of a regular script loading (meaning that we include the <script> tag in the static HTML.

**Comment by nokome** [comment]
@michael let's deal with #78 and then come back to this one. I would prefer to have only one <script> tag in the HTML but if we need to have more then so be it.
