### ISSUE TITLE
Integration with PS

### ISSUE THREAD

**Issue by esetera** [stencila/stencila#86]
hey chappies

Its a great demo and great video. Nokome - when we discussed this in SF you were planning to integrate this with PS. Is that still the case? If so we should schedule some time and work out when it would be good to do it. We can then take the demo and show others to drive traffic to you as well as demonstrate the flexibility of PubSweet.

**Comment by nokome** [comment]
Yep, @esetera still keen to do this. Just a matter of when. As you say, we need to schedule some time for that. My Jan-Apr are already looking really busy. But this might not take too long. Once the authentication stuff is worked out (on both sides) it should, in theory, be not too hard. I'll keep touching base with @jure and you and see if we can slot some time in during January.

**Comment by esetera** [comment]
hey @nokome. That is really good news. I would very much like to promote the work you are doing and I think we can 'shop it around' a lot easier and more compellingly if we can show a PubSweet integration.

**Comment by nokome** [comment]
Hey @jure, @oliver---- , @micheal : you're all having a meetup next week, right? Is that a good time to get the ball rolling on this?

**Comment by michael** [comment]
Definitely. Our main topic will be integration of realtime collab features into PS. But I think we should use the time together to come up with an implementation plan for Stencila integration.

**Comment by micheal** [comment]
I probably shouldn't be on this. ;)

**Comment by esetera** [comment]
yeah, I think the primary focus is the collab hub integration. Since
Nokome is remote it would be good to discuss the sheets and a plan, but
look to integrate it after the in-person meeting.

adam


On 03/04/2016 11:08 PM, Michael Aufreiter wrote:
> Definitely. Our main topic will be integration of realtime collab
> features into PS. But I think we should use the time together to come up
> with an implementation plan for Stencila integration.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stencila/stencila/issues/86#issuecomment-192217406>.
> 

-- 

---
Adam Hyde
http://www.adamhyde.net/projects

**Comment by jure** [comment]
Yes, meetup focus is the collab hub. We could have a short planning session on Sheets integration though, I imagine @michael and @oliver---- have a better understanding of Stencila's architecture so that would be helpful.

Perhaps we can start a discussion on the requirements here though: What sort of things would we need to provide in order for Stencila/Sheets to live within PubSweet?

**Comment by nokome** [comment]
Great, thanks all. Yes, @michael and @oliver---- best placed to get this started since they know both systems. Will wait to hear from you.

**Comment by nokome** [comment]
In the process of cleaning up old issues. Feel free to re-open but for feature ideas, a new topic in the Ideas category at https://community.stenci.la/ is preferable.
