### ISSUE TITLE
Update method: ensure only dependent cells are updated

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#89]
In sheets, the choice of dependent cells to update is suboptimal. Currently, we use a topological sort and then update all cells in the list _after_ the current one. But this updates cells which may not be directly dependent on the current one. Instead, we probably need to walk the dependency graph from the current cell, checking for circularity on the way.

**Comment by oliver----** [comment]
In JS I filter only cells with a changed value.

**Comment by nokome** [comment]
Great. I will fix the backend dependency analysis. But in any case it may be worth doing this filtering in the backend too - dependants of a cell may have changed but not the resulting string representation when it is evaluated. That would save traffic over the wire.

**Comment by oliver----** [comment]
Yep :+1:

**Comment by nokome** [comment]
Currently, at 55be430, this seems to be creating buggy results when you clear a cell - set it's contents to empty. In one case I was not able to do anything more with the sheet after this. In this case you will need to deactivate the session manually to get a new clone of the same sheet, or `/+sheet` to create a new one.
