### ISSUE TITLE
Upgrade Substance version

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#90]
Currently using `substance/substance#4a95ecead71b2eab24353e1b6dd76f50adec7e4e`

**Comment by nokome** [comment]
Closed with 290be218fea308c8abec7db54af0bbd7dd1f391a

**Comment by oliver----** [comment]
I wanted to upgrade the stencil code as well

**Comment by nokome** [comment]
Oh, cool, yes, that would be good. Thanks!

**Comment by oliver----** [comment]
Done.
