### ISSUE TITLE
Speed up manual data entry

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#92]
At present to modify a cell's source you need to double click on it, edit the source and then press enter (which annoyingly adds a newline to the source). Need to be able to quickly edit cells without doing the double click: ie. type, enter, type, enter..., tab, enter, type etc

**Comment by michael** [comment]
I thought about this too. Cursor navigation of cells is powerful, however even in Excel/Good Spreadsheet there's no keyboard shortcut (or I am missing it) to start editing the selected cell. You have to doubleclick that cell to edit the existing content. It would be nice to just hit enter instead to activate the edit. Then change the contents and hit enter again to confirm.

**Comment by oliver----** [comment]
Is now working.
