### ISSUE TITLE
Desktop: Project side bar width slider

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#936]
The width slider for the project sidebar is a little hard to discover. I think most people are used to being able to adjust width by hovering over the left hand side of the divider (upon which the line is highlighted and the cursor becomes a <-> arrow).

![Peek 2021-05-19 16-03](https://user-images.githubusercontent.com/1152336/118754845-e8db1880-b8bb-11eb-8f3b-348479644411.gif)

**Comment by alex-ketch** [comment]
Closed by #939
