### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#96]
Create methods (exposed as Web API as well) that list and specify code snippets for a `Spread` (later to be merged with `Contexts` so available to `Stencils` as well).

`snippets()` method and `GET @snippets` API endpoint to return a nested JSON object of snippet name/descriptions that can be browsed or searched:

```js
 {"Maths":{"sum":"Sum of numbers", "count": "Count of ..."}, "Dates and times":{...}}
```

`snippet(name)` method and `GET @snippet?name=xxx` to return a JSON object specifying the snippet:

```GET @snippet?name=log10```:
```js
{
    "desc" : "Base 10 logarithm of value",
    "params" : {
        "value" : {
            "desc": "Value to compute logarithm for"
        }
    },
    "code" : "log10(${value})"
}
```

This uses the same ES6 string substitution format used by [SublimeText snippets](http://docs.sublimetext.info/en/latest/extensibility/snippets.html) and [Ace snippets](https://cloud9-sdk.readme.io/docs/snippets) but instead of having a placeholder syntax makes that explicit using `default` in `params`.

But with optional parameters it is difficult (impossible?) to generate valid and succinct code with substitution. So we might add a `eval` attribute which gives JS expression for generating a snippet. e.g.

```js
{
    "desc" : "Sum of values",
    "params" : {
        "value" : {
            "desc": "Values to sum"
        },
        "na_rm" : {
            "desc": "Should missing values (including ‘NaN’) be removed?",
            "optional": true
        }
    },
    "eval" : " 'sum('+nums+na_rm?(","+na_rm):''+')' "
}
```
An `exec` attribute could be used for more complicated, multiline code generating functions.

These will be used to generate UI's for setting cell expressions. This is what it looks like in Calc:
![image](https://cloud.githubusercontent.com/assets/1152336/12283039/18b646be-ba08-11e5-8311-d5bc272310b2.png)

**Comment by nokome** [comment]
Twould be good to be able to re-edit a cell's source via the snippet UI. Rather than trying to parse the cell expression, that could be done by storing the snippet name and attributes for a cell and then regenerating the expression (would need to turn off manual editing of cell source or get user to confirm explicit un-snippetting of cell)

```
{
  "A2":{
    "name":"log10",
     "params":{
       "value":"A1"
     }
  }
}

**Comment by nokome** [comment]
@michael and @oliver---- : please have a look at this commit 17cdde1. It adds preliminary documentation around snippets and some devserver endpoints. We can discuss later when you have had a chance to tear it apart!

**Comment by michael** [comment]
Nice preparation. Thanks! I will start with modelling a Snippet component that visualizes the data from the JSON but also provides some highlight ability.. e.g. the parameter you are currently editing in the source.

**Comment by michael** [comment]
I slightly modified the JSON spec. What we need is a static description of the arguments of a function. Each arg gets a name and description plus flags like `optional` or `variadic` (like  "[value2...]" maybe you have a better name for it).

That's the JSON i will consider in the componet for now. I would not display more information inline as it takes too much space. A link "Learn more" could open a documentation page that has snippets and examples rendered in full.

```js
{
	"name": "sum",
	"summary": "Returns the sum of values.",
	"notes": [
		"If only a single number for `values` is supplied, `sum` returns `values`"
	],
	"args": [
		{
			"name": "value1",
      "descr": "The first number or range to sum up."
		},
    {
      "name": "value2",
      "descr": "Additional numbers or ranges to add to value1",
      "variadic": true,
      "optional": true
    }
	],
	"examples": [
		"sum(A1)",
		"sum(A1:A10, 100)",
		"sum(A1:G10, A2:G12, 14)"
	],
	"see": [
		"sumsq",
		"sumif",
		"product"
	],
        ... 
}
```

**Comment by nokome** [comment]
Array of args - Hah, yeah I had it as an array like you suggest and then tried to be more terse for snippet authors. Fine.

Name "args" v "pars" - you prefer "args"? ; fine with me.

Variadic - good idea to have this but I don't think we will use it much - it's hard to explain here, but to generalize this across context languages I think we need to take a different approach to specifying multiple cells as inputs into functions. Instead of having `sum(A1:A2,G4, B3:C8)` I am proposing a cell union operator `&` so it becomes `sum(A1:A2&G4&B3:C8)`. I think this will play a lot better with snippet code generation and different languages. It is also more semantic : commas are for delineating function arguments, ampersand is for union of cells and is similar to the colon operator in this sense.

Shape - you did not include this but it is important and related to the above - from the `snippets/schema.yml` : Permissible shape for the sheet cells used as arguments to this parameter.    Valid values include :
- `one` (a single cell e.g. `A1` or a literal value e.g. `428`)
-  `block` (a contiguous range of cells e.g. `A1:G10`).
-  `list` (a list of cell IDs e.g. `A1:A5&G4`)

Shape is important because in the host language e.g. R it might be expecting an atom (ie. `one`), a `vector` (ie. `list`) or a `data.frame` (ie `block`). Internally, we transforms the cell expressions into the right type.

**Comment by nokome** [comment]
Oh, also, you prefer `"optional": true` over `"required":true`? Probably more terse.

**Comment by michael** [comment]
Yeah I thought required is the default. Let's go with parameters. That's just fine.

Union could be an option. Just thought that people would be more familiar with the repeatable (variadic) parameter pattern (excel, google sheets).

Will consider shape.. now I got what it's for. Just wonder how we should best visualize the shape of a param without using a lot of space. displaying "any" is not of great help.

**Comment by michael** [comment]
I think it's nice to have this formal to validate the user input. However for the snippet description a literal description may be easier to grasp.

**Comment by michael** [comment]
*value: Number or cell or range of cells to sum up.*

or

*value1: First number or cell or range of cells to sum up.*
*value2: Additional expressions to add to value1*

But not:

*value {one,block,list}: Things to sum up*

**Comment by michael** [comment]
Made a design sketch (pretty much what Google doc does - slightly more compact)

![image](https://cloud.githubusercontent.com/assets/2931/12492634/777ae8ce-c081-11e5-8248-93906fe702e7.png)

**Comment by nokome** [comment]
Agree, for the user we need to display something like "value: Number or cell or range of cells to sum up." but still have `one, block, list` in snippet spec to guide/validate their selection.

Like your sketch, I was thinking myself that Google's could be made more compact

**Comment by nokome** [comment]
> Union could be an option. Just thought that people would be more familiar with the 
> repeatable (variadic) parameter pattern (excel, google sheets).

I agree, that in the spreadsheet world that variadic is more common. But in the code world it is less so. And we're trying to provide a spreadsheet like "projection" of the code world - so I think we should not use variadic too much. Also, technically, I imagine variadics will be difficult for code generation logic.

**Comment by michael** [comment]
I'll just start with that as a working version. We can discuss the details later. I think with the generic params concept we can reach any of those options pretty easily..

**Comment by nokome** [comment]
I've updated the spec 55dbabf. Can you rebase (?) so it's in `substance-dev`. Then, I can switch over to there and perhaps work on the snippet code generation. Sound OK?

**Comment by michael** [comment]
Let's rather merge our stuff into develop when ready. Since Oli and I work on that same branch so rebase hurts. I will work with a static version for now anyway and later we connect to the backend.

**Comment by nokome** [comment]
OK, I'll just work in develop in `shippets` dir on snippet code gen.

Also, I thought I would remind you that some snippets may have to be quite long and multiline (e.g. for producing plots with lots of options specified). So we are not just limited to single line function calls as in Excel etc. Will have consequences for UI.

**Comment by michael** [comment]
First implementation:

![snippets](https://cloud.githubusercontent.com/assets/2931/12498164/c8b8a5fe-c0a0-11e5-9928-742660a16c3a.gif)

There seems to be some bug with the evaluation that's why we only see undefined. However it worked for us a few times. Was just not able to capture it on the screencast.

**Comment by nokome** [comment]
Wooot! :balloon:

**Comment by nokome** [comment]
I've been working on snippet schema and build integration here : c8e003d.
And on hosting snippets in production for consumption by the UI and humans: https://stenci.la/snippets
Comments and suggestions welcome. We need to try out the schema more before writing too many more snippets - but we need to write more snippets to really try it out :sweat:!

**Comment by michael** [comment]
Good morning. I guess now is a good time to merge into develop. We may be a bit late for the call. Oli didn't make it here yet after exhausting skiing day yesterday. ;)

**Comment by nokome** [comment]
No problems, just let me know when you are ready

On Fri, Jan 22, 2016 at 9:31 PM, Michael Aufreiter <notifications@github.com

**Comment by michael** [comment]
We call in five mins.

**Comment by nokome** [comment]
OK, "functions" it is! We might use snippets later for actual snippets of text

**Comment by oliver----** [comment]
For snippets I would go for a classical template approach, like it is done in Sublime for instance.
I.e., guiding the user to fill out all template variables, and adopting general editing capabilities, not introducing new editing concepts.

**Comment by nokome** [comment]
So, I've renamed this Functions and done the renaming in the code too. Sheets now have two new API methods:

- `functions`: returns a JSON array of function names
- `function`: returns a JSON specification of a function

Note that both of these are now generated dynamically and that `functions` may need to be updated if the user imports a package thereby increasing the number of available functions.

The current R implementation involves the parsing of documentation files and this could be improved. In particular, at present newlines and other whitespace is propogating through to the JSON. This will be fixed...sometime.

I have done an initial integration into the web front end:

- web/sheet/engine/SheetRemoteEngine.js - includes some initial ideas about caching function specs.
- web/sheet/ui/CellEditor.js Line 30 - but seems to have broken the display of `FunctionComponent`

@michael : hopefully you can take it from here. But I no hurry - would probably be better to wait for some back end stability and websockets to make the getting of function specs less frustrating.

**Comment by michael** [comment]
Thanks for the update. I will have a look some time this week.

**Comment by michael** [comment]
Hey! 

Some quick thoughts:

- it would be good if we keep all functions in a local cache so we can access them synchronously and get a responsive auto complete
- so we could have a set of default functions and then load more functions as more packages are imported (ideally with a scoped query (e.g. GET /functions/PACKAGENAME)
- for the initial page load a reasonable way would be to serve all available function names with the index.html file so we don't need to trigger an extra async request after page load.

web/sheet/ui/CellEditor.js Line 30: this breaks because there must not be any async code in render functions. As said we should have all available functions (at least the names) accessible locally so we can implement a ChooseFunction component that updates as you type.

**Comment by nokome** [comment]
Re local cache: agree completely and started implementing it that way https://github.com/stencila/stencila/blob/develop/web/sheet/engine/SheetRemoteEngine.js#L20

Re updating function list: currently for an R context `GET /functions` returns all functions in scope. When a cell is updated to say `= library(ggplot2)` the front end needs to know that it needs to update its list of function names. For that reason, as well as getting dependency order right I am thinking of making an explicit cell type for imports e.g prefixed by a semicolon ':' e.g. `: library(ggplot2)`. Currently, the backend regex matches for `library(.+)` and knows that needs to be executed first - but the semicolon approach is more explicit and lets the fontend also know that it needs to update the function list (and possible other stuff in the future)

Re initial page having a list of functions: I'd prefer to do an async request because the list of functions is dependent on the R context that the sheet is currently attached to, not the sheet itself - feels like it's polluting the HTML with extra info unessarily

**Comment by nokome** [comment]
Closing this issue. There are still plenty of specifics to be done by the foundations of functions as outlined here are complete. Thanks y'all!
