### ISSUE TITLE
Desktop: increase language support in code editor and switch based on document format.

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#969]
The code editor currently only supports syntax highlighting for Bash, Python and R and does not seem to switch language when the format of the open file changes.

Previously I've suggested we need a big map of formats identifiers (usually file extension) to info for that format. Adding a CodeMirror mode to that could be useful here e.g.

```ts
const formats = {
    'png': {
        preview: true,
    }
    'tex': {
        editor: true,
        editorMode: 'stex',
        preview: true
    }
}
```

**Comment by alex-ketch** [comment]
This was addressed by updating Stencila Components package to v0.33.0 (https://github.com/stencila/stencila/commit/725bb46e9a0cc958dcaae561418aec7da7124c09)
