### ISSUE TITLE
Cell formatting

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#97]
There is currently no formatting (e.g. bold, color etc) for cells. It would be good to make formatting either static or dynamic (i.e. dependent on the value of the cell, ala "conditional formatting" in Excel). 

One approach to this would be to have a `formats.json` file which specifies, for certain cell ranges,  mappings between CSS attributes and host language expressions which are evaluated in the spread with the variable `value` being the value of the cell e.g.

``` json
[
       {
                "cells": "A1:B6",
                "background-color": "hsv(value,0.8,0.8)",
                "font-style": "ifelse(value<0,'italic','normal')"
        },
        ...
 ]
```

Expressions could just be constants too:

``` json
 {
     "cells": "A43",
     "background-color": "red",
},
```

In C++ this would need a `std::vector<std::map<std::string,std::string>> Sheet::formats_` and a `uint Cell::format` index which points to the element in the formats vector and `style` attributes to be added to cells when generating HTML and in the JSON result from `@update`.

In the UI we would need a formatting tool that would allow a user to select CSS attributes and assign expressions to them - and buttons for quickly doing the normal stuff : bold, background color, borders etc

**Comment by michael** [comment]
Oh that's actually a nice idea. I like the stylesheet approach.

**Comment by nokome** [comment]
Over on HN, @samfisher83, pointed out these Excel paintings: http://www.quertime.com/article/arn-2012-08-22-1-25-drawings-and-games-made-with-microsoft-excel/

Between cell mapping #118 and this cell formatting we should be able to do something similar quite easily. Would be a fun demo.

**Comment by oliver----** [comment]
I think conditional formatters should consist of three parts:
```
cells: <cell-or-range-expression>(, ...),
expression: <expression evaluating to a boolean>,
style: <css-style-string> -> more semantical would be a category/class that can be styled via css
```

**Comment by nokome** [comment]
That's an option but it would exclude the possibility to map data onto style attributes like color to do things like: http://policeanalyst.com/creating-heat-maps-from-excel-pivot-tables-with-conditional-formatting/ 

![image](https://user-images.githubusercontent.com/1152336/33743595-6f576c22-dc12-11e7-9339-563c85f658da.png)

Anyway, let's come back to this later. I still see this as a different topic to cell issues/comments. It's more about data visualisation than tagging of cells.

**Comment by Integral** [comment]
God! I would like to see this thing in spreadsheet editor!

**Comment by oliver----** [comment]
I think we should talk about this now :)

So what you are saying is that it is desired to provide keys=css-style-keys with values being treated as templates, right?

**Comment by oliver----** [comment]
BTW, this is an important source for requirements for the implementation of 'issues' as I think all dynamic, cell based evaluators are similar: depend on a set of cells, executing an expression or built-in function, storing information on the cell-state. They differ in the way how the result is mapped.

**Comment by nokome** [comment]
> I think we should talk about this now :)

Fine :smile: 

> So what you are saying is that it is desired to provide keys=css-style-keys with values being treated as templates, right?

Yes, may be this concept is better called "data-driven styles" instead of "conditional formatting" (the legacy term). Each CSS `property` has a `value` generated by an expression which is evaluated against the value of the cell.

Now we have multiple languages in a single sheet we would need to add a language attribute:

```json
var dataDriveStyle = {
   cells: "A1:B6",
   properties: {
     "background-color": {
         language: "r",
         expression: "hsv(sin(value),0.8,0.8)"
     }
  }
}
```

Note this example uses the `hsv` function in R which returns a hex colour string https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/hsv.html . But I'd suggest the language would default to `mini` and we implement analagous functions there.

**Comment by oliver----** [comment]
Would it be acceptable to use one language per formatter?

**Comment by oliver----** [comment]
I like the idea. While this is not very semantical, it gives the user great flexibility

**Comment by oliver----** [comment]
> hsv function in R which returns a hex colour

I think we could do some auto-completion depending on the key.
E.g. in jquery (or Substance DOMElement) it is possible to set `el.css('width, 100)` which adds 'px' in that case.

**Comment by nokome** [comment]
> Would it be acceptable to use one language per formatter?

Yes, I think that would be fine most of the time. If someone really wanted to do something funky (like use some special function only available in R) then it could be overriden:

```js
var dataDriveStyle = {
   cells: "A1:B6",
   properties: {
     "font-weight": max(value * 100, 500),
     "background-color": {
         expression: "hsv(sin(value),0.8,0.8)"
         language: 'r'
     }
  }
}
```

> I like the idea. While this is not very semantical, it gives the user great flexibility

Actually, I think it is semantic because it's formatting derived from the data (using expressions stored in the sheet) no ad-hoc formatting.

**Comment by oliver----** [comment]
Ok. Thanks. Captured :)

💯

**Comment by oliver----** [comment]
Proposal for the first iteration:
```
cells: "C1:B10", 
language: 'r',
styles: {
  "font-weight": max(value * 100, 500),
  "background-color": "hsv(sin(value),0.8,0.8)"
}
```

**Comment by oliver----** [comment]
@nokome  What is your take on conflicting formatters?

**Comment by oliver----** [comment]
Just realized that this is inconvenient for applying different styles for the same premise.
Should we change the proposal to
```
cells: "C1:B10", 
language: 'r',
expression: <boolean>,  ->  if true style is applied
styles: {
  "font-weight": max(value * 100, 500),
  "background-color": "hsv(sin(value),0.8,0.8)"
}
```

**Comment by nokome** [comment]
> @nokome What is your take on conflicting formatters?

I was thinking that there would only be one formatter per cell.

> One option would be 'extend', i.e. overriding on css-property level.

If we stick with one formatter per cell then this redundant - there would be no conflicts.

> Just realized that the previous proposal is inconvenient for applying different styles for the same premise.

Not sure what this means, sorry.

**Comment by oliver----** [comment]
> I was thinking that there would only be one formatter per cell.

Coming from a technical point of view: formatters are associated to cells via a cell or range expression, i.e. multiple formatters could be associated to the same cell.

Re the other point:
```
cells: "C1:B10", 
language: 'r',
styles: {
  "font-weight": max(value * 100, 500),
  "background-color": "hsv(sin(value),0.8,0.8)"
}
```
This is supporting sophisticated use-cases like the 'heat-map'.

IMO this case is much more often:
```
cells: "C1:B10", 
language: 'mini',
expression: 'value < 0',
styles: {
  "background-color": "red"
}
```

**Comment by nokome** [comment]
> Coming from a technical point of view: formatters are associated to cells via a cell or range expression, i.e. multiple formatters could be associated to the same cell.

Your right, sorry didn't think about that long enough. Order of definition, last one wins makes sense then.

OK, get your other point now, yes need to have both. Suggest using `apply` instead of `expression`:

```
cells: "C1:B10", 
language: 'r',
apply: 'true',
styles: {
  "font-weight": "max(value * 100, 500)",
  "background-color": "hsv(sin(value),0.8,0.8)"
}
```

```
cells: "C1:B10", 
language: 'r',
apply: 'value < 0',
styles: {
  "background-color": "red"
}
```

**Comment by oliver----** [comment]
What do you think about this?
```
<formatters>
  <formatter apply="value < 0" language="mini">
    <cells>A1:B10</cells>
    <styles>
      <style property="font-weight" value="red" />
    </styles>
  </formatter>
</formatters>
```

```
<formatters>
  <formatter apply="true">
    <cells>A1:B10</cells>
    <styles>
      <style property="font-weight" expression="max(value * 100, 500)" language="r" />
      <style property="background-color" expression="hsv(sin(value),0.8,0.8)" language="r" />
    </styles>
  </formatter>
</formatters>
```

**Comment by nokome** [comment]
I keep on wanting to use the name "style" instead of "format". Not a strong preference but it slighly differentiates it from more adhoc formatting and Excel-style conditional formatting and more reflects that it's based-on CSS. So I would suggest:

```xml
<styles>
  <style apply="true">
    <cells>A1:B10</cells>
    <properties>
      <property name="font-weight" value="max(value * 100, 500)" language="r" /> <!-- a dynamic property -->
      <property name="background-color" value="red" /> <!-- a static property -->
    </properties>
  </style>
</style>
```
