### ISSUE TITLE
Sheet UI layout

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#99]
Setup overall UI layout with toolbar (activation toggle, save, commit etc buttons), expression bar (for editing cell expressions), side panel (for things like snippets #96 and cell contents #100, and lists of named cells). We should provide familiar spreadsheet UX but not slavishly copy what is in Excel, Calc, Google Sheets etc - freshness where appropriate; prefer minimal over busy!

**Comment by michael** [comment]
You think it would work to have it basically similar to the StencilWriter UI? Like the two column approach and toolbar on the top of the left pane. Do we want any formatting capabilities? Like strong/emphasis/link etc. for cells that act as labels and don't have data in it. I'm sure people will request background colors for cells as they are used to from Excel. ;)

**Comment by nokome** [comment]
@michael : yes, two columns (but preferably right column is optional and re-sizeable); perhaps all the formatting should go into formatting UI in the right column and encompass the ideas in #97 rather than cluttering up the toolbar too much.

Here's a sketch of my current thinking:
![image](https://cloud.githubusercontent.com/assets/1152336/12310148/8ecc0d4c-bab3-11e5-867b-8cba670ed893.png)

**Comment by nokome** [comment]
In the toolbar we need:

- activation/deactivation toggle icon - something like power on/off button, black when off, pulsating green when in process of activating, green when activated - calls `PUT @activate` and `PUT @deactivate` API endpoints as appropriate

- save button - floppy disk icon - calls `PUT @save` API endpoint (will no data, rely on calls to `PUT @update` when cell editing is done) - simply writes sheet to disk within session

- commit button - ? icon - opens a modal dialog asking for a commit `title` and `message` - sends to `PUT @commit` - commits in session clone _and_ pushes to origin

**Comment by nokome** [comment]
OK, as discussed, don't need (for now):
  - formula bar
  - an activation/deactivation button (will be done implicitly)
  - a save (write to disk) button and commit button - will be combined into save button

**Comment by nokome** [comment]
@michael : I spent a lot of time trying to get the backend to do the push back to master - auth issues with libgit2. Anyway, I've just cracked it (I think) - but wont have time to incorporate today - hopefully tomorrow.

**Comment by nokome** [comment]
Thoughts on activation workflow.

Thinking about using a thin  line under toolbar to indicate status :
 - grey when inactive
 - pulsing green while activating
 - green when active

When the user first tries to edit a cell:
- Notify them that in process of creating a personal copy and activating it (making it live)
- `PUT {address}@activate`
  - 401 response : require user to login - can we allow user to log in or create account without leaving page?
  - 200 response with JSON data on the session: successfully activated - indicate with solid green line at top

- `PUT {address}@session` occasionally to get the state of the session? Notify when session is active and ready for editing.

I might have to fix those endpoints to give the right behaviour.

**Comment by michael** [comment]
That sound good to me. Will get the UI in place. Take your time with finishing the API endpoints. I can simulate the behaviour for now.

**Comment by nokome** [comment]
Fixed them already - didn't take long :)

**Comment by michael** [comment]
After some thinking... We should maybe better differentiate Read vs Write usecases.

Read: No session needed, no save button present (instead there's open in editor or fork button if it's not your document)

Writer: R-Session is required upfront. If it's not there it would display a boot up screen with a progress bar.. starting your R session... The R session is actually activated not on sheet scope but on user scope, so if you switch to another document it would load faster without the splash screen.

Edge cases: A session could die unexpectedly (network error or timeout) while an editor is open. In this case I would block the user interface with a message prompt. 'Your sheet got deactivated due to inactivity. Click here to continue editing."

The advantage would be that there's no activate/deactivate concept in a sheet which is kind of unnatural. We should not confront the user with it. Imo it's better to make the start of the editor slower than displaying a half-working editor.

From an API point of view this would mean that we have a read endpoint and a write endpoint that does the activation implicitly if needed.

We could also have separate urls for write vs read:

http://localhost:5000/michael/SCndozXOTbOk
  -> GET `{address}@read`

http://localhost:5000/michael/SCndozXOTbOk/edit
 -> GET `{address}@edit`

**Comment by nokome** [comment]
I agree with about half of this I think. These are my short, perhaphs vague, sleep deprived thoughts:

- I'd prefer to avoid separate URLs - just keep one canonical
- When a sheet URL is hit we can see if the user has write access:
   - yes: then session is required activate the sheet straight away and user can start editing
   - no: don't activate the sheet but provide a fork button which opens a new tab with fork
- Instead of the splash screen I still think I would prefer to be able to view the sheet but see a notification about what is happening
- I like to start from the same static-read-only HTML and then have the JS start with a `PUT {address}@boot` (or some such) which will either start a session and return `{"mode":"write"}`, or return `{"mode":"read"}`

Enough ramblings from me, I need :zzz:

**Comment by michael** [comment]
Splash screen we could avoid since we have already renderable data which we can display. However, in edit mode we should not allow interactions until the session is really live. Otherwise there will be confusion if it looks like you can edit cells but then you get an error.

Sleep well!

**Comment by nokome** [comment]
@michael and @oliver---- , I have made changes as discussed to the API

I added `{address}@boot` if the user has `UPDATE` level rights to the component then it will automatically start a session, wait until the session is ready and the component has been cloned into it and then returns the user rights and the session details:

```json
{
  "session": {
    "id": 46,
    "user": {
      "username": "nokome",
      "url": "https://stenci.la/users/nokome"
    },
    "image": "stencila/ubuntu-14.04-r-3.2",
    "url": "https://stenci.la/sessions/46",
    "websocket": "wss://stenci.la/sessions/46@connect",
    "status": "Up Less than a second",
    "ready": true,
    "started": "2016-01-20T06:19:01.530Z",
    "updated": "2016-01-20T06:19:02.191Z",
    "pinged": null,
    "stopped": null
  },
  "rights": "UPDATE"
}
```

You should call `@boot` first thing and configure the UI based on `rights`. Session may be `null` if insufficient rights. Currently, it always returns `UPDATE` but in the future it could return from the list of heirarchial rights below (but they are not fully implemented yet).

```
NONE = 0
READ = 10
ANNOTATE = 20
UPDATE = 30
AUTHORIZE = 40
DELETE = 50
CREATE = 60
```

In `@update` and `@ping`, the sheet is activated, just like in `@boot` if it is not already - you can try this by manually calling https://stenci.la/api#!/Components/put_address_deactivate or https://stenci.la/api#!/Sessions/put_sessions_id_stop in the backgound in another tab.

I suggest that you keep calling `@ping` as it will mean that if the session does drop out, a new one can be pre-emptively launched.

I have not yet finished the `@save` endpoint changes - adding a `message` argument to it.

**Comment by michael** [comment]
Super. Will try this with our client boot process. Regarding ping... will this just give me the session status or also keep the session alive?

**Comment by nokome** [comment]
Will keep the session alive. It always responds with an empty JSON response `{}` - for 200 status codes anyway.

**Comment by michael** [comment]
Works.  Thanks a lot.

Still with calling it boot the technical implementation shines through. Maybe we call this endpoint GET {address}@open and make it also return the HTML. We will need this later when we have the server-side prerendering in place. But let's leave it as is for now and just go on with the other stuff.

**Comment by nokome** [comment]
Yeah, I thought about `open` :) . But that the user already has it "open" -
they are looking at it! Anyway, those who are using the API will be more
technical anyway - and I think it conveys more technical meaning to them -
the name is hidden to the user in any case.

Perhaps we should have something else for initial HTML since it is not
necessary on first page load e.g. `GET {address}@content` - that is what we
use for stencils

On Wed, Jan 20, 2016 at 9:53 PM, Michael Aufreiter <notifications@github.com

**Comment by nokome** [comment]
I've modified `PUT /{address}@commit` so it takes a `message` argument : 
```json
{
  "message": "string"
}
```
and returns a revision

```json
{
  "revision": "xxxxxxxxx"
}
```
See https://stenci.la/api#!/Components/put_address_commit. Its just a stub at the moment - does not do anything and always returns the above - but something to develop against.

I think `@commit` is better for this than `@save` because that is what it is doing and the message will end up in the commit log. I think that is what we agreed on and have some autosave feature - restoring  state of the clone in the session.

**Comment by michael** [comment]
Looks good. I'll get the commit message prompt into the save tool.

**Comment by michael** [comment]
Working version of the save dialog looks like this:

![image](https://cloud.githubusercontent.com/assets/2931/12447133/772c33dc-bf6e-11e5-8cea-b25ad4df288b.png)

**Comment by nokome** [comment]
After our discussion re taking snapshots of sheets and stencils. I think that we should have separate save and commit buttons. 

It's a bit foreign and a bit scary for some users to have to commit with a message that will be recorded in public history forever when all they want to do is press Ctrl+S and know that somehow, somewhere their work is getting saved in case their machine dies or whatever.

We can still have autosave - occasionally fire a `@save` request and have the save button go grey until further changes.

**Comment by nokome** [comment]
#132 deals with persistence stuff so closing this one
